/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {IndexRootQueryResponse} from "../../types/index-controller/index-root.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {indexRoot} from "../../clients/index-controller/index-root.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const indexRootSuspenseQueryKey = () => [{url: "/"}] as const;

export type IndexRootSuspenseQueryKey = ReturnType<typeof indexRootSuspenseQueryKey>;

export function indexRootSuspenseQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = indexRootSuspenseQueryKey();
	return queryOptions<IndexRootQueryResponse, ResponseErrorConfig<Error>, IndexRootQueryResponse, typeof queryKey>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return indexRoot(config);
		},
	});
}

/**
 * @description MAIN
 * @summary ROOT
 * {@link /}
 */
export function useIndexRootSuspense<TData = IndexRootQueryResponse, TQueryKey extends QueryKey = IndexRootSuspenseQueryKey>(
	options: {
		query?: Partial<UseSuspenseQueryOptions<IndexRootQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? indexRootSuspenseQueryKey();

	const query = useSuspenseQuery(
		{...indexRootSuspenseQueryOptions(config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
