/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {IndexRootQueryResponse} from "../../types/index-controller/index-root.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {indexRoot} from "../../clients/index-controller/index-root.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const indexRootQueryKey = () => [{url: "/"}] as const;

export type IndexRootQueryKey = ReturnType<typeof indexRootQueryKey>;

export function indexRootQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = indexRootQueryKey();
	return queryOptions<IndexRootQueryResponse, ResponseErrorConfig<Error>, IndexRootQueryResponse, typeof queryKey>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return indexRoot(config);
		},
	});
}

/**
 * @description MAIN
 * @summary ROOT
 * {@link /}
 */
export function useIndexRoot<
	TData = IndexRootQueryResponse,
	TQueryData = IndexRootQueryResponse,
	TQueryKey extends QueryKey = IndexRootQueryKey,
>(
	options: {
		query?: Partial<QueryObserverOptions<IndexRootQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? indexRootQueryKey();

	const query = useQuery(
		{...indexRootQueryOptions(config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
