/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {ConfigValueGetEnumListQueryResponse} from "../../types/config-value/config-value-get-enum-list.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getConfigValueGetEnumListUrl() {
	const res = {method: "GET", url: `/v1/config-value/enum` as const};
	return res;
}

/**
 * @description Enum 설정 조회 API
 * @summary v1 Enum 설정 조회
 * {@link /v1/config-value/enum}
 */
export async function configValueGetEnumList(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<ConfigValueGetEnumListQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getConfigValueGetEnumListUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
