/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {configValueGetEnumList} from "./config-value-get-enum-list.ts";
import {configValueGetItem} from "./config-value-get-item.ts";
import {configValueUpsert} from "./config-value-upsert.ts";

export function configValue() {
	return {configValueGetItem, configValueUpsert, configValueGetEnumList};
}
