/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {ConfigValueUpsertMutationRequest, ConfigValueUpsertMutationResponse} from "../../types/config-value/config-value-upsert.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getConfigValueUpsertUrl() {
	const res = {method: "POST", url: `/v1/config-value` as const};
	return res;
}

/**
 * @description 설정 생성/수정 API
 * @summary v1 설정 생성/수정
 * {@link /v1/config-value}
 */
export async function configValueUpsert(
	data: ConfigValueUpsertMutationRequest,
	config: Partial<RequestConfig<ConfigValueUpsertMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<ConfigValueUpsertMutationResponse, ResponseErrorConfig<Error>, ConfigValueUpsertMutationRequest>({
		method: "POST",
		url: getConfigValueUpsertUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
