/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {ConfigValueGetItemQueryResponse, ConfigValueGetItemQueryParams} from "../../types/config-value/config-value-get-item.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getConfigValueGetItemUrl() {
	const res = {method: "GET", url: `/v1/config-value` as const};
	return res;
}

/**
 * @description 설정 조회 API
 * @summary v1 설정 조회
 * {@link /v1/config-value}
 */
export async function configValueGetItem(params: ConfigValueGetItemQueryParams, config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<ConfigValueGetItemQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getConfigValueGetItemUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
