/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	ContentManagerSearchContentsQueryResponse,
	ContentManagerSearchContentsQueryParams,
} from "../../types/content-manager/content-manager-search-contents.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {contentManagerSearchContents} from "../../clients/content-manager/content-manager-search-contents.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const contentManagerSearchContentsSuspenseQueryKey = (params: ContentManagerSearchContentsQueryParams) =>
	[{url: "/v1/content-manager/contents"}, ...(params ? [params] : [])] as const;

export type ContentManagerSearchContentsSuspenseQueryKey = ReturnType<typeof contentManagerSearchContentsSuspenseQueryKey>;

export function contentManagerSearchContentsSuspenseQueryOptions(
	params: ContentManagerSearchContentsQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = contentManagerSearchContentsSuspenseQueryKey(params);
	return queryOptions<
		ContentManagerSearchContentsQueryResponse,
		ResponseErrorConfig<Error>,
		ContentManagerSearchContentsQueryResponse,
		typeof queryKey
	>({
		enabled: !!params,
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return contentManagerSearchContents(params, config);
		},
	});
}

/**
 * @description 컨텐츠 목록 조회 API
 * @summary v1 컨텐츠 목록 조회
 * {@link /v1/content-manager/contents}
 */
export function useContentManagerSearchContentsSuspense<
	TData = ContentManagerSearchContentsQueryResponse,
	TQueryKey extends QueryKey = ContentManagerSearchContentsSuspenseQueryKey,
>(
	params: ContentManagerSearchContentsQueryParams,
	options: {
		query?: Partial<UseSuspenseQueryOptions<ContentManagerSearchContentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? contentManagerSearchContentsSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{...contentManagerSearchContentsSuspenseQueryOptions(params, config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
