/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	ContentManagerGetTableInfoQueryResponse,
	ContentManagerGetTableInfoQueryParams,
} from "../../types/content-manager/content-manager-get-table-info.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {contentManagerGetTableInfo} from "../../clients/content-manager/content-manager-get-table-info.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const contentManagerGetTableInfoQueryKey = (params: ContentManagerGetTableInfoQueryParams) =>
	[{url: "/v1/content-manager/contents/table-info"}, ...(params ? [params] : [])] as const;

export type ContentManagerGetTableInfoQueryKey = ReturnType<typeof contentManagerGetTableInfoQueryKey>;

export function contentManagerGetTableInfoQueryOptions(
	params: ContentManagerGetTableInfoQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = contentManagerGetTableInfoQueryKey(params);
	return queryOptions<
		ContentManagerGetTableInfoQueryResponse,
		ResponseErrorConfig<Error>,
		ContentManagerGetTableInfoQueryResponse,
		typeof queryKey
	>({
		enabled: !!params,
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return contentManagerGetTableInfo(params, config);
		},
	});
}

/**
 * @description 테이블/컬럼 정보 조회(등록, 수정용) API
 * @summary v1 테이블 정보 조회
 * {@link /v1/content-manager/contents/table-info}
 */
export function useContentManagerGetTableInfo<
	TData = ContentManagerGetTableInfoQueryResponse,
	TQueryData = ContentManagerGetTableInfoQueryResponse,
	TQueryKey extends QueryKey = ContentManagerGetTableInfoQueryKey,
>(
	params: ContentManagerGetTableInfoQueryParams,
	options: {
		query?: Partial<
			QueryObserverOptions<ContentManagerGetTableInfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? contentManagerGetTableInfoQueryKey(params);

	const query = useQuery(
		{...contentManagerGetTableInfoQueryOptions(params, config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
