/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	ContentManagerUpsertMutationRequest,
	ContentManagerUpsertMutationResponse,
	ContentManagerUpsertQueryParams,
} from "../../types/content-manager/content-manager-upsert.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {contentManagerUpsert} from "../../clients/content-manager/content-manager-upsert.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const contentManagerUpsertMutationKey = () => [{url: "/v1/content-manager/contents"}] as const;

export type ContentManagerUpsertMutationKey = ReturnType<typeof contentManagerUpsertMutationKey>;

export function contentManagerUpsertMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<ContentManagerUpsertMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = contentManagerUpsertMutationKey();
	return mutationOptions<
		ContentManagerUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentManagerUpsertQueryParams; data?: ContentManagerUpsertMutationRequest},
		TContext
	>({
		mutationKey,
		mutationFn: async ({params, data}) => {
			return contentManagerUpsert(params, data, config);
		},
	});
}

/**
 * @description 컨텐츠 생성/수정 API (body에 id가 있으면 UPDATE, 없으면 INSERT)
 * @summary v1 컨텐츠 생성/수정
 * {@link /v1/content-manager/contents}
 */
export function useContentManagerUpsert<TContext>(
	options: {
		mutation?: UseMutationOptions<
			ContentManagerUpsertMutationResponse,
			ResponseErrorConfig<Error>,
			{params: ContentManagerUpsertQueryParams; data?: ContentManagerUpsertMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<ContentManagerUpsertMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? contentManagerUpsertMutationKey();

	const baseOptions = contentManagerUpsertMutationOptions(config) as UseMutationOptions<
		ContentManagerUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentManagerUpsertQueryParams; data?: ContentManagerUpsertMutationRequest},
		TContext
	>;

	return useMutation<
		ContentManagerUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentManagerUpsertQueryParams; data?: ContentManagerUpsertMutationRequest},
		TContext
	>({...baseOptions, mutationKey, ...mutationOptions}, queryClient) as UseMutationResult<
		ContentManagerUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentManagerUpsertQueryParams; data?: ContentManagerUpsertMutationRequest},
		TContext
	>;
}
