/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	ContentManagerRemovesMutationResponse,
	ContentManagerRemovesQueryParams,
} from "../../types/content-manager/content-manager-removes.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {contentManagerRemoves} from "../../clients/content-manager/content-manager-removes.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const contentManagerRemovesMutationKey = () => [{url: "/v1/content-manager/contents"}] as const;

export type ContentManagerRemovesMutationKey = ReturnType<typeof contentManagerRemovesMutationKey>;

export function contentManagerRemovesMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = contentManagerRemovesMutationKey();
	return mutationOptions<
		ContentManagerRemovesMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentManagerRemovesQueryParams},
		TContext
	>({
		mutationKey,
		mutationFn: async ({params}) => {
			return contentManagerRemoves(params, config);
		},
	});
}

/**
 * @description 컨텐츠 삭제 API
 * @summary v1 컨텐츠 삭제
 * {@link /v1/content-manager/contents}
 */
export function useContentManagerRemoves<TContext>(
	options: {
		mutation?: UseMutationOptions<
			ContentManagerRemovesMutationResponse,
			ResponseErrorConfig<Error>,
			{params: ContentManagerRemovesQueryParams},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? contentManagerRemovesMutationKey();

	const baseOptions = contentManagerRemovesMutationOptions(config) as UseMutationOptions<
		ContentManagerRemovesMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentManagerRemovesQueryParams},
		TContext
	>;

	return useMutation<
		ContentManagerRemovesMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentManagerRemovesQueryParams},
		TContext
	>({...baseOptions, mutationKey, ...mutationOptions}, queryClient) as UseMutationResult<
		ContentManagerRemovesMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentManagerRemovesQueryParams},
		TContext
	>;
}
