/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	ContentManagerGetItemQueryResponse,
	ContentManagerGetItemPathParams,
	ContentManagerGetItemQueryParams,
} from "../../types/content-manager/content-manager-get-item.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {contentManagerGetItem} from "../../clients/content-manager/content-manager-get-item.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const contentManagerGetItemSuspenseQueryKey = (
	id: ContentManagerGetItemPathParams["id"],
	params: ContentManagerGetItemQueryParams,
) => [{url: "/v1/content-manager/contents/:id", params: {id: id}}, ...(params ? [params] : [])] as const;

export type ContentManagerGetItemSuspenseQueryKey = ReturnType<typeof contentManagerGetItemSuspenseQueryKey>;

export function contentManagerGetItemSuspenseQueryOptions(
	id: ContentManagerGetItemPathParams["id"],
	params: ContentManagerGetItemQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = contentManagerGetItemSuspenseQueryKey(id, params);
	return queryOptions<ContentManagerGetItemQueryResponse, ResponseErrorConfig<Error>, ContentManagerGetItemQueryResponse, typeof queryKey>({
		enabled: !!(id && params),
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return contentManagerGetItem(id, params, config);
		},
	});
}

/**
 * @description 컨텐츠 상세 조회 API
 * @summary v1 컨텐츠 상세 조회
 * {@link /v1/content-manager/contents/:id}
 */
export function useContentManagerGetItemSuspense<
	TData = ContentManagerGetItemQueryResponse,
	TQueryKey extends QueryKey = ContentManagerGetItemSuspenseQueryKey,
>(
	id: ContentManagerGetItemPathParams["id"],
	params: ContentManagerGetItemQueryParams,
	options: {
		query?: Partial<UseSuspenseQueryOptions<ContentManagerGetItemQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? contentManagerGetItemSuspenseQueryKey(id, params);

	const query = useSuspenseQuery(
		{...contentManagerGetItemSuspenseQueryOptions(id, params, config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
