/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {ContentFolderSaveMutationRequest, ContentFolderSaveMutationResponse} from "../../types/content-folder/content-folder-save.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getContentFolderSaveUrl() {
	const res = {method: "PUT", url: `/v1/content-folders` as const};
	return res;
}

/**
 * @description 폴더/테이블 배치 전체를 일괄 저장하는 API
 * @summary v1 컨텐츠 폴더 트리 저장
 * {@link /v1/content-folders}
 */
export async function contentFolderSave(
	data: ContentFolderSaveMutationRequest,
	config: Partial<RequestConfig<ContentFolderSaveMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<ContentFolderSaveMutationResponse, ResponseErrorConfig<Error>, ContentFolderSaveMutationRequest>({
		method: "PUT",
		url: getContentFolderSaveUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
