/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {contentFolderGetList} from "./content-folder-get-list.ts";
import {contentFolderSave} from "./content-folder-save.ts";

export function contentFolder() {
	return {contentFolderGetList, contentFolderSave};
}
