/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {ContentFolderGetListQueryResponse} from "../../types/content-folder/content-folder-get-list.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getContentFolderGetListUrl() {
	const res = {method: "GET", url: `/v1/content-folders` as const};
	return res;
}

/**
 * @description 권한을 반영한 컨텐츠 폴더 트리 조회 API
 * @summary v1 컨텐츠 폴더 트리 조회
 * {@link /v1/content-folders}
 */
export async function contentFolderGetList(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<ContentFolderGetListQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getContentFolderGetListUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
