/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {AdminUpsertMutationRequest, AdminUpsertMutationResponse} from "../../types/admin/admin-upsert.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {adminUpsert} from "../../clients/admin/admin-upsert.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const adminUpsertMutationKey = () => [{url: "/v1/admins"}] as const;

export type AdminUpsertMutationKey = ReturnType<typeof adminUpsertMutationKey>;

export function adminUpsertMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<AdminUpsertMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = adminUpsertMutationKey();
	return mutationOptions<AdminUpsertMutationResponse, ResponseErrorConfig<Error>, {data: AdminUpsertMutationRequest}, TContext>({
		mutationKey,
		mutationFn: async ({data}) => {
			return adminUpsert(data, config);
		},
	});
}

/**
 * @description 관리자 등록/수정 API
 * @summary v1 관리자 등록/수정
 * {@link /v1/admins}
 */
export function useAdminUpsert<TContext>(
	options: {
		mutation?: UseMutationOptions<AdminUpsertMutationResponse, ResponseErrorConfig<Error>, {data: AdminUpsertMutationRequest}, TContext> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig<AdminUpsertMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? adminUpsertMutationKey();

	const baseOptions = adminUpsertMutationOptions(config) as UseMutationOptions<
		AdminUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AdminUpsertMutationRequest},
		TContext
	>;

	return useMutation<AdminUpsertMutationResponse, ResponseErrorConfig<Error>, {data: AdminUpsertMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<AdminUpsertMutationResponse, ResponseErrorConfig<Error>, {data: AdminUpsertMutationRequest}, TContext>;
}
