/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AdminIsLoginIdDuplicateQueryResponse,
	AdminIsLoginIdDuplicateQueryParams,
} from "../../types/admin/admin-is-login-id-duplicate.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {adminIsLoginIdDuplicate} from "../../clients/admin/admin-is-login-id-duplicate.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const adminIsLoginIdDuplicateSuspenseQueryKey = (params: AdminIsLoginIdDuplicateQueryParams) =>
	[{url: "/v1/admins/is-duplicate-login-id"}, ...(params ? [params] : [])] as const;

export type AdminIsLoginIdDuplicateSuspenseQueryKey = ReturnType<typeof adminIsLoginIdDuplicateSuspenseQueryKey>;

export function adminIsLoginIdDuplicateSuspenseQueryOptions(
	params: AdminIsLoginIdDuplicateQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = adminIsLoginIdDuplicateSuspenseQueryKey(params);
	return queryOptions<
		AdminIsLoginIdDuplicateQueryResponse,
		ResponseErrorConfig<Error>,
		AdminIsLoginIdDuplicateQueryResponse,
		typeof queryKey
	>({
		enabled: !!params,
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return adminIsLoginIdDuplicate(params, config);
		},
	});
}

/**
 * @description 관리자 로그인 아이디 중복 확인 API
 * @summary v1 관리자 로그인 아이디 중복 확인
 * {@link /v1/admins/is-duplicate-login-id}
 */
export function useAdminIsLoginIdDuplicateSuspense<
	TData = AdminIsLoginIdDuplicateQueryResponse,
	TQueryKey extends QueryKey = AdminIsLoginIdDuplicateSuspenseQueryKey,
>(
	params: AdminIsLoginIdDuplicateQueryParams,
	options: {
		query?: Partial<UseSuspenseQueryOptions<AdminIsLoginIdDuplicateQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? adminIsLoginIdDuplicateSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{...adminIsLoginIdDuplicateSuspenseQueryOptions(params, config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
