/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {AdminGetItemQueryResponse, AdminGetItemPathParams} from "../../types/admin/admin-get-item.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {adminGetItem} from "../../clients/admin/admin-get-item.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const adminGetItemSuspenseQueryKey = (id: AdminGetItemPathParams["id"]) => [{url: "/v1/admins/:id", params: {id: id}}] as const;

export type AdminGetItemSuspenseQueryKey = ReturnType<typeof adminGetItemSuspenseQueryKey>;

export function adminGetItemSuspenseQueryOptions(
	id: AdminGetItemPathParams["id"],
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = adminGetItemSuspenseQueryKey(id);
	return queryOptions<AdminGetItemQueryResponse, ResponseErrorConfig<Error>, AdminGetItemQueryResponse, typeof queryKey>({
		enabled: !!id,
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return adminGetItem(id, config);
		},
	});
}

/**
 * @description 관리자 상세 조회 API
 * @summary v1 관리자 상세 조회
 * {@link /v1/admins/:id}
 */
export function useAdminGetItemSuspense<TData = AdminGetItemQueryResponse, TQueryKey extends QueryKey = AdminGetItemSuspenseQueryKey>(
	id: AdminGetItemPathParams["id"],
	options: {
		query?: Partial<UseSuspenseQueryOptions<AdminGetItemQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? adminGetItemSuspenseQueryKey(id);

	const query = useSuspenseQuery(
		{...adminGetItemSuspenseQueryOptions(id, config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
