/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {AdminUpdatesMutationRequest, AdminUpdatesMutationResponse} from "../../types/admin/admin-updates.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {adminUpdates} from "../../clients/admin/admin-updates.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const adminUpdatesMutationKey = () => [{url: "/v1/admins/modify/permission-groups"}] as const;

export type AdminUpdatesMutationKey = ReturnType<typeof adminUpdatesMutationKey>;

export function adminUpdatesMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<AdminUpdatesMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = adminUpdatesMutationKey();
	return mutationOptions<AdminUpdatesMutationResponse, ResponseErrorConfig<Error>, {data: AdminUpdatesMutationRequest}, TContext>({
		mutationKey,
		mutationFn: async ({data}) => {
			return adminUpdates(data, config);
		},
	});
}

/**
 * @description 관리자 권한 그룹 일괄 수정 API
 * @summary v1 관리자 권한 그룹 일괄 수정
 * {@link /v1/admins/modify/permission-groups}
 */
export function useAdminUpdates<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AdminUpdatesMutationResponse,
			ResponseErrorConfig<Error>,
			{data: AdminUpdatesMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<AdminUpdatesMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? adminUpdatesMutationKey();

	const baseOptions = adminUpdatesMutationOptions(config) as UseMutationOptions<
		AdminUpdatesMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AdminUpdatesMutationRequest},
		TContext
	>;

	return useMutation<AdminUpdatesMutationResponse, ResponseErrorConfig<Error>, {data: AdminUpdatesMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<AdminUpdatesMutationResponse, ResponseErrorConfig<Error>, {data: AdminUpdatesMutationRequest}, TContext>;
}
