/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {AdminSearchAdminsQueryResponse, AdminSearchAdminsQueryParams} from "../../types/admin/admin-search-admins.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {adminSearchAdmins} from "../../clients/admin/admin-search-admins.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const adminSearchAdminsSuspenseQueryKey = (params: AdminSearchAdminsQueryParams = {}) =>
	[{url: "/v1/admins"}, ...(params ? [params] : [])] as const;

export type AdminSearchAdminsSuspenseQueryKey = ReturnType<typeof adminSearchAdminsSuspenseQueryKey>;

export function adminSearchAdminsSuspenseQueryOptions(
	params?: AdminSearchAdminsQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = adminSearchAdminsSuspenseQueryKey(params);
	return queryOptions<AdminSearchAdminsQueryResponse, ResponseErrorConfig<Error>, AdminSearchAdminsQueryResponse, typeof queryKey>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return adminSearchAdmins(params, config);
		},
	});
}

/**
 * @description 관리자 목록 조회 API
 * @summary v1 관리자 목록 조회
 * {@link /v1/admins}
 */
export function useAdminSearchAdminsSuspense<
	TData = AdminSearchAdminsQueryResponse,
	TQueryKey extends QueryKey = AdminSearchAdminsSuspenseQueryKey,
>(
	params?: AdminSearchAdminsQueryParams,
	options: {
		query?: Partial<UseSuspenseQueryOptions<AdminSearchAdminsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? adminSearchAdminsSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{...adminSearchAdminsSuspenseQueryOptions(params, config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
