/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {AdminRemoveAdminsMutationResponse, AdminRemoveAdminsQueryParams} from "../../types/admin/admin-remove-admins.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {adminRemoveAdmins} from "../../clients/admin/admin-remove-admins.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const adminRemoveAdminsMutationKey = () => [{url: "/v1/admins"}] as const;

export type AdminRemoveAdminsMutationKey = ReturnType<typeof adminRemoveAdminsMutationKey>;

export function adminRemoveAdminsMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = adminRemoveAdminsMutationKey();
	return mutationOptions<AdminRemoveAdminsMutationResponse, ResponseErrorConfig<Error>, {params: AdminRemoveAdminsQueryParams}, TContext>({
		mutationKey,
		mutationFn: async ({params}) => {
			return adminRemoveAdmins(params, config);
		},
	});
}

/**
 * @description 관리자 삭제 API
 * @summary v1 관리자 삭제
 * {@link /v1/admins}
 */
export function useAdminRemoveAdmins<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AdminRemoveAdminsMutationResponse,
			ResponseErrorConfig<Error>,
			{params: AdminRemoveAdminsQueryParams},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? adminRemoveAdminsMutationKey();

	const baseOptions = adminRemoveAdminsMutationOptions(config) as UseMutationOptions<
		AdminRemoveAdminsMutationResponse,
		ResponseErrorConfig<Error>,
		{params: AdminRemoveAdminsQueryParams},
		TContext
	>;

	return useMutation<AdminRemoveAdminsMutationResponse, ResponseErrorConfig<Error>, {params: AdminRemoveAdminsQueryParams}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<AdminRemoveAdminsMutationResponse, ResponseErrorConfig<Error>, {params: AdminRemoveAdminsQueryParams}, TContext>;
}
