/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {AdminUnlockAdminsMutationRequest, AdminUnlockAdminsMutationResponse} from "../../types/admin/admin-unlock-admins.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {adminUnlockAdmins} from "../../clients/admin/admin-unlock-admins.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const adminUnlockAdminsMutationKey = () => [{url: "/v1/admins/unlock"}] as const;

export type AdminUnlockAdminsMutationKey = ReturnType<typeof adminUnlockAdminsMutationKey>;

export function adminUnlockAdminsMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<AdminUnlockAdminsMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = adminUnlockAdminsMutationKey();
	return mutationOptions<AdminUnlockAdminsMutationResponse, ResponseErrorConfig<Error>, {data: AdminUnlockAdminsMutationRequest}, TContext>(
		{
			mutationKey,
			mutationFn: async ({data}) => {
				return adminUnlockAdmins(data, config);
			},
		},
	);
}

/**
 * @description 관리자 잠금 해제 API
 * @summary v1 관리자 잠금 해제
 * {@link /v1/admins/unlock}
 */
export function useAdminUnlockAdmins<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AdminUnlockAdminsMutationResponse,
			ResponseErrorConfig<Error>,
			{data: AdminUnlockAdminsMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<AdminUnlockAdminsMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? adminUnlockAdminsMutationKey();

	const baseOptions = adminUnlockAdminsMutationOptions(config) as UseMutationOptions<
		AdminUnlockAdminsMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AdminUnlockAdminsMutationRequest},
		TContext
	>;

	return useMutation<AdminUnlockAdminsMutationResponse, ResponseErrorConfig<Error>, {data: AdminUnlockAdminsMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<AdminUnlockAdminsMutationResponse, ResponseErrorConfig<Error>, {data: AdminUnlockAdminsMutationRequest}, TContext>;
}
