/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AdminUpsert200, AdminUpsertMutationRequest, AdminUpsertMutationResponse} from "../../types/admin/admin-upsert.ts";
import {createAdminSaveRequest} from "../create-admin-save-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createAdminUpsert200(data?: Partial<AdminUpsert200>): AdminUpsert200 {
	return createUnitResult(data);
}

export function createAdminUpsertMutationRequest(data?: Partial<AdminUpsertMutationRequest>): AdminUpsertMutationRequest {
	return createAdminSaveRequest(data);
}

export function createAdminUpsertMutationResponse(data?: Partial<AdminUpsertMutationResponse>): AdminUpsertMutationResponse {
	return data || faker.helpers.arrayElement<any>([createAdminUpsert200()]);
}
