/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AdminGetItemPathParams, AdminGetItem200, AdminGetItemQueryResponse} from "../../types/admin/admin-get-item.ts";
import {createApiResultAdminDetailResponse} from "../create-api-result-admin-detail-response.ts";
import {faker} from "@faker-js/faker";

export function createAdminGetItemPathParams(data?: Partial<AdminGetItemPathParams>): AdminGetItemPathParams {
	return {...{id: faker.number.int()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createAdminGetItem200(data?: Partial<AdminGetItem200>): AdminGetItem200 {
	return createApiResultAdminDetailResponse(data);
}

export function createAdminGetItemQueryResponse(data?: Partial<AdminGetItemQueryResponse>): AdminGetItemQueryResponse {
	return data || faker.helpers.arrayElement<any>([createAdminGetItem200()]);
}
