/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AdminRemoveAdminsQueryParams,
	AdminRemoveAdmins200,
	AdminRemoveAdminsMutationResponse,
} from "../../types/admin/admin-remove-admins.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createAdminRemoveAdminsQueryParams(data?: Partial<AdminRemoveAdminsQueryParams>): AdminRemoveAdminsQueryParams {
	return {...{ids: faker.helpers.multiple(() => faker.number.int())}, ...(data || {})};
}

/**
 * @description OK
 */
export function createAdminRemoveAdmins200(data?: Partial<AdminRemoveAdmins200>): AdminRemoveAdmins200 {
	return createUnitResult(data);
}

export function createAdminRemoveAdminsMutationResponse(
	data?: Partial<AdminRemoveAdminsMutationResponse>,
): AdminRemoveAdminsMutationResponse {
	return data || faker.helpers.arrayElement<any>([createAdminRemoveAdmins200()]);
}
