/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AdminIsLoginIdDuplicateQueryParams,
	AdminIsLoginIdDuplicate200,
	AdminIsLoginIdDuplicateQueryResponse,
} from "../../types/admin/admin-is-login-id-duplicate.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createAdminIsLoginIdDuplicateQueryParams(
	data?: Partial<AdminIsLoginIdDuplicateQueryParams>,
): AdminIsLoginIdDuplicateQueryParams {
	return {...{loginId: faker.string.alpha()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createAdminIsLoginIdDuplicate200(data?: Partial<AdminIsLoginIdDuplicate200>): AdminIsLoginIdDuplicate200 {
	return createUnitResult(data);
}

export function createAdminIsLoginIdDuplicateQueryResponse(
	data?: Partial<AdminIsLoginIdDuplicateQueryResponse>,
): AdminIsLoginIdDuplicateQueryResponse {
	return data || faker.helpers.arrayElement<any>([createAdminIsLoginIdDuplicate200()]);
}
