/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AdminUpdates200, AdminUpdatesMutationRequest, AdminUpdatesMutationResponse} from "../../types/admin/admin-updates.ts";
import {createAdminPermissionGroupBulkUpdateRequest} from "../create-admin-permission-group-bulk-update-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createAdminUpdates200(data?: Partial<AdminUpdates200>): AdminUpdates200 {
	return createUnitResult(data);
}

export function createAdminUpdatesMutationRequest(data?: Partial<AdminUpdatesMutationRequest>): AdminUpdatesMutationRequest {
	return createAdminPermissionGroupBulkUpdateRequest(data);
}

export function createAdminUpdatesMutationResponse(data?: Partial<AdminUpdatesMutationResponse>): AdminUpdatesMutationResponse {
	return data || faker.helpers.arrayElement<any>([createAdminUpdates200()]);
}
