/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AdminSearchAdminsQueryParams,
	AdminSearchAdmins200,
	AdminSearchAdminsQueryResponse,
} from "../../types/admin/admin-search-admins.ts";
import {createApiResultOnePageAdminSummaryResponse} from "../create-api-result-one-page-admin-summary-response.ts";
import {faker} from "@faker-js/faker";

export function createAdminSearchAdminsQueryParams(data?: Partial<AdminSearchAdminsQueryParams>): AdminSearchAdminsQueryParams {
	return {
		...{
			permissionGroupId: faker.number.int(),
			removed: faker.datatype.boolean(),
			lockedStartAt: faker.date.anytime().toISOString().substring(0, 10),
			lockedEndAt: faker.date.anytime().toISOString().substring(0, 10),
			searchOption: faker.helpers.arrayElement<NonNullable<AdminSearchAdminsQueryParams>["searchOption"]>(["LOGIN_ID", "NAME"]),
			searchKeyword: faker.string.alpha(),
			field: faker.helpers.multiple(() => faker.string.alpha()),
			operator: faker.helpers.multiple(() => faker.string.alpha()),
			value: faker.helpers.multiple(() => faker.string.alpha()),
			page: faker.number.int(),
			size: faker.number.int(),
		},
		...(data || {}),
	};
}

/**
 * @description OK
 */
export function createAdminSearchAdmins200(data?: Partial<AdminSearchAdmins200>): AdminSearchAdmins200 {
	return createApiResultOnePageAdminSummaryResponse(data);
}

export function createAdminSearchAdminsQueryResponse(data?: Partial<AdminSearchAdminsQueryResponse>): AdminSearchAdminsQueryResponse {
	return data || faker.helpers.arrayElement<any>([createAdminSearchAdmins200()]);
}
