/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AdminUnlockAdmins200,
	AdminUnlockAdminsMutationRequest,
	AdminUnlockAdminsMutationResponse,
} from "../../types/admin/admin-unlock-admins.ts";
import {createAdminUnlockRequest} from "../create-admin-unlock-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createAdminUnlockAdmins200(data?: Partial<AdminUnlockAdmins200>): AdminUnlockAdmins200 {
	return createUnitResult(data);
}

export function createAdminUnlockAdminsMutationRequest(data?: Partial<AdminUnlockAdminsMutationRequest>): AdminUnlockAdminsMutationRequest {
	return createAdminUnlockRequest(data);
}

export function createAdminUnlockAdminsMutationResponse(
	data?: Partial<AdminUnlockAdminsMutationResponse>,
): AdminUnlockAdminsMutationResponse {
	return data || faker.helpers.arrayElement<any>([createAdminUnlockAdmins200()]);
}
