/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOneListBoardPageResponse} from "../api-result-one-list-board-page-response.ts";

/**
 * @description OK
 */
export type HomeDashboardGetBuildNotes200 = ApiResultOneListBoardPageResponse;

export type HomeDashboardGetBuildNotesQueryResponse = HomeDashboardGetBuildNotes200;

export type HomeDashboardGetBuildNotesQuery = {Response: HomeDashboardGetBuildNotes200; Errors: any};
