/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOneListUserActivityResponse} from "../api-result-one-list-user-activity-response.ts";

/**
 * @description OK
 */
export type HomeDashboardGetUserActivities200 = ApiResultOneListUserActivityResponse;

export type HomeDashboardGetUserActivitiesQueryResponse = HomeDashboardGetUserActivities200;

export type HomeDashboardGetUserActivitiesQuery = {Response: HomeDashboardGetUserActivities200; Errors: any};
