/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {mediaLibraryRemove} from "./media-library-remove.ts";
import {mediaLibrarySearchMediaLibrary} from "./media-library-search-media-library.ts";
import {mediaLibraryUpsert} from "./media-library-upsert.ts";

export function mediaLibrary() {
	return {mediaLibrarySearchMediaLibrary, mediaLibraryUpsert, mediaLibraryRemove};
}
