/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	MediaLibrarySearchMediaLibraryQueryResponse,
	MediaLibrarySearchMediaLibraryQueryParams,
} from "../../types/media-library/media-library-search-media-library.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getMediaLibrarySearchMediaLibraryUrl() {
	const res = {method: "GET", url: `/v1/media-library` as const};
	return res;
}

/**
 * @description 미디어 라이브러리 목록 조회 API
 * @summary v1 미디어 라이브러리 목록 조회
 * {@link /v1/media-library}
 */
export async function mediaLibrarySearchMediaLibrary(
	params?: MediaLibrarySearchMediaLibraryQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<MediaLibrarySearchMediaLibraryQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getMediaLibrarySearchMediaLibraryUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
