/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {MediaLibraryRemoveMutationResponse, MediaLibraryRemovePathParams} from "../../types/media-library/media-library-remove.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getMediaLibraryRemoveUrl(id: MediaLibraryRemovePathParams["id"]) {
	const res = {method: "DELETE", url: `/v1/media-library/${id}` as const};
	return res;
}

/**
 * @description 미디어 라이브러리 단건 삭제 API
 * @summary v1 미디어 라이브러리 삭제
 * {@link /v1/media-library/:id}
 */
export async function mediaLibraryRemove(id: MediaLibraryRemovePathParams["id"], config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<MediaLibraryRemoveMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "DELETE",
		url: getMediaLibraryRemoveUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
