/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	MediaLibraryUpsertMutationRequest,
	MediaLibraryUpsertMutationResponse,
} from "../../types/media-library/media-library-upsert.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getMediaLibraryUpsertUrl() {
	const res = {method: "POST", url: `/v1/media-library` as const};
	return res;
}

/**
 * @description 미디어 라이브러리 생성/수정 API
 * @summary v1 미디어 라이브러리 생성/수정
 * {@link /v1/media-library}
 */
export async function mediaLibraryUpsert(
	data: MediaLibraryUpsertMutationRequest,
	config: Partial<RequestConfig<MediaLibraryUpsertMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<MediaLibraryUpsertMutationResponse, ResponseErrorConfig<Error>, MediaLibraryUpsertMutationRequest>({
		method: "POST",
		url: getMediaLibraryUpsertUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
