/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {BoardUpsertMutationRequest, BoardUpsertMutationResponse} from "../../types/board/board-upsert.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getBoardUpsertUrl() {
	const res = {method: "POST", url: `/v1/boards` as const};
	return res;
}

/**
 * @description 게시글 등록/수정 API
 * @summary v1 게시글 등록/수정
 * {@link /v1/boards}
 */
export async function boardUpsert(
	data: BoardUpsertMutationRequest,
	config: Partial<RequestConfig<BoardUpsertMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<BoardUpsertMutationResponse, ResponseErrorConfig<Error>, BoardUpsertMutationRequest>({
		method: "POST",
		url: getBoardUpsertUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
