/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {BoardSearchBoardsQueryResponse, BoardSearchBoardsQueryParams} from "../../types/board/board-search-boards.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getBoardSearchBoardsUrl() {
	const res = {method: "GET", url: `/v1/boards` as const};
	return res;
}

/**
 * @description removed=false 게시글 목록을 id desc 정렬로 페이징 조회 API
 * @summary v1 게시글 목록 조회
 * {@link /v1/boards}
 */
export async function boardSearchBoards(params?: BoardSearchBoardsQueryParams, config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<BoardSearchBoardsQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getBoardSearchBoardsUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
