/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {BoardRemoveMutationResponse, BoardRemovePathParams} from "../../types/board/board-remove.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getBoardRemoveUrl(id: BoardRemovePathParams["id"]) {
	const res = {method: "DELETE", url: `/v1/boards/${id}` as const};
	return res;
}

/**
 * @description 게시글 삭제 API(soft delete)
 * @summary v1 게시글 삭제
 * {@link /v1/boards/:id}
 */
export async function boardRemove(id: BoardRemovePathParams["id"], config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<BoardRemoveMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "DELETE",
		url: getBoardRemoveUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
