/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {boardRemove} from "./board-remove.ts";
import {boardSearchBoards} from "./board-search-boards.ts";
import {boardUpsert} from "./board-upsert.ts";

export function board() {
	return {boardSearchBoards, boardUpsert, boardRemove};
}
