/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultListCreateMediaPresignedUrlResponse} from "../api-result-list-create-media-presigned-url-response.ts";
import type {CreateMediaPresignedUrlItemRequest} from "../create-media-presigned-url-item-request.ts";

export type ContentMediaCreatePresignedUrlsQueryParams = {
	/**
	 * @type string
	 */
	tableName: string;
};

/**
 * @description OK
 */
export type ContentMediaCreatePresignedUrls200 = ApiResultListCreateMediaPresignedUrlResponse;

export type ContentMediaCreatePresignedUrlsMutationRequest = CreateMediaPresignedUrlItemRequest[];

export type ContentMediaCreatePresignedUrlsMutationResponse = ContentMediaCreatePresignedUrls200;

export type ContentMediaCreatePresignedUrlsMutation = {
	Response: ContentMediaCreatePresignedUrls200;
	Request: ContentMediaCreatePresignedUrlsMutationRequest;
	QueryParams: ContentMediaCreatePresignedUrlsQueryParams;
	Errors: any;
};
