/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ConfigValueGetEnumList200, ConfigValueGetEnumListQueryResponse} from "../../types/config-value/config-value-get-enum-list.ts";
import {createApiResultListConfigValueResponse} from "../create-api-result-list-config-value-response.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createConfigValueGetEnumList200(data?: Partial<ConfigValueGetEnumList200>): ConfigValueGetEnumList200 {
	return createApiResultListConfigValueResponse(data);
}

export function createConfigValueGetEnumListQueryResponse(
	data?: Partial<ConfigValueGetEnumListQueryResponse>,
): ConfigValueGetEnumListQueryResponse {
	return data || faker.helpers.arrayElement<any>([createConfigValueGetEnumList200()]);
}
