/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ConfigValueGetItemQueryParams,
	ConfigValueGetItem200,
	ConfigValueGetItemQueryResponse,
} from "../../types/config-value/config-value-get-item.ts";
import {createApiResultConfigValueResponse} from "../create-api-result-config-value-response.ts";
import {faker} from "@faker-js/faker";

export function createConfigValueGetItemQueryParams(data?: Partial<ConfigValueGetItemQueryParams>): ConfigValueGetItemQueryParams {
	return {...{config: faker.string.alpha()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createConfigValueGetItem200(data?: Partial<ConfigValueGetItem200>): ConfigValueGetItem200 {
	return createApiResultConfigValueResponse(data);
}

export function createConfigValueGetItemQueryResponse(data?: Partial<ConfigValueGetItemQueryResponse>): ConfigValueGetItemQueryResponse {
	return data || faker.helpers.arrayElement<any>([createConfigValueGetItem200()]);
}
