/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ConfigValueUpsert200,
	ConfigValueUpsertMutationRequest,
	ConfigValueUpsertMutationResponse,
} from "../../types/config-value/config-value-upsert.ts";
import {createConfigValueRequest} from "../create-config-value-request.ts";
import {createConfigValueResponse} from "../create-config-value-response.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createConfigValueUpsert200(data?: Partial<ConfigValueUpsert200>): ConfigValueUpsert200 {
	return createConfigValueResponse(data);
}

export function createConfigValueUpsertMutationRequest(data?: Partial<ConfigValueUpsertMutationRequest>): ConfigValueUpsertMutationRequest {
	return createConfigValueRequest(data);
}

export function createConfigValueUpsertMutationResponse(
	data?: Partial<ConfigValueUpsertMutationResponse>,
): ConfigValueUpsertMutationResponse {
	return data || faker.helpers.arrayElement<any>([createConfigValueUpsert200()]);
}
