/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AuditLogSearchAuditLogsQueryParams,
	AuditLogSearchAuditLogs200,
	AuditLogSearchAuditLogsQueryResponse,
} from "../../types/audit-log/audit-log-search-audit-logs.ts";
import {createApiResultOnePageAuditLogPageResponse} from "../create-api-result-one-page-audit-log-page-response.ts";
import {faker} from "@faker-js/faker";

export function createAuditLogSearchAuditLogsQueryParams(
	data?: Partial<AuditLogSearchAuditLogsQueryParams>,
): AuditLogSearchAuditLogsQueryParams {
	return {
		...{
			adminId: faker.string.alpha(),
			timestampFrom: faker.string.alpha(),
			timestampTo: faker.string.alpha(),
			field: faker.helpers.multiple(() => faker.string.alpha()),
			operator: faker.helpers.multiple(() => faker.string.alpha()),
			value: faker.helpers.multiple(() => faker.string.alpha()),
			page: faker.number.int(),
			size: faker.number.int(),
		},
		...(data || {}),
	};
}

/**
 * @description OK
 */
export function createAuditLogSearchAuditLogs200(data?: Partial<AuditLogSearchAuditLogs200>): AuditLogSearchAuditLogs200 {
	return createApiResultOnePageAuditLogPageResponse(data);
}

export function createAuditLogSearchAuditLogsQueryResponse(
	data?: Partial<AuditLogSearchAuditLogsQueryResponse>,
): AuditLogSearchAuditLogsQueryResponse {
	return data || faker.helpers.arrayElement<any>([createAuditLogSearchAuditLogs200()]);
}
