/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {contentMediaCreatePresignedUrls} from "./content-media-create-presigned-urls.ts";

export function contentMedia() {
	return {contentMediaCreatePresignedUrls};
}
