/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	ContentMediaCreatePresignedUrlsMutationRequest,
	ContentMediaCreatePresignedUrlsMutationResponse,
	ContentMediaCreatePresignedUrlsQueryParams,
} from "../../types/content-media/content-media-create-presigned-urls.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getContentMediaCreatePresignedUrlsUrl() {
	const res = {method: "POST", url: `/v1/content-media/aws/presigned-url` as const};
	return res;
}

/**
 * @description MEDIA 파일 다중 업로드용 AWS Presigned URL 발급 API
 * @summary v1 MEDIA Presigned URL 발급
 * {@link /v1/content-media/aws/presigned-url}
 */
export async function contentMediaCreatePresignedUrls(
	params: ContentMediaCreatePresignedUrlsQueryParams,
	data?: ContentMediaCreatePresignedUrlsMutationRequest,
	config: Partial<RequestConfig<ContentMediaCreatePresignedUrlsMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<
		ContentMediaCreatePresignedUrlsMutationResponse,
		ResponseErrorConfig<Error>,
		ContentMediaCreatePresignedUrlsMutationRequest
	>({method: "POST", url: getContentMediaCreatePresignedUrlsUrl().url.toString(), params, data: requestData, ...requestConfig});
	return res.data;
}
