/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {IndexRootQueryResponse} from "../../types/index-controller/index-root.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getIndexRootUrl() {
	const res = {method: "GET", url: `/` as const};
	return res;
}

/**
 * @description MAIN
 * @summary ROOT
 * {@link /}
 */
export async function indexRoot(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<IndexRootQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getIndexRootUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
