/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

export const operations = {
	contentFolderGetList: {path: "/v1/content-folders", method: "get"},
	contentFolderSave: {path: "/v1/content-folders", method: "put"},
	tenantSearchTenants: {path: "/v1/tenants", method: "get"},
	tenantUpsert: {path: "/v1/tenants", method: "post"},
	mediaLibrarySearchMediaLibrary: {path: "/v1/media-library", method: "get"},
	mediaLibraryUpsert: {path: "/v1/media-library", method: "post"},
	filterSearchFilters: {path: "/v1/filters", method: "get"},
	filterUpsert: {path: "/v1/filters", method: "post"},
	contentMediaCreatePresignedUrls: {path: "/v1/content-media/aws/presigned-url", method: "post"},
	contentManagerSearchContents: {path: "/v1/content-manager/contents", method: "get"},
	contentManagerUpsert: {path: "/v1/content-manager/contents", method: "post"},
	contentManagerRemoves: {path: "/v1/content-manager/contents", method: "delete"},
	configValueGetItem: {path: "/v1/config-value", method: "get"},
	configValueUpsert: {path: "/v1/config-value", method: "post"},
	authorizationVerifyOtp: {path: "/v1/cms/auth/verify-otp", method: "post"},
	authorizationLoginGoogle: {path: "/v1/cms/auth/social-login", method: "post"},
	authorizationRefreshToken: {path: "/v1/cms/auth/refresh", method: "post"},
	authorizationLogout: {path: "/v1/cms/auth/logout", method: "post"},
	authorizationLogin: {path: "/v1/cms/auth/login", method: "post"},
	cacheFlushAllRedisCache: {path: "/v1/cache/flush-all", method: "post"},
	boardSearchBoards: {path: "/v1/boards", method: "get"},
	boardUpsert: {path: "/v1/boards", method: "post"},
	adminSearchAdmins: {path: "/v1/admins", method: "get"},
	adminUpsert: {path: "/v1/admins", method: "post"},
	adminRemoveAdmins: {path: "/v1/admins", method: "delete"},
	adminUnlockAdmins: {path: "/v1/admins/unlock", method: "post"},
	permissionGroupGetList: {path: "/v1/admins/permission-groups", method: "get"},
	permissionGroupUpsert: {path: "/v1/admins/permission-groups", method: "post"},
	adminUpdates: {path: "/v1/admins/modify/permission-groups", method: "post"},
	homeDashboardGetUserActivities: {path: "/v1/home-dashboard/user-activity", method: "get"},
	homeDashboardGetNotices: {path: "/v1/home-dashboard/notices", method: "get"},
	homeDashboardGetBuildNotes: {path: "/v1/home-dashboard/build-notes", method: "get"},
	environmentGetAuthPlatform: {path: "/v1/environments/auth-platform", method: "get"},
	contentTypeGetTableList: {path: "/v1/content-type/tables", method: "get"},
	contentManagerGetItem: {path: "/v1/content-manager/contents/:id", method: "get"},
	contentManagerGetTableInfo: {path: "/v1/content-manager/contents/table-info", method: "get"},
	configValueGetEnumList: {path: "/v1/config-value/enum", method: "get"},
	authorizationInfo: {path: "/v1/cms/auth/info", method: "get"},
	auditLogSearchAuditLogs: {path: "/v1/audit-logs", method: "get"},
	adminGetItem: {path: "/v1/admins/:id", method: "get"},
	permissionGroupGetItem: {path: "/v1/admins/permission-groups/:permissionGroupId", method: "get"},
	permissionGroupRemove: {path: "/v1/admins/permission-groups/:permissionGroupId", method: "delete"},
	permissionGroupGetApiEndpointList: {path: "/v1/admins/permission-groups/api-endpoints", method: "get"},
	adminIsLoginIdDuplicate: {path: "/v1/admins/is-duplicate-login-id", method: "get"},
	indexRoot: {path: "/", method: "get"},
	tenantRemove: {path: "/v1/tenants/:id", method: "delete"},
	mediaLibraryRemove: {path: "/v1/media-library/:id", method: "delete"},
	filterRemove: {path: "/v1/filters/:id", method: "delete"},
	boardRemove: {path: "/v1/boards/:id", method: "delete"},
};
