/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	PermissionGroupGetApiEndpointList200,
	PermissionGroupGetApiEndpointListQueryResponse,
} from "../../types/permission-group/permission-group-get-api-endpoint-list.ts";
import {createApiResultOneListApiEndpointResponse} from "../create-api-result-one-list-api-endpoint-response.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createPermissionGroupGetApiEndpointList200(
	data?: Partial<PermissionGroupGetApiEndpointList200>,
): PermissionGroupGetApiEndpointList200 {
	return createApiResultOneListApiEndpointResponse(data);
}

export function createPermissionGroupGetApiEndpointListQueryResponse(
	data?: Partial<PermissionGroupGetApiEndpointListQueryResponse>,
): PermissionGroupGetApiEndpointListQueryResponse {
	return data || faker.helpers.arrayElement<any>([createPermissionGroupGetApiEndpointList200()]);
}
