/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	PermissionGroupRemovePathParams,
	PermissionGroupRemove200,
	PermissionGroupRemoveMutationResponse,
} from "../../types/permission-group/permission-group-remove.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createPermissionGroupRemovePathParams(data?: Partial<PermissionGroupRemovePathParams>): PermissionGroupRemovePathParams {
	return {...{permissionGroupId: faker.number.int()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createPermissionGroupRemove200(data?: Partial<PermissionGroupRemove200>): PermissionGroupRemove200 {
	return createUnitResult(data);
}

export function createPermissionGroupRemoveMutationResponse(
	data?: Partial<PermissionGroupRemoveMutationResponse>,
): PermissionGroupRemoveMutationResponse {
	return data || faker.helpers.arrayElement<any>([createPermissionGroupRemove200()]);
}
