/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	PermissionGroupGetList200,
	PermissionGroupGetListQueryResponse,
} from "../../types/permission-group/permission-group-get-list.ts";
import {createApiResultOneListPermissionGroupResponse} from "../create-api-result-one-list-permission-group-response.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createPermissionGroupGetList200(data?: Partial<PermissionGroupGetList200>): PermissionGroupGetList200 {
	return createApiResultOneListPermissionGroupResponse(data);
}

export function createPermissionGroupGetListQueryResponse(
	data?: Partial<PermissionGroupGetListQueryResponse>,
): PermissionGroupGetListQueryResponse {
	return data || faker.helpers.arrayElement<any>([createPermissionGroupGetList200()]);
}
