/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	PermissionGroupGetItemPathParams,
	PermissionGroupGetItem200,
	PermissionGroupGetItemQueryResponse,
} from "../../types/permission-group/permission-group-get-item.ts";
import {createApiResultPermissionGroupApiEndPointResponse} from "../create-api-result-permission-group-api-end-point-response.ts";
import {faker} from "@faker-js/faker";

export function createPermissionGroupGetItemPathParams(data?: Partial<PermissionGroupGetItemPathParams>): PermissionGroupGetItemPathParams {
	return {...{permissionGroupId: faker.number.int()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createPermissionGroupGetItem200(data?: Partial<PermissionGroupGetItem200>): PermissionGroupGetItem200 {
	return createApiResultPermissionGroupApiEndPointResponse(data);
}

export function createPermissionGroupGetItemQueryResponse(
	data?: Partial<PermissionGroupGetItemQueryResponse>,
): PermissionGroupGetItemQueryResponse {
	return data || faker.helpers.arrayElement<any>([createPermissionGroupGetItem200()]);
}
