/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	PermissionGroupUpsert200,
	PermissionGroupUpsertMutationRequest,
	PermissionGroupUpsertMutationResponse,
} from "../../types/permission-group/permission-group-upsert.ts";
import {createPermissionGroupApiEndpointSaveRequest} from "../create-permission-group-api-endpoint-save-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createPermissionGroupUpsert200(data?: Partial<PermissionGroupUpsert200>): PermissionGroupUpsert200 {
	return createUnitResult(data);
}

export function createPermissionGroupUpsertMutationRequest(
	data?: Partial<PermissionGroupUpsertMutationRequest>,
): PermissionGroupUpsertMutationRequest {
	return createPermissionGroupApiEndpointSaveRequest(data);
}

export function createPermissionGroupUpsertMutationResponse(
	data?: Partial<PermissionGroupUpsertMutationResponse>,
): PermissionGroupUpsertMutationResponse {
	return data || faker.helpers.arrayElement<any>([createPermissionGroupUpsert200()]);
}
