/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	ContentTypeGetTableListQueryResponse,
	ContentTypeGetTableListQueryParams,
} from "../../types/content-type/content-type-get-table-list.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {contentTypeGetTableList} from "../../clients/content-type/content-type-get-table-list.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const contentTypeGetTableListSuspenseQueryKey = (params: ContentTypeGetTableListQueryParams = {}) =>
	[{url: "/v1/content-type/tables"}, ...(params ? [params] : [])] as const;

export type ContentTypeGetTableListSuspenseQueryKey = ReturnType<typeof contentTypeGetTableListSuspenseQueryKey>;

export function contentTypeGetTableListSuspenseQueryOptions(
	params?: ContentTypeGetTableListQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = contentTypeGetTableListSuspenseQueryKey(params);
	return queryOptions<
		ContentTypeGetTableListQueryResponse,
		ResponseErrorConfig<Error>,
		ContentTypeGetTableListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return contentTypeGetTableList(params, config);
		},
	});
}

/**
 * @description 권한이 있는 테이블 목록 조회 API
 * @summary v1 테이블 목록 조회
 * {@link /v1/content-type/tables}
 */
export function useContentTypeGetTableListSuspense<
	TData = ContentTypeGetTableListQueryResponse,
	TQueryKey extends QueryKey = ContentTypeGetTableListSuspenseQueryKey,
>(
	params?: ContentTypeGetTableListQueryParams,
	options: {
		query?: Partial<UseSuspenseQueryOptions<ContentTypeGetTableListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? contentTypeGetTableListSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{...contentTypeGetTableListSuspenseQueryOptions(params, config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
