/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	ContentTypeGetTableListQueryResponse,
	ContentTypeGetTableListQueryParams,
} from "../../types/content-type/content-type-get-table-list.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {contentTypeGetTableList} from "../../clients/content-type/content-type-get-table-list.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const contentTypeGetTableListQueryKey = (params: ContentTypeGetTableListQueryParams = {}) =>
	[{url: "/v1/content-type/tables"}, ...(params ? [params] : [])] as const;

export type ContentTypeGetTableListQueryKey = ReturnType<typeof contentTypeGetTableListQueryKey>;

export function contentTypeGetTableListQueryOptions(
	params?: ContentTypeGetTableListQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = contentTypeGetTableListQueryKey(params);
	return queryOptions<
		ContentTypeGetTableListQueryResponse,
		ResponseErrorConfig<Error>,
		ContentTypeGetTableListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return contentTypeGetTableList(params, config);
		},
	});
}

/**
 * @description 권한이 있는 테이블 목록 조회 API
 * @summary v1 테이블 목록 조회
 * {@link /v1/content-type/tables}
 */
export function useContentTypeGetTableList<
	TData = ContentTypeGetTableListQueryResponse,
	TQueryData = ContentTypeGetTableListQueryResponse,
	TQueryKey extends QueryKey = ContentTypeGetTableListQueryKey,
>(
	params?: ContentTypeGetTableListQueryParams,
	options: {
		query?: Partial<
			QueryObserverOptions<ContentTypeGetTableListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? contentTypeGetTableListQueryKey(params);

	const query = useQuery(
		{...contentTypeGetTableListQueryOptions(params, config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
