/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {CacheFlushAllRedisCache200, CacheFlushAllRedisCacheMutationResponse} from "../../types/cache/cache-flush-all-redis-cache.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createCacheFlushAllRedisCache200(data?: Partial<CacheFlushAllRedisCache200>): CacheFlushAllRedisCache200 {
	return createUnitResult(data);
}

export function createCacheFlushAllRedisCacheMutationResponse(
	data?: Partial<CacheFlushAllRedisCacheMutationResponse>,
): CacheFlushAllRedisCacheMutationResponse {
	return data || faker.helpers.arrayElement<any>([createCacheFlushAllRedisCache200()]);
}
