/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {TenantUpsertMutationRequest, TenantUpsertMutationResponse} from "../../types/tenant/tenant-upsert.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getTenantUpsertUrl() {
	const res = {method: "POST", url: `/v1/tenants` as const};
	return res;
}

/**
 * @description 테넌트 등록/수정 API
 * @summary v1 테넌트 등록/수정
 * {@link /v1/tenants}
 */
export async function tenantUpsert(
	data: TenantUpsertMutationRequest,
	config: Partial<RequestConfig<TenantUpsertMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<TenantUpsertMutationResponse, ResponseErrorConfig<Error>, TenantUpsertMutationRequest>({
		method: "POST",
		url: getTenantUpsertUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
