/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {TenantSearchTenantsQueryResponse, TenantSearchTenantsQueryParams} from "../../types/tenant/tenant-search-tenants.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getTenantSearchTenantsUrl() {
	const res = {method: "GET", url: `/v1/tenants` as const};
	return res;
}

/**
 * @description removed=false 테넌트 목록을 id desc 정렬로 페이징 조회 API
 * @summary v1 테넌트 목록 조회
 * {@link /v1/tenants}
 */
export async function tenantSearchTenants(
	params?: TenantSearchTenantsQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<TenantSearchTenantsQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getTenantSearchTenantsUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
