/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {TenantRemoveMutationResponse, TenantRemovePathParams} from "../../types/tenant/tenant-remove.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getTenantRemoveUrl(id: TenantRemovePathParams["id"]) {
	const res = {method: "DELETE", url: `/v1/tenants/${id}` as const};
	return res;
}

/**
 * @description 테넌트 삭제 API(soft delete)
 * @summary v1 테넌트 삭제
 * {@link /v1/tenants/:id}
 */
export async function tenantRemove(id: TenantRemovePathParams["id"], config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<TenantRemoveMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "DELETE",
		url: getTenantRemoveUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
