/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {tenantRemove} from "./tenant-remove.ts";
import {tenantSearchTenants} from "./tenant-search-tenants.ts";
import {tenantUpsert} from "./tenant-upsert.ts";

export function tenant() {
	return {tenantSearchTenants, tenantUpsert, tenantRemove};
}
