/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {CacheFlushAllRedisCacheMutationResponse} from "../../types/cache/cache-flush-all-redis-cache.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getCacheFlushAllRedisCacheUrl() {
	const res = {method: "POST", url: `/v1/cache/flush-all` as const};
	return res;
}

/**
 * @description Redis 캐시 전체 삭제 API
 * @summary v1 Redis 캐시 전체 삭제
 * {@link /v1/cache/flush-all}
 */
export async function cacheFlushAllRedisCache(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<CacheFlushAllRedisCacheMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "POST",
		url: getCacheFlushAllRedisCacheUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
