/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {BoardRemoveMutationResponse, BoardRemovePathParams} from "../../types/board/board-remove.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {boardRemove} from "../../clients/board/board-remove.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const boardRemoveMutationKey = () => [{url: "/v1/boards/:id"}] as const;

export type BoardRemoveMutationKey = ReturnType<typeof boardRemoveMutationKey>;

export function boardRemoveMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = boardRemoveMutationKey();
	return mutationOptions<BoardRemoveMutationResponse, ResponseErrorConfig<Error>, {id: BoardRemovePathParams["id"]}, TContext>({
		mutationKey,
		mutationFn: async ({id}) => {
			return boardRemove(id, config);
		},
	});
}

/**
 * @description 게시글 삭제 API(soft delete)
 * @summary v1 게시글 삭제
 * {@link /v1/boards/:id}
 */
export function useBoardRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<BoardRemoveMutationResponse, ResponseErrorConfig<Error>, {id: BoardRemovePathParams["id"]}, TContext> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? boardRemoveMutationKey();

	const baseOptions = boardRemoveMutationOptions(config) as UseMutationOptions<
		BoardRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{id: BoardRemovePathParams["id"]},
		TContext
	>;

	return useMutation<BoardRemoveMutationResponse, ResponseErrorConfig<Error>, {id: BoardRemovePathParams["id"]}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<BoardRemoveMutationResponse, ResponseErrorConfig<Error>, {id: BoardRemovePathParams["id"]}, TContext>;
}
