/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {BoardSearchBoardsQueryResponse, BoardSearchBoardsQueryParams} from "../../types/board/board-search-boards.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {boardSearchBoards} from "../../clients/board/board-search-boards.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const boardSearchBoardsSuspenseQueryKey = (params: BoardSearchBoardsQueryParams = {}) =>
	[{url: "/v1/boards"}, ...(params ? [params] : [])] as const;

export type BoardSearchBoardsSuspenseQueryKey = ReturnType<typeof boardSearchBoardsSuspenseQueryKey>;

export function boardSearchBoardsSuspenseQueryOptions(
	params?: BoardSearchBoardsQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = boardSearchBoardsSuspenseQueryKey(params);
	return queryOptions<BoardSearchBoardsQueryResponse, ResponseErrorConfig<Error>, BoardSearchBoardsQueryResponse, typeof queryKey>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return boardSearchBoards(params, config);
		},
	});
}

/**
 * @description removed=false 게시글 목록을 id desc 정렬로 페이징 조회 API
 * @summary v1 게시글 목록 조회
 * {@link /v1/boards}
 */
export function useBoardSearchBoardsSuspense<
	TData = BoardSearchBoardsQueryResponse,
	TQueryKey extends QueryKey = BoardSearchBoardsSuspenseQueryKey,
>(
	params?: BoardSearchBoardsQueryParams,
	options: {
		query?: Partial<UseSuspenseQueryOptions<BoardSearchBoardsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? boardSearchBoardsSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{...boardSearchBoardsSuspenseQueryOptions(params, config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
