/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {BoardUpsertMutationRequest, BoardUpsertMutationResponse} from "../../types/board/board-upsert.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {boardUpsert} from "../../clients/board/board-upsert.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const boardUpsertMutationKey = () => [{url: "/v1/boards"}] as const;

export type BoardUpsertMutationKey = ReturnType<typeof boardUpsertMutationKey>;

export function boardUpsertMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<BoardUpsertMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = boardUpsertMutationKey();
	return mutationOptions<BoardUpsertMutationResponse, ResponseErrorConfig<Error>, {data: BoardUpsertMutationRequest}, TContext>({
		mutationKey,
		mutationFn: async ({data}) => {
			return boardUpsert(data, config);
		},
	});
}

/**
 * @description 게시글 등록/수정 API
 * @summary v1 게시글 등록/수정
 * {@link /v1/boards}
 */
export function useBoardUpsert<TContext>(
	options: {
		mutation?: UseMutationOptions<BoardUpsertMutationResponse, ResponseErrorConfig<Error>, {data: BoardUpsertMutationRequest}, TContext> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig<BoardUpsertMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? boardUpsertMutationKey();

	const baseOptions = boardUpsertMutationOptions(config) as UseMutationOptions<
		BoardUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: BoardUpsertMutationRequest},
		TContext
	>;

	return useMutation<BoardUpsertMutationResponse, ResponseErrorConfig<Error>, {data: BoardUpsertMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<BoardUpsertMutationResponse, ResponseErrorConfig<Error>, {data: BoardUpsertMutationRequest}, TContext>;
}
