/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	ContentManagerGetTableInfoQueryResponse,
	ContentManagerGetTableInfoQueryParams,
} from "../../types/content-manager/content-manager-get-table-info.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getContentManagerGetTableInfoUrl() {
	const res = {method: "GET", url: `/v1/content-manager/contents/table-info` as const};
	return res;
}

/**
 * @description 테이블/컬럼 정보 조회(등록, 수정용) API
 * @summary v1 테이블 정보 조회
 * {@link /v1/content-manager/contents/table-info}
 */
export async function contentManagerGetTableInfo(
	params: ContentManagerGetTableInfoQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<ContentManagerGetTableInfoQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getContentManagerGetTableInfoUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
