/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	ContentManagerUpsertMutationRequest,
	ContentManagerUpsertMutationResponse,
	ContentManagerUpsertQueryParams,
} from "../../types/content-manager/content-manager-upsert.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getContentManagerUpsertUrl() {
	const res = {method: "POST", url: `/v1/content-manager/contents` as const};
	return res;
}

/**
 * @description 컨텐츠 생성/수정 API (body에 id가 있으면 UPDATE, 없으면 INSERT)
 * @summary v1 컨텐츠 생성/수정
 * {@link /v1/content-manager/contents}
 */
export async function contentManagerUpsert(
	params: ContentManagerUpsertQueryParams,
	data?: ContentManagerUpsertMutationRequest,
	config: Partial<RequestConfig<ContentManagerUpsertMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<ContentManagerUpsertMutationResponse, ResponseErrorConfig<Error>, ContentManagerUpsertMutationRequest>({
		method: "POST",
		url: getContentManagerUpsertUrl().url.toString(),
		params,
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
