/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	ContentManagerSearchContentsQueryResponse,
	ContentManagerSearchContentsQueryParams,
} from "../../types/content-manager/content-manager-search-contents.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getContentManagerSearchContentsUrl() {
	const res = {method: "GET", url: `/v1/content-manager/contents` as const};
	return res;
}

/**
 * @description 컨텐츠 목록 조회 API
 * @summary v1 컨텐츠 목록 조회
 * {@link /v1/content-manager/contents}
 */
export async function contentManagerSearchContents(
	params: ContentManagerSearchContentsQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<ContentManagerSearchContentsQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getContentManagerSearchContentsUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
