/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {contentManagerGetItem} from "./content-manager-get-item.ts";
import {contentManagerGetTableInfo} from "./content-manager-get-table-info.ts";
import {contentManagerRemoves} from "./content-manager-removes.ts";
import {contentManagerSearchContents} from "./content-manager-search-contents.ts";
import {contentManagerUpsert} from "./content-manager-upsert.ts";

export function contentManager() {
	return {contentManagerSearchContents, contentManagerUpsert, contentManagerRemoves, contentManagerGetItem, contentManagerGetTableInfo};
}
