/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	ContentManagerGetItemQueryResponse,
	ContentManagerGetItemPathParams,
	ContentManagerGetItemQueryParams,
} from "../../types/content-manager/content-manager-get-item.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getContentManagerGetItemUrl(id: ContentManagerGetItemPathParams["id"]) {
	const res = {method: "GET", url: `/v1/content-manager/contents/${id}` as const};
	return res;
}

/**
 * @description 컨텐츠 상세 조회 API
 * @summary v1 컨텐츠 상세 조회
 * {@link /v1/content-manager/contents/:id}
 */
export async function contentManagerGetItem(
	id: ContentManagerGetItemPathParams["id"],
	params: ContentManagerGetItemQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<ContentManagerGetItemQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getContentManagerGetItemUrl(id).url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
