/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	ContentManagerRemovesMutationResponse,
	ContentManagerRemovesQueryParams,
} from "../../types/content-manager/content-manager-removes.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getContentManagerRemovesUrl() {
	const res = {method: "DELETE", url: `/v1/content-manager/contents` as const};
	return res;
}

/**
 * @description 컨텐츠 삭제 API
 * @summary v1 컨텐츠 삭제
 * {@link /v1/content-manager/contents}
 */
export async function contentManagerRemoves(
	params: ContentManagerRemovesQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<ContentManagerRemovesMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "DELETE",
		url: getContentManagerRemovesUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
