/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {permissionGroupGetApiEndpointList} from "./permission-group-get-api-endpoint-list.ts";
import {permissionGroupGetItem} from "./permission-group-get-item.ts";
import {permissionGroupGetList} from "./permission-group-get-list.ts";
import {permissionGroupRemove} from "./permission-group-remove.ts";
import {permissionGroupUpsert} from "./permission-group-upsert.ts";

export function permissionGroup() {
	return {permissionGroupGetList, permissionGroupUpsert, permissionGroupGetItem, permissionGroupRemove, permissionGroupGetApiEndpointList};
}
