/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {PermissionGroupGetApiEndpointListQueryResponse} from "../../types/permission-group/permission-group-get-api-endpoint-list.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getPermissionGroupGetApiEndpointListUrl() {
	const res = {method: "GET", url: `/v1/admins/permission-groups/api-endpoints` as const};
	return res;
}

/**
 * @description  API 엔드포인트(Tag name 기준으로 그룹핑된 HTTP 메서드) 목록 조회 API
 * @summary v1 API 엔드포인트 목록 조회
 * {@link /v1/admins/permission-groups/api-endpoints}
 */
export async function permissionGroupGetApiEndpointList(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<PermissionGroupGetApiEndpointListQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getPermissionGroupGetApiEndpointListUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
