/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {PermissionGroupGetListQueryResponse} from "../../types/permission-group/permission-group-get-list.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getPermissionGroupGetListUrl() {
	const res = {method: "GET", url: `/v1/admins/permission-groups` as const};
	return res;
}

/**
 * @description 권한 그룹 목록 조회 API
 * @summary v1 권한 그룹 목록 조회
 * {@link /v1/admins/permission-groups}
 */
export async function permissionGroupGetList(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<PermissionGroupGetListQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getPermissionGroupGetListUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
