/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	PermissionGroupUpsertMutationRequest,
	PermissionGroupUpsertMutationResponse,
} from "../../types/permission-group/permission-group-upsert.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getPermissionGroupUpsertUrl() {
	const res = {method: "POST", url: `/v1/admins/permission-groups` as const};
	return res;
}

/**
 * @description 관리자 권한 등록/수정 API
 * @summary v1 권한 그룹 등록/수정
 * {@link /v1/admins/permission-groups}
 */
export async function permissionGroupUpsert(
	data: PermissionGroupUpsertMutationRequest,
	config: Partial<RequestConfig<PermissionGroupUpsertMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<PermissionGroupUpsertMutationResponse, ResponseErrorConfig<Error>, PermissionGroupUpsertMutationRequest>({
		method: "POST",
		url: getPermissionGroupUpsertUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
