/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	PermissionGroupGetItemQueryResponse,
	PermissionGroupGetItemPathParams,
} from "../../types/permission-group/permission-group-get-item.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getPermissionGroupGetItemUrl(permissionGroupId: PermissionGroupGetItemPathParams["permissionGroupId"]) {
	const res = {method: "GET", url: `/v1/admins/permission-groups/${permissionGroupId}` as const};
	return res;
}

/**
 * @description 권한 상세 조회 API
 * @summary v1 권한 그룹 상세 조회
 * {@link /v1/admins/permission-groups/:permissionGroupId}
 */
export async function permissionGroupGetItem(
	permissionGroupId: PermissionGroupGetItemPathParams["permissionGroupId"],
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<PermissionGroupGetItemQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getPermissionGroupGetItemUrl(permissionGroupId).url.toString(),
		...requestConfig,
	});
	return res.data;
}
