/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	PermissionGroupRemoveMutationResponse,
	PermissionGroupRemovePathParams,
} from "../../types/permission-group/permission-group-remove.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getPermissionGroupRemoveUrl(permissionGroupId: PermissionGroupRemovePathParams["permissionGroupId"]) {
	const res = {method: "DELETE", url: `/v1/admins/permission-groups/${permissionGroupId}` as const};
	return res;
}

/**
 * @description 관리자 권한 삭제 API
 * @summary v1 권한 그룹 삭제
 * {@link /v1/admins/permission-groups/:permissionGroupId}
 */
export async function permissionGroupRemove(
	permissionGroupId: PermissionGroupRemovePathParams["permissionGroupId"],
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<PermissionGroupRemoveMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "DELETE",
		url: getPermissionGroupRemoveUrl(permissionGroupId).url.toString(),
		...requestConfig,
	});
	return res.data;
}
