/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	MediaLibrarySearchMediaLibraryQueryResponse,
	MediaLibrarySearchMediaLibraryQueryParams,
} from "../../types/media-library/media-library-search-media-library.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {mediaLibrarySearchMediaLibrary} from "../../clients/media-library/media-library-search-media-library.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const mediaLibrarySearchMediaLibraryQueryKey = (params: MediaLibrarySearchMediaLibraryQueryParams = {}) =>
	[{url: "/v1/media-library"}, ...(params ? [params] : [])] as const;

export type MediaLibrarySearchMediaLibraryQueryKey = ReturnType<typeof mediaLibrarySearchMediaLibraryQueryKey>;

export function mediaLibrarySearchMediaLibraryQueryOptions(
	params?: MediaLibrarySearchMediaLibraryQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = mediaLibrarySearchMediaLibraryQueryKey(params);
	return queryOptions<
		MediaLibrarySearchMediaLibraryQueryResponse,
		ResponseErrorConfig<Error>,
		MediaLibrarySearchMediaLibraryQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return mediaLibrarySearchMediaLibrary(params, config);
		},
	});
}

/**
 * @description 미디어 라이브러리 목록 조회 API
 * @summary v1 미디어 라이브러리 목록 조회
 * {@link /v1/media-library}
 */
export function useMediaLibrarySearchMediaLibrary<
	TData = MediaLibrarySearchMediaLibraryQueryResponse,
	TQueryData = MediaLibrarySearchMediaLibraryQueryResponse,
	TQueryKey extends QueryKey = MediaLibrarySearchMediaLibraryQueryKey,
>(
	params?: MediaLibrarySearchMediaLibraryQueryParams,
	options: {
		query?: Partial<
			QueryObserverOptions<MediaLibrarySearchMediaLibraryQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? mediaLibrarySearchMediaLibraryQueryKey(params);

	const query = useQuery(
		{...mediaLibrarySearchMediaLibraryQueryOptions(params, config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
