/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {MediaLibraryRemoveMutationResponse, MediaLibraryRemovePathParams} from "../../types/media-library/media-library-remove.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {mediaLibraryRemove} from "../../clients/media-library/media-library-remove.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const mediaLibraryRemoveMutationKey = () => [{url: "/v1/media-library/:id"}] as const;

export type MediaLibraryRemoveMutationKey = ReturnType<typeof mediaLibraryRemoveMutationKey>;

export function mediaLibraryRemoveMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = mediaLibraryRemoveMutationKey();
	return mutationOptions<
		MediaLibraryRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{id: MediaLibraryRemovePathParams["id"]},
		TContext
	>({
		mutationKey,
		mutationFn: async ({id}) => {
			return mediaLibraryRemove(id, config);
		},
	});
}

/**
 * @description 미디어 라이브러리 단건 삭제 API
 * @summary v1 미디어 라이브러리 삭제
 * {@link /v1/media-library/:id}
 */
export function useMediaLibraryRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			MediaLibraryRemoveMutationResponse,
			ResponseErrorConfig<Error>,
			{id: MediaLibraryRemovePathParams["id"]},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? mediaLibraryRemoveMutationKey();

	const baseOptions = mediaLibraryRemoveMutationOptions(config) as UseMutationOptions<
		MediaLibraryRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{id: MediaLibraryRemovePathParams["id"]},
		TContext
	>;

	return useMutation<MediaLibraryRemoveMutationResponse, ResponseErrorConfig<Error>, {id: MediaLibraryRemovePathParams["id"]}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<
		MediaLibraryRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{id: MediaLibraryRemovePathParams["id"]},
		TContext
	>;
}
