/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	MediaLibraryUpsertMutationRequest,
	MediaLibraryUpsertMutationResponse,
} from "../../types/media-library/media-library-upsert.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {mediaLibraryUpsert} from "../../clients/media-library/media-library-upsert.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const mediaLibraryUpsertMutationKey = () => [{url: "/v1/media-library"}] as const;

export type MediaLibraryUpsertMutationKey = ReturnType<typeof mediaLibraryUpsertMutationKey>;

export function mediaLibraryUpsertMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<MediaLibraryUpsertMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = mediaLibraryUpsertMutationKey();
	return mutationOptions<
		MediaLibraryUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: MediaLibraryUpsertMutationRequest},
		TContext
	>({
		mutationKey,
		mutationFn: async ({data}) => {
			return mediaLibraryUpsert(data, config);
		},
	});
}

/**
 * @description 미디어 라이브러리 생성/수정 API
 * @summary v1 미디어 라이브러리 생성/수정
 * {@link /v1/media-library}
 */
export function useMediaLibraryUpsert<TContext>(
	options: {
		mutation?: UseMutationOptions<
			MediaLibraryUpsertMutationResponse,
			ResponseErrorConfig<Error>,
			{data: MediaLibraryUpsertMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<MediaLibraryUpsertMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? mediaLibraryUpsertMutationKey();

	const baseOptions = mediaLibraryUpsertMutationOptions(config) as UseMutationOptions<
		MediaLibraryUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: MediaLibraryUpsertMutationRequest},
		TContext
	>;

	return useMutation<MediaLibraryUpsertMutationResponse, ResponseErrorConfig<Error>, {data: MediaLibraryUpsertMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<
		MediaLibraryUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: MediaLibraryUpsertMutationRequest},
		TContext
	>;
}
