/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	EnvironmentGetAuthPlatform200,
	EnvironmentGetAuthPlatformQueryResponse,
} from "../../types/environment/environment-get-auth-platform.ts";
import {createApiResultAuthPlatformResponse} from "../create-api-result-auth-platform-response.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createEnvironmentGetAuthPlatform200(data?: Partial<EnvironmentGetAuthPlatform200>): EnvironmentGetAuthPlatform200 {
	return createApiResultAuthPlatformResponse(data);
}

export function createEnvironmentGetAuthPlatformQueryResponse(
	data?: Partial<EnvironmentGetAuthPlatformQueryResponse>,
): EnvironmentGetAuthPlatformQueryResponse {
	return data || faker.helpers.arrayElement<any>([createEnvironmentGetAuthPlatform200()]);
}
