/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {ConfigValueUpsertMutationRequest, ConfigValueUpsertMutationResponse} from "../../types/config-value/config-value-upsert.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {configValueUpsert} from "../../clients/config-value/config-value-upsert.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const configValueUpsertMutationKey = () => [{url: "/v1/config-value"}] as const;

export type ConfigValueUpsertMutationKey = ReturnType<typeof configValueUpsertMutationKey>;

export function configValueUpsertMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<ConfigValueUpsertMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = configValueUpsertMutationKey();
	return mutationOptions<ConfigValueUpsertMutationResponse, ResponseErrorConfig<Error>, {data: ConfigValueUpsertMutationRequest}, TContext>(
		{
			mutationKey,
			mutationFn: async ({data}) => {
				return configValueUpsert(data, config);
			},
		},
	);
}

/**
 * @description 설정 생성/수정 API
 * @summary v1 설정 생성/수정
 * {@link /v1/config-value}
 */
export function useConfigValueUpsert<TContext>(
	options: {
		mutation?: UseMutationOptions<
			ConfigValueUpsertMutationResponse,
			ResponseErrorConfig<Error>,
			{data: ConfigValueUpsertMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<ConfigValueUpsertMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? configValueUpsertMutationKey();

	const baseOptions = configValueUpsertMutationOptions(config) as UseMutationOptions<
		ConfigValueUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: ConfigValueUpsertMutationRequest},
		TContext
	>;

	return useMutation<ConfigValueUpsertMutationResponse, ResponseErrorConfig<Error>, {data: ConfigValueUpsertMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<ConfigValueUpsertMutationResponse, ResponseErrorConfig<Error>, {data: ConfigValueUpsertMutationRequest}, TContext>;
}
