/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {ConfigValueGetEnumListQueryResponse} from "../../types/config-value/config-value-get-enum-list.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {configValueGetEnumList} from "../../clients/config-value/config-value-get-enum-list.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const configValueGetEnumListQueryKey = () => [{url: "/v1/config-value/enum"}] as const;

export type ConfigValueGetEnumListQueryKey = ReturnType<typeof configValueGetEnumListQueryKey>;

export function configValueGetEnumListQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = configValueGetEnumListQueryKey();
	return queryOptions<
		ConfigValueGetEnumListQueryResponse,
		ResponseErrorConfig<Error>,
		ConfigValueGetEnumListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return configValueGetEnumList(config);
		},
	});
}

/**
 * @description Enum 설정 조회 API
 * @summary v1 Enum 설정 조회
 * {@link /v1/config-value/enum}
 */
export function useConfigValueGetEnumList<
	TData = ConfigValueGetEnumListQueryResponse,
	TQueryData = ConfigValueGetEnumListQueryResponse,
	TQueryKey extends QueryKey = ConfigValueGetEnumListQueryKey,
>(
	options: {
		query?: Partial<QueryObserverOptions<ConfigValueGetEnumListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? configValueGetEnumListQueryKey();

	const query = useQuery(
		{...configValueGetEnumListQueryOptions(config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
