/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {ConfigValueGetItemQueryResponse, ConfigValueGetItemQueryParams} from "../../types/config-value/config-value-get-item.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {configValueGetItem} from "../../clients/config-value/config-value-get-item.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const configValueGetItemQueryKey = (params: ConfigValueGetItemQueryParams) =>
	[{url: "/v1/config-value"}, ...(params ? [params] : [])] as const;

export type ConfigValueGetItemQueryKey = ReturnType<typeof configValueGetItemQueryKey>;

export function configValueGetItemQueryOptions(
	params: ConfigValueGetItemQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = configValueGetItemQueryKey(params);
	return queryOptions<ConfigValueGetItemQueryResponse, ResponseErrorConfig<Error>, ConfigValueGetItemQueryResponse, typeof queryKey>({
		enabled: !!params,
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return configValueGetItem(params, config);
		},
	});
}

/**
 * @description 설정 조회 API
 * @summary v1 설정 조회
 * {@link /v1/config-value}
 */
export function useConfigValueGetItem<
	TData = ConfigValueGetItemQueryResponse,
	TQueryData = ConfigValueGetItemQueryResponse,
	TQueryKey extends QueryKey = ConfigValueGetItemQueryKey,
>(
	params: ConfigValueGetItemQueryParams,
	options: {
		query?: Partial<QueryObserverOptions<ConfigValueGetItemQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? configValueGetItemQueryKey(params);

	const query = useQuery(
		{...configValueGetItemQueryOptions(params, config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
