/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {ContentFolderSaveMutationRequest, ContentFolderSaveMutationResponse} from "../../types/content-folder/content-folder-save.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {contentFolderSave} from "../../clients/content-folder/content-folder-save.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const contentFolderSaveMutationKey = () => [{url: "/v1/content-folders"}] as const;

export type ContentFolderSaveMutationKey = ReturnType<typeof contentFolderSaveMutationKey>;

export function contentFolderSaveMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<ContentFolderSaveMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = contentFolderSaveMutationKey();
	return mutationOptions<ContentFolderSaveMutationResponse, ResponseErrorConfig<Error>, {data: ContentFolderSaveMutationRequest}, TContext>(
		{
			mutationKey,
			mutationFn: async ({data}) => {
				return contentFolderSave(data, config);
			},
		},
	);
}

/**
 * @description 폴더/테이블 배치 전체를 일괄 저장하는 API
 * @summary v1 컨텐츠 폴더 트리 저장
 * {@link /v1/content-folders}
 */
export function useContentFolderSave<TContext>(
	options: {
		mutation?: UseMutationOptions<
			ContentFolderSaveMutationResponse,
			ResponseErrorConfig<Error>,
			{data: ContentFolderSaveMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<ContentFolderSaveMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? contentFolderSaveMutationKey();

	const baseOptions = contentFolderSaveMutationOptions(config) as UseMutationOptions<
		ContentFolderSaveMutationResponse,
		ResponseErrorConfig<Error>,
		{data: ContentFolderSaveMutationRequest},
		TContext
	>;

	return useMutation<ContentFolderSaveMutationResponse, ResponseErrorConfig<Error>, {data: ContentFolderSaveMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<ContentFolderSaveMutationResponse, ResponseErrorConfig<Error>, {data: ContentFolderSaveMutationRequest}, TContext>;
}
