/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {ContentFolderGetListQueryResponse} from "../../types/content-folder/content-folder-get-list.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {contentFolderGetList} from "../../clients/content-folder/content-folder-get-list.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const contentFolderGetListSuspenseQueryKey = () => [{url: "/v1/content-folders"}] as const;

export type ContentFolderGetListSuspenseQueryKey = ReturnType<typeof contentFolderGetListSuspenseQueryKey>;

export function contentFolderGetListSuspenseQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = contentFolderGetListSuspenseQueryKey();
	return queryOptions<ContentFolderGetListQueryResponse, ResponseErrorConfig<Error>, ContentFolderGetListQueryResponse, typeof queryKey>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return contentFolderGetList(config);
		},
	});
}

/**
 * @description 권한을 반영한 컨텐츠 폴더 트리 조회 API
 * @summary v1 컨텐츠 폴더 트리 조회
 * {@link /v1/content-folders}
 */
export function useContentFolderGetListSuspense<
	TData = ContentFolderGetListQueryResponse,
	TQueryKey extends QueryKey = ContentFolderGetListSuspenseQueryKey,
>(
	options: {
		query?: Partial<UseSuspenseQueryOptions<ContentFolderGetListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? contentFolderGetListSuspenseQueryKey();

	const query = useSuspenseQuery(
		{...contentFolderGetListSuspenseQueryOptions(config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
