/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {FilterUpsertMutationRequest, FilterUpsertMutationResponse} from "../../types/filter/filter-upsert.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {filterUpsert} from "../../clients/filter/filter-upsert.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const filterUpsertMutationKey = () => [{url: "/v1/filters"}] as const;

export type FilterUpsertMutationKey = ReturnType<typeof filterUpsertMutationKey>;

export function filterUpsertMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<FilterUpsertMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = filterUpsertMutationKey();
	return mutationOptions<FilterUpsertMutationResponse, ResponseErrorConfig<Error>, {data: FilterUpsertMutationRequest}, TContext>({
		mutationKey,
		mutationFn: async ({data}) => {
			return filterUpsert(data, config);
		},
	});
}

/**
 * @description 필터 등록/수정 API
 * @summary v1 필터 등록/수정
 * {@link /v1/filters}
 */
export function useFilterUpsert<TContext>(
	options: {
		mutation?: UseMutationOptions<
			FilterUpsertMutationResponse,
			ResponseErrorConfig<Error>,
			{data: FilterUpsertMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<FilterUpsertMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? filterUpsertMutationKey();

	const baseOptions = filterUpsertMutationOptions(config) as UseMutationOptions<
		FilterUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: FilterUpsertMutationRequest},
		TContext
	>;

	return useMutation<FilterUpsertMutationResponse, ResponseErrorConfig<Error>, {data: FilterUpsertMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<FilterUpsertMutationResponse, ResponseErrorConfig<Error>, {data: FilterUpsertMutationRequest}, TContext>;
}
