/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {FilterSearchFiltersQueryResponse, FilterSearchFiltersQueryParams} from "../../types/filter/filter-search-filters.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {filterSearchFilters} from "../../clients/filter/filter-search-filters.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const filterSearchFiltersQueryKey = (params: FilterSearchFiltersQueryParams = {}) =>
	[{url: "/v1/filters"}, ...(params ? [params] : [])] as const;

export type FilterSearchFiltersQueryKey = ReturnType<typeof filterSearchFiltersQueryKey>;

export function filterSearchFiltersQueryOptions(
	params?: FilterSearchFiltersQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = filterSearchFiltersQueryKey(params);
	return queryOptions<FilterSearchFiltersQueryResponse, ResponseErrorConfig<Error>, FilterSearchFiltersQueryResponse, typeof queryKey>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return filterSearchFilters(params, config);
		},
	});
}

/**
 * @description removed=false 필터 목록을 id desc 정렬로 페이징 조회 API
 * @summary v1 필터 목록 조회
 * {@link /v1/filters}
 */
export function useFilterSearchFilters<
	TData = FilterSearchFiltersQueryResponse,
	TQueryData = FilterSearchFiltersQueryResponse,
	TQueryKey extends QueryKey = FilterSearchFiltersQueryKey,
>(
	params?: FilterSearchFiltersQueryParams,
	options: {
		query?: Partial<QueryObserverOptions<FilterSearchFiltersQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? filterSearchFiltersQueryKey(params);

	const query = useQuery(
		{...filterSearchFiltersQueryOptions(params, config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
