/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {FilterRemoveMutationResponse, FilterRemovePathParams} from "../../types/filter/filter-remove.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {filterRemove} from "../../clients/filter/filter-remove.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const filterRemoveMutationKey = () => [{url: "/v1/filters/:id"}] as const;

export type FilterRemoveMutationKey = ReturnType<typeof filterRemoveMutationKey>;

export function filterRemoveMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = filterRemoveMutationKey();
	return mutationOptions<FilterRemoveMutationResponse, ResponseErrorConfig<Error>, {id: FilterRemovePathParams["id"]}, TContext>({
		mutationKey,
		mutationFn: async ({id}) => {
			return filterRemove(id, config);
		},
	});
}

/**
 * @description 필터 삭제 API(soft delete)
 * @summary v1 필터 삭제
 * {@link /v1/filters/:id}
 */
export function useFilterRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			FilterRemoveMutationResponse,
			ResponseErrorConfig<Error>,
			{id: FilterRemovePathParams["id"]},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? filterRemoveMutationKey();

	const baseOptions = filterRemoveMutationOptions(config) as UseMutationOptions<
		FilterRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{id: FilterRemovePathParams["id"]},
		TContext
	>;

	return useMutation<FilterRemoveMutationResponse, ResponseErrorConfig<Error>, {id: FilterRemovePathParams["id"]}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<FilterRemoveMutationResponse, ResponseErrorConfig<Error>, {id: FilterRemovePathParams["id"]}, TContext>;
}
