/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	ContentMediaCreatePresignedUrlsMutationRequest,
	ContentMediaCreatePresignedUrlsMutationResponse,
	ContentMediaCreatePresignedUrlsQueryParams,
} from "../../types/content-media/content-media-create-presigned-urls.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {contentMediaCreatePresignedUrls} from "../../clients/content-media/content-media-create-presigned-urls.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const contentMediaCreatePresignedUrlsMutationKey = () => [{url: "/v1/content-media/aws/presigned-url"}] as const;

export type ContentMediaCreatePresignedUrlsMutationKey = ReturnType<typeof contentMediaCreatePresignedUrlsMutationKey>;

export function contentMediaCreatePresignedUrlsMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<ContentMediaCreatePresignedUrlsMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = contentMediaCreatePresignedUrlsMutationKey();
	return mutationOptions<
		ContentMediaCreatePresignedUrlsMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentMediaCreatePresignedUrlsQueryParams; data?: ContentMediaCreatePresignedUrlsMutationRequest},
		TContext
	>({
		mutationKey,
		mutationFn: async ({params, data}) => {
			return contentMediaCreatePresignedUrls(params, data, config);
		},
	});
}

/**
 * @description MEDIA 파일 다중 업로드용 AWS Presigned URL 발급 API
 * @summary v1 MEDIA Presigned URL 발급
 * {@link /v1/content-media/aws/presigned-url}
 */
export function useContentMediaCreatePresignedUrls<TContext>(
	options: {
		mutation?: UseMutationOptions<
			ContentMediaCreatePresignedUrlsMutationResponse,
			ResponseErrorConfig<Error>,
			{params: ContentMediaCreatePresignedUrlsQueryParams; data?: ContentMediaCreatePresignedUrlsMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<ContentMediaCreatePresignedUrlsMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? contentMediaCreatePresignedUrlsMutationKey();

	const baseOptions = contentMediaCreatePresignedUrlsMutationOptions(config) as UseMutationOptions<
		ContentMediaCreatePresignedUrlsMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentMediaCreatePresignedUrlsQueryParams; data?: ContentMediaCreatePresignedUrlsMutationRequest},
		TContext
	>;

	return useMutation<
		ContentMediaCreatePresignedUrlsMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentMediaCreatePresignedUrlsQueryParams; data?: ContentMediaCreatePresignedUrlsMutationRequest},
		TContext
	>({...baseOptions, mutationKey, ...mutationOptions}, queryClient) as UseMutationResult<
		ContentMediaCreatePresignedUrlsMutationResponse,
		ResponseErrorConfig<Error>,
		{params: ContentMediaCreatePresignedUrlsQueryParams; data?: ContentMediaCreatePresignedUrlsMutationRequest},
		TContext
	>;
}
