/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {MediaLibraryInsertRequest} from "../media-library-insert-request.ts";
import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type MediaLibraryUpsert200 = UnitResult;

export type MediaLibraryUpsertMutationRequest = MediaLibraryInsertRequest;

export type MediaLibraryUpsertMutationResponse = MediaLibraryUpsert200;

export type MediaLibraryUpsertMutation = {Response: MediaLibraryUpsert200; Request: MediaLibraryUpsertMutationRequest; Errors: any};
