/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UnitResult} from "../unit-result.ts";

export type MediaLibraryRemovePathParams = {
	/**
	 * @type integer, int64
	 */
	id: number;
};

/**
 * @description OK
 */
export type MediaLibraryRemove200 = UnitResult;

export type MediaLibraryRemoveMutationResponse = MediaLibraryRemove200;

export type MediaLibraryRemoveMutation = {Response: MediaLibraryRemove200; PathParams: MediaLibraryRemovePathParams; Errors: any};
