/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type CacheFlushAllRedisCache200 = UnitResult;

export type CacheFlushAllRedisCacheMutationResponse = CacheFlushAllRedisCache200;

export type CacheFlushAllRedisCacheMutation = {Response: CacheFlushAllRedisCache200; Errors: any};
