/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOneListContentFolderNodeResponse} from "../api-result-one-list-content-folder-node-response.ts";

/**
 * @description OK
 */
export type ContentFolderGetList200 = ApiResultOneListContentFolderNodeResponse;

export type ContentFolderGetListQueryResponse = ContentFolderGetList200;

export type ContentFolderGetListQuery = {Response: ContentFolderGetList200; Errors: any};
