/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ContentFolderSaveRequest} from "../content-folder-save-request.ts";
import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type ContentFolderSave200 = UnitResult;

export type ContentFolderSaveMutationRequest = ContentFolderSaveRequest;

export type ContentFolderSaveMutationResponse = ContentFolderSave200;

export type ContentFolderSaveMutation = {Response: ContentFolderSave200; Request: ContentFolderSaveMutationRequest; Errors: any};
