/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultListConfigValueResponse} from "../api-result-list-config-value-response.ts";

/**
 * @description OK
 */
export type ConfigValueGetEnumList200 = ApiResultListConfigValueResponse;

export type ConfigValueGetEnumListQueryResponse = ConfigValueGetEnumList200;

export type ConfigValueGetEnumListQuery = {Response: ConfigValueGetEnumList200; Errors: any};
