/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultConfigValueResponse} from "../api-result-config-value-response.ts";

export type ConfigValueGetItemQueryParams = {
	/**
	 * @type string
	 */
	config: string;
};

/**
 * @description OK
 */
export type ConfigValueGetItem200 = ApiResultConfigValueResponse;

export type ConfigValueGetItemQueryResponse = ConfigValueGetItem200;

export type ConfigValueGetItemQuery = {Response: ConfigValueGetItem200; QueryParams: ConfigValueGetItemQueryParams; Errors: any};
