/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ConfigValueRequest} from "../config-value-request.ts";
import type {ConfigValueResponse} from "../config-value-response.ts";

/**
 * @description OK
 */
export type ConfigValueUpsert200 = ConfigValueResponse;

export type ConfigValueUpsertMutationRequest = ConfigValueRequest;

export type ConfigValueUpsertMutationResponse = ConfigValueUpsert200;

export type ConfigValueUpsertMutation = {Response: ConfigValueUpsert200; Request: ConfigValueUpsertMutationRequest; Errors: any};
