/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {HomeDashboardGetUserActivitiesQueryResponse} from "../../types/home-dashboard/home-dashboard-get-user-activities.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getHomeDashboardGetUserActivitiesUrl() {
	const res = {method: "GET", url: `/v1/home-dashboard/user-activity` as const};
	return res;
}

/**
 * @description 관리자별 최근 사용자 활동 목록 조회 API
 * @summary v1 사용자 활동 조회
 * {@link /v1/home-dashboard/user-activity}
 */
export async function homeDashboardGetUserActivities(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<HomeDashboardGetUserActivitiesQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getHomeDashboardGetUserActivitiesUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
