/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {HomeDashboardGetBuildNotesQueryResponse} from "../../types/home-dashboard/home-dashboard-get-build-notes.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getHomeDashboardGetBuildNotesUrl() {
	const res = {method: "GET", url: `/v1/home-dashboard/build-notes` as const};
	return res;
}

/**
 * @description 빌드노트 최근 5건 조회 API
 * @summary v1 빌드노트 조회
 * {@link /v1/home-dashboard/build-notes}
 */
export async function homeDashboardGetBuildNotes(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<HomeDashboardGetBuildNotesQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getHomeDashboardGetBuildNotesUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
