/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {HomeDashboardGetNoticesQueryResponse} from "../../types/home-dashboard/home-dashboard-get-notices.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getHomeDashboardGetNoticesUrl() {
	const res = {method: "GET", url: `/v1/home-dashboard/notices` as const};
	return res;
}

/**
 * @description 공지사항 최근 5건 조회 API
 * @summary v1 공지사항 조회
 * {@link /v1/home-dashboard/notices}
 */
export async function homeDashboardGetNotices(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<HomeDashboardGetNoticesQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getHomeDashboardGetNoticesUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
