/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {homeDashboardGetBuildNotes} from "./home-dashboard-get-build-notes.ts";
import {homeDashboardGetNotices} from "./home-dashboard-get-notices.ts";
import {homeDashboardGetUserActivities} from "./home-dashboard-get-user-activities.ts";

export function homeDashboard() {
	return {homeDashboardGetUserActivities, homeDashboardGetNotices, homeDashboardGetBuildNotes};
}
