/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {BoardSaveRequest} from "../board-save-request.ts";
import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type BoardUpsert200 = UnitResult;

export type BoardUpsertMutationRequest = BoardSaveRequest;

export type BoardUpsertMutationResponse = BoardUpsert200;

export type BoardUpsertMutation = {Response: BoardUpsert200; Request: BoardUpsertMutationRequest; Errors: any};
