/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OneListApiEndpointResponse} from "../types/one-list-api-endpoint-response.ts";
import {createApiEndpointResponse} from "./create-api-endpoint-response.ts";
import {faker} from "@faker-js/faker";

export function createOneListApiEndpointResponse(data?: Partial<OneListApiEndpointResponse>): OneListApiEndpointResponse {
	return {...{list: faker.helpers.multiple(() => createApiEndpointResponse())}, ...(data || {})};
}
