/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AuditLogPageResponse} from "../types/audit-log-page-response.ts";
import {faker} from "@faker-js/faker";

export function createAuditLogPageResponse(data?: Partial<AuditLogPageResponse>): AuditLogPageResponse {
	return {
		...{
			id: faker.number.int(),
			adminId: faker.string.alpha(),
			adminName: faker.string.alpha(),
			description: faker.string.alpha(),
			url: faker.string.alpha(),
			method: faker.string.alpha(),
			status: faker.string.alpha(),
			requestBody: faker.string.alpha(),
			executionTimeMs: faker.number.int(),
			start: faker.string.alpha(),
			end: faker.string.alpha(),
			timestamp: faker.string.alpha(),
			createdAt: faker.date.anytime().toISOString(),
		},
		...(data || {}),
	};
}
