/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {PermissionGroupAdminResponse} from "../types/permission-group-admin-response.ts";
import {faker} from "@faker-js/faker";

export function createPermissionGroupAdminResponse(data?: Partial<PermissionGroupAdminResponse>): PermissionGroupAdminResponse {
	return {
		...{id: faker.number.int(), loginId: faker.string.alpha(), name: faker.string.alpha(), removed: faker.datatype.boolean()},
		...(data || {}),
	};
}
