/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ApiEndpointSummaryResponse} from "../types/api-endpoint-summary-response.ts";
import {faker} from "@faker-js/faker";

export function createApiEndpointSummaryResponse(data?: Partial<ApiEndpointSummaryResponse>): ApiEndpointSummaryResponse {
	return {
		...{
			tagName: faker.string.alpha(),
			httpMethods: faker.helpers.multiple(() => faker.helpers.arrayElement<any>(["GET", "POST", "PUT", "DELETE"])),
		},
		...(data || {}),
	};
}
