/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ApiEndpointSaveRequest} from "../types/api-endpoint-save-request.ts";
import {faker} from "@faker-js/faker";

export function createApiEndpointSaveRequest(data?: Partial<ApiEndpointSaveRequest>): ApiEndpointSaveRequest {
	return {
		...{
			tagName: faker.string.alpha({length: 1}),
			httpMethods: faker.helpers.multiple(() => faker.helpers.arrayElement<any>(["GET", "POST", "PUT", "DELETE"])),
		},
		...(data || {}),
	};
}
