/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OneListContentTypeColumnResponse} from "../types/one-list-content-type-column-response.ts";
import {createContentTypeColumnResponse} from "./create-content-type-column-response.ts";
import {faker} from "@faker-js/faker";

export function createOneListContentTypeColumnResponse(data?: Partial<OneListContentTypeColumnResponse>): OneListContentTypeColumnResponse {
	return {...{list: faker.helpers.multiple(() => createContentTypeColumnResponse())}, ...(data || {})};
}
