/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {TenantSaveRequest} from "../types/tenant-save-request.ts";
import {faker} from "@faker-js/faker";

export function createTenantSaveRequest(data?: Partial<TenantSaveRequest>): TenantSaveRequest {
	return {...{id: faker.number.int(), name: faker.string.alpha({length: 1})}, ...(data || {})};
}
