/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OnePageMapStringObject} from "../types/one-page-map-string-object.ts";
import {faker} from "@faker-js/faker";

export function createOnePageMapStringObject(data?: Partial<OnePageMapStringObject>): OnePageMapStringObject {
	return {...{page: faker.number.int(), totalCount: faker.number.int(), list: faker.helpers.multiple(() => ({}))}, ...(data || {})};
}
