/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {BoardSaveRequest} from "../types/board-save-request.ts";
import {faker} from "@faker-js/faker";

export function createBoardSaveRequest(data?: Partial<BoardSaveRequest>): BoardSaveRequest {
	return {
		...{
			id: faker.number.int(),
			type: faker.helpers.arrayElement<NonNullable<BoardSaveRequest>["type"]>(["NOTICE", "BUILD_NOTE"]),
			grade: faker.string.alpha({length: 1}),
			title: faker.string.alpha({length: 1}),
			content: faker.string.alpha(),
		},
		...(data || {}),
	};
}
