/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AdminSummaryResponse} from "../types/admin-summary-response.ts";
import {faker} from "@faker-js/faker";

export function createAdminSummaryResponse(data?: Partial<AdminSummaryResponse>): AdminSummaryResponse {
	return {
		...{
			id: faker.number.int(),
			permissionGroupName: faker.string.alpha(),
			provider: faker.helpers.arrayElement<NonNullable<AdminSummaryResponse>["provider"]>(["GOOGLE", "APPLE"]),
			loginId: faker.string.alpha(),
			name: faker.string.alpha(),
			removed: faker.datatype.boolean(),
			lockedAt: faker.date.anytime().toISOString(),
			lastLoginAt: faker.date.anytime().toISOString(),
			createdAt: faker.date.anytime().toISOString(),
		},
		...(data || {}),
	};
}
