/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {LoginResponse} from "../types/login-response.ts";
import {createTokenInfoResponse} from "./create-token-info-response.ts";
import {faker} from "@faker-js/faker";

export function createLoginResponse(data?: Partial<LoginResponse>): LoginResponse {
	return {
		...{
			otpRequired: faker.datatype.boolean(),
			otpToken: faker.string.alpha(),
			otpExpiredAt: faker.date.anytime().toISOString(),
			tokenInfo: createTokenInfoResponse(),
		},
		...(data || {}),
	};
}
