/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {FilterItemOptionResponse} from "../types/filter-item-option-response.ts";
import {faker} from "@faker-js/faker";

export function createFilterItemOptionResponse(data?: Partial<FilterItemOptionResponse>): FilterItemOptionResponse {
	return {...{label: faker.string.alpha(), value: faker.string.alpha()}, ...(data || {})};
}
