/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OneListContentTypeTableResponse} from "../types/one-list-content-type-table-response.ts";
import {createContentTypeTableResponse} from "./create-content-type-table-response.ts";
import {faker} from "@faker-js/faker";

export function createOneListContentTypeTableResponse(data?: Partial<OneListContentTypeTableResponse>): OneListContentTypeTableResponse {
	return {...{list: faker.helpers.multiple(() => createContentTypeTableResponse())}, ...(data || {})};
}
