/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ConfigValueResponse} from "../types/config-value-response.ts";
import {faker} from "@faker-js/faker";

export function createConfigValueResponse(data?: Partial<ConfigValueResponse>): ConfigValueResponse {
	return {...{config: faker.string.alpha(), value: faker.string.alpha()}, ...(data || {})};
}
