/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {MediaFileResponse} from "../types/media-file-response.ts";
import {faker} from "@faker-js/faker";

export function createMediaFileResponse(data?: Partial<MediaFileResponse>): MediaFileResponse {
	return {
		...{
			id: faker.number.int(),
			url: faker.string.alpha(),
			path: faker.string.alpha(),
			mimeType: faker.string.alpha(),
			name: faker.string.alpha(),
			size: faker.number.int(),
			ext: faker.string.alpha(),
			provider: faker.helpers.arrayElement<NonNullable<MediaFileResponse>["provider"]>(["AWS", "GCP", "NCP", "LOCAL"]),
		},
		...(data || {}),
	};
}
