/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AuthPlatformResponse} from "../types/auth-platform-response.ts";
import {faker} from "@faker-js/faker";

export function createAuthPlatformResponse(data?: Partial<AuthPlatformResponse>): AuthPlatformResponse {
	return {...{usePlatformLogin: faker.datatype.boolean(), useGcpLogin: faker.datatype.boolean()}, ...(data || {})};
}
