/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ContentFolderNodeResponse} from "../types/content-folder-node-response.ts";
import {faker} from "@faker-js/faker";

export function createContentFolderNodeResponse(data?: Partial<ContentFolderNodeResponse>): ContentFolderNodeResponse {
	return {
		...{
			id: faker.number.int(),
			parentId: faker.number.int(),
			nodeType: faker.helpers.arrayElement<NonNullable<ContentFolderNodeResponse>["nodeType"]>(["FOLDER", "TABLE"]),
			name: faker.string.alpha(),
			tableName: faker.string.alpha(),
			orderNumber: faker.number.int(),
			displayed: faker.datatype.boolean(),
			children: undefined as any,
		},
		...(data || {}),
	};
}
