/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OnePageBoardPageResponse} from "../types/one-page-board-page-response.ts";
import {createBoardPageResponse} from "./create-board-page-response.ts";
import {faker} from "@faker-js/faker";

export function createOnePageBoardPageResponse(data?: Partial<OnePageBoardPageResponse>): OnePageBoardPageResponse {
	return {
		...{page: faker.number.int(), totalCount: faker.number.int(), list: faker.helpers.multiple(() => createBoardPageResponse())},
		...(data || {}),
	};
}
