/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OneListMapStringObject} from "../types/one-list-map-string-object.ts";
import {faker} from "@faker-js/faker";

export function createOneListMapStringObject(data?: Partial<OneListMapStringObject>): OneListMapStringObject {
	return {...{list: faker.helpers.multiple(() => ({}))}, ...(data || {})};
}
