/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OnePageAdminSummaryResponse} from "../types/one-page-admin-summary-response.ts";
import {createAdminSummaryResponse} from "./create-admin-summary-response.ts";
import {faker} from "@faker-js/faker";

export function createOnePageAdminSummaryResponse(data?: Partial<OnePageAdminSummaryResponse>): OnePageAdminSummaryResponse {
	return {
		...{page: faker.number.int(), totalCount: faker.number.int(), list: faker.helpers.multiple(() => createAdminSummaryResponse())},
		...(data || {}),
	};
}
