/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {BoardPageResponse} from "../types/board-page-response.ts";
import {faker} from "@faker-js/faker";

export function createBoardPageResponse(data?: Partial<BoardPageResponse>): BoardPageResponse {
	return {
		...{
			id: faker.number.int(),
			type: faker.helpers.arrayElement<NonNullable<BoardPageResponse>["type"]>(["NOTICE", "BUILD_NOTE"]),
			grade: faker.string.alpha(),
			title: faker.string.alpha(),
			content: faker.string.alpha(),
			creatorId: faker.number.int(),
			creatorName: faker.string.alpha(),
			createdAt: faker.date.anytime().toISOString(),
		},
		...(data || {}),
	};
}
