/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {CreateMediaPresignedUrlResponse} from "../types/create-media-presigned-url-response.ts";
import {createMediaFileResponse} from "./create-media-file-response.ts";
import {faker} from "@faker-js/faker";

export function createCreateMediaPresignedUrlResponse(data?: Partial<CreateMediaPresignedUrlResponse>): CreateMediaPresignedUrlResponse {
	return {
		...{
			method: faker.string.alpha(),
			presignedUrl: faker.string.alpha(),
			expiresAt: faker.date.anytime().toISOString(),
			file: createMediaFileResponse(),
		},
		...(data || {}),
	};
}
