/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OneListContentFolderNodeResponse} from "../types/one-list-content-folder-node-response.ts";
import {createContentFolderNodeResponse} from "./create-content-folder-node-response.ts";
import {faker} from "@faker-js/faker";

export function createOneListContentFolderNodeResponse(data?: Partial<OneListContentFolderNodeResponse>): OneListContentFolderNodeResponse {
	return {...{list: faker.helpers.multiple(() => createContentFolderNodeResponse())}, ...(data || {})};
}
