/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ConfigValueRequest} from "../types/config-value-request.ts";
import {faker} from "@faker-js/faker";

/**
 * @description 시스템 설정 DTO
 */
export function createConfigValueRequest(data?: Partial<ConfigValueRequest>): ConfigValueRequest {
	return {
		...{
			config: faker.string.alpha(),
			value: faker.string.alpha(),
			description: faker.string.alpha(),
			personalized: faker.datatype.boolean(),
		},
		...(data || {}),
	};
}
