/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {PermissionGroupApiEndPointResponse} from "../types/permission-group-api-end-point-response.ts";
import {createApiEndpointSummaryResponse} from "./create-api-endpoint-summary-response.ts";
import {createPermissionGroupAdminResponse} from "./create-permission-group-admin-response.ts";
import {createPermissionGroupResponse} from "./create-permission-group-response.ts";
import {faker} from "@faker-js/faker";

export function createPermissionGroupApiEndPointResponse(
	data?: Partial<PermissionGroupApiEndPointResponse>,
): PermissionGroupApiEndPointResponse {
	return {
		...{
			permissionGroup: createPermissionGroupResponse(),
			permissions: faker.helpers.multiple(() => createApiEndpointSummaryResponse()),
			permissionGroupAdmin: faker.helpers.multiple(() => createPermissionGroupAdminResponse()),
		},
		...(data || {}),
	};
}
