/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {MediaLibraryInsertRequest} from "../types/media-library-insert-request.ts";
import {createUpsertMediaFileRequest} from "./create-upsert-media-file-request.ts";
import {faker} from "@faker-js/faker";

export function createMediaLibraryInsertRequest(data?: Partial<MediaLibraryInsertRequest>): MediaLibraryInsertRequest {
	return {...{files: faker.helpers.multiple(() => createUpsertMediaFileRequest())}, ...(data || {})};
}
