/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AdminDetailResponse} from "../types/admin-detail-response.ts";
import {createPermissionGroupResponse} from "./create-permission-group-response.ts";
import {faker} from "@faker-js/faker";

export function createAdminDetailResponse(data?: Partial<AdminDetailResponse>): AdminDetailResponse {
	return {
		...{
			id: faker.number.int(),
			permissionGroup: createPermissionGroupResponse(),
			provider: faker.helpers.arrayElement<NonNullable<AdminDetailResponse>["provider"]>(["GOOGLE", "APPLE"]),
			loginId: faker.string.alpha(),
			name: faker.string.alpha(),
			otpSecretKey: faker.string.alpha(),
			removed: faker.datatype.boolean(),
			lockCount: faker.number.int(),
			lockedAt: faker.date.anytime().toISOString(),
			createdAt: faker.date.anytime().toISOString(),
			disabledAt: faker.date.anytime().toISOString(),
			lastLoginAt: faker.date.anytime().toISOString(),
			resetPasswordAt: faker.date.anytime().toISOString(),
			tenantId: faker.number.int(),
		},
		...(data || {}),
	};
}
