/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {PermissionGroupSaveRequest} from "../types/permission-group-save-request.ts";
import {faker} from "@faker-js/faker";

export function createPermissionGroupSaveRequest(data?: Partial<PermissionGroupSaveRequest>): PermissionGroupSaveRequest {
	return {...{id: faker.number.int(), name: faker.string.alpha({length: 1}), description: faker.string.alpha()}, ...(data || {})};
}
