/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ContentFolderSaveRequest} from "../types/content-folder-save-request.ts";
import {createContentFolderSaveNodeRequest} from "./create-content-folder-save-node-request.ts";
import {faker} from "@faker-js/faker";

export function createContentFolderSaveRequest(data?: Partial<ContentFolderSaveRequest>): ContentFolderSaveRequest {
	return {...{nodes: faker.helpers.multiple(() => createContentFolderSaveNodeRequest())}, ...(data || {})};
}
