/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {PlatformLoginRequest} from "../types/platform-login-request.ts";
import {faker} from "@faker-js/faker";

export function createPlatformLoginRequest(data?: Partial<PlatformLoginRequest>): PlatformLoginRequest {
	return {...{loginId: faker.string.alpha({length: 1}), password: faker.string.alpha({length: 1})}, ...(data || {})};
}
