/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OneListPermissionGroupResponse} from "../types/one-list-permission-group-response.ts";
import {createPermissionGroupResponse} from "./create-permission-group-response.ts";
import {faker} from "@faker-js/faker";

export function createOneListPermissionGroupResponse(data?: Partial<OneListPermissionGroupResponse>): OneListPermissionGroupResponse {
	return {...{list: faker.helpers.multiple(() => createPermissionGroupResponse())}, ...(data || {})};
}
