/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {UpsertMediaFileRequest} from "../types/upsert-media-file-request.ts";
import {faker} from "@faker-js/faker";

export function createUpsertMediaFileRequest(data?: Partial<UpsertMediaFileRequest>): UpsertMediaFileRequest {
	return {
		...{
			url: faker.string.alpha({length: 1}),
			path: faker.string.alpha({length: 1}),
			mimeType: faker.string.alpha({length: 1}),
			name: faker.string.alpha({length: 1}),
			size: faker.number.int({min: 1}),
			ext: faker.string.alpha(),
			provider: faker.helpers.arrayElement<NonNullable<UpsertMediaFileRequest>["provider"]>(["AWS", "GCP", "NCP", "LOCAL"]),
		},
		...(data || {}),
	};
}
