/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OneListUserActivityResponse} from "../types/one-list-user-activity-response.ts";
import {createUserActivityResponse} from "./create-user-activity-response.ts";
import {faker} from "@faker-js/faker";

export function createOneListUserActivityResponse(data?: Partial<OneListUserActivityResponse>): OneListUserActivityResponse {
	return {...{list: faker.helpers.multiple(() => createUserActivityResponse())}, ...(data || {})};
}
