/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ContentFolderSaveNodeRequest} from "../types/content-folder-save-node-request.ts";
import {faker} from "@faker-js/faker";

export function createContentFolderSaveNodeRequest(data?: Partial<ContentFolderSaveNodeRequest>): ContentFolderSaveNodeRequest {
	return {
		...{
			nodeType: faker.helpers.arrayElement<NonNullable<ContentFolderSaveNodeRequest>["nodeType"]>(["FOLDER", "TABLE"]),
			name: faker.string.alpha({length: 1}),
			tableName: faker.string.alpha(),
			displayed: faker.datatype.boolean(),
			children: faker.helpers.multiple(() => undefined as any),
		},
		...(data || {}),
	};
}
