/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {OnePageFilterResponse} from "../types/one-page-filter-response.ts";
import {createFilterResponse} from "./create-filter-response.ts";
import {faker} from "@faker-js/faker";

export function createOnePageFilterResponse(data?: Partial<OnePageFilterResponse>): OnePageFilterResponse {
	return {
		...{page: faker.number.int(), totalCount: faker.number.int(), list: faker.helpers.multiple(() => createFilterResponse())},
		...(data || {}),
	};
}
