/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ContentUpsertRequest} from "../types/content-upsert-request.ts";
import {createUpsertMediaColumnRequest} from "./create-upsert-media-column-request.ts";
import {faker} from "@faker-js/faker";

export function createContentUpsertRequest(data?: Partial<ContentUpsertRequest>): ContentUpsertRequest {
	return {...{body: {}, fileRequests: faker.helpers.multiple(() => createUpsertMediaColumnRequest())}, ...(data || {})};
}
