/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AdminUnlockRequest} from "../types/admin-unlock-request.ts";
import {faker} from "@faker-js/faker";

export function createAdminUnlockRequest(data?: Partial<AdminUnlockRequest>): AdminUnlockRequest {
	return {...{ids: faker.helpers.multiple(() => faker.number.int(), {count: 1})}, ...(data || {})};
}
