/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ContentTypeColumnResponse} from "../types/content-type-column-response.ts";
import {faker} from "@faker-js/faker";

export function createContentTypeColumnResponse(data?: Partial<ContentTypeColumnResponse>): ContentTypeColumnResponse {
	return {
		...{
			name: faker.string.alpha(),
			ordinalPosition: faker.number.int(),
			columnType: faker.string.alpha(),
			fieldType: faker.helpers.arrayElement<NonNullable<ContentTypeColumnResponse>["fieldType"]>([
				"TEXT",
				"BOOLEAN",
				"JSON",
				"NUMBER",
				"DATE",
				"ENUMERATION",
				"MEDIA",
				"RELATION",
			]),
			required: faker.datatype.boolean(),
			defaultValue: faker.string.alpha(),
			unique: faker.datatype.boolean(),
			privateField: faker.datatype.boolean(),
			regexpPattern: faker.string.alpha(),
			minLength: faker.number.int({min: 0, max: 255}),
			maxLength: faker.number.int({min: 0, max: 255}),
			minValue: faker.number.int({min: 0, max: 255}),
			maxValue: faker.number.int({min: 0, max: 255}),
			textType: faker.helpers.arrayElement<NonNullable<ContentTypeColumnResponse>["textType"]>(["SHORT_TEXT", "LONG_TEXT"]),
			numberType: faker.helpers.arrayElement<NonNullable<ContentTypeColumnResponse>["numberType"]>([
				"INTEGER",
				"BIG_INTEGER",
				"DECIMAL",
				"FLOAT",
			]),
			precision: faker.number.int({min: 0, max: 255}),
			scale: faker.number.int({min: 0, max: 255}),
			dateType: faker.helpers.arrayElement<NonNullable<ContentTypeColumnResponse>["dateType"]>(["DATE", "DATE_TIME", "TIME"]),
			enumValues: faker.helpers.multiple(() => faker.string.alpha()),
			relationType: faker.helpers.arrayElement<NonNullable<ContentTypeColumnResponse>["relationType"]>([
				"ONE_TO_ONE",
				"MANY_TO_ONE",
				"ONE_TO_MANY",
				"MANY_TO_MANY",
			]),
			relationTargetTable: faker.string.alpha(),
		},
		...(data || {}),
	};
}
