/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {TenantResponse} from "../types/tenant-response.ts";
import {faker} from "@faker-js/faker";

export function createTenantResponse(data?: Partial<TenantResponse>): TenantResponse {
	return {
		...{id: faker.number.int(), name: faker.string.alpha(), creatorId: faker.number.int(), createdAt: faker.date.anytime().toISOString()},
		...(data || {}),
	};
}
