/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {UpsertMediaColumnRequest} from "../types/upsert-media-column-request.ts";
import {createUpsertMediaFileRequest} from "./create-upsert-media-file-request.ts";
import {faker} from "@faker-js/faker";

export function createUpsertMediaColumnRequest(data?: Partial<UpsertMediaColumnRequest>): UpsertMediaColumnRequest {
	return {
		...{columnName: new RandExp("^[a-z_][a-z0-9_]{0,63}$").gen(), files: faker.helpers.multiple(() => createUpsertMediaFileRequest())},
		...(data || {}),
	};
}
