/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {PermissionGroupApiEndpointSaveRequest} from "../types/permission-group-api-endpoint-save-request.ts";
import {createApiEndpointSaveRequest} from "./create-api-endpoint-save-request.ts";
import {createPermissionGroupSaveRequest} from "./create-permission-group-save-request.ts";
import {faker} from "@faker-js/faker";

export function createPermissionGroupApiEndpointSaveRequest(
	data?: Partial<PermissionGroupApiEndpointSaveRequest>,
): PermissionGroupApiEndpointSaveRequest {
	return {
		...{
			permissionGroupRequest: createPermissionGroupSaveRequest(),
			apiEndpoints: faker.helpers.multiple(() => createApiEndpointSaveRequest()),
		},
		...(data || {}),
	};
}
