/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AdminSaveRequest} from "../types/admin-save-request.ts";
import {faker} from "@faker-js/faker";

export function createAdminSaveRequest(data?: Partial<AdminSaveRequest>): AdminSaveRequest {
	return {
		...{
			id: faker.number.int(),
			permissionGroupId: faker.number.int(),
			provider: faker.helpers.arrayElement<NonNullable<AdminSaveRequest>["provider"]>(["GOOGLE", "APPLE"]),
			loginId: faker.string.alpha({length: 1}),
			password: faker.string.alpha(),
			name: faker.string.alpha({length: 1}),
			tenantId: faker.number.int(),
		},
		...(data || {}),
	};
}
