/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {FilterResponse} from "../types/filter-response.ts";
import {createFilterItemOptionResponse} from "./create-filter-item-option-response.ts";
import {faker} from "@faker-js/faker";

export function createFilterResponse(data?: Partial<FilterResponse>): FilterResponse {
	return {
		...{
			id: faker.number.int(),
			table: faker.string.alpha(),
			field: faker.string.alpha(),
			label: faker.string.alpha(),
			dataType: faker.string.alpha(),
			operator: faker.string.alpha(),
			component: faker.string.alpha(),
			items: faker.helpers.multiple(() => createFilterItemOptionResponse()),
			creatorId: faker.number.int(),
			createdAt: faker.date.anytime().toISOString(),
			updatedAt: faker.date.anytime().toISOString(),
		},
		...(data || {}),
	};
}
