/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ContentTypeTableResponse} from "../types/content-type-table-response.ts";
import {createContentTypeColumnResponse} from "./create-content-type-column-response.ts";
import {faker} from "@faker-js/faker";

export function createContentTypeTableResponse(data?: Partial<ContentTypeTableResponse>): ContentTypeTableResponse {
	return {
		...{
			tableName: faker.string.alpha(),
			displayName: faker.string.alpha(),
			columns: faker.helpers.multiple(() => createContentTypeColumnResponse()),
		},
		...(data || {}),
	};
}
