/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {FilterSaveRequest} from "../types/filter-save-request.ts";
import {faker} from "@faker-js/faker";

export function createFilterSaveRequest(data?: Partial<FilterSaveRequest>): FilterSaveRequest {
	return {
		...{
			id: faker.number.int(),
			table: faker.string.alpha({length: 1}),
			field: faker.string.alpha({length: 1}),
			label: faker.string.alpha({length: 1}),
			dataType: faker.string.alpha({length: 1}),
			operator: faker.string.alpha({length: 1}),
			component: faker.string.alpha({length: 1}),
			items: faker.string.alpha(),
		},
		...(data || {}),
	};
}
