/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {FilterSearchFiltersQueryResponse, FilterSearchFiltersQueryParams} from "../../types/filter/filter-search-filters.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getFilterSearchFiltersUrl() {
	const res = {method: "GET", url: `/v1/filters` as const};
	return res;
}

/**
 * @description removed=false 필터 목록을 id desc 정렬로 페이징 조회 API
 * @summary v1 필터 목록 조회
 * {@link /v1/filters}
 */
export async function filterSearchFilters(
	params?: FilterSearchFiltersQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<FilterSearchFiltersQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getFilterSearchFiltersUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
