/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {FilterRemoveMutationResponse, FilterRemovePathParams} from "../../types/filter/filter-remove.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getFilterRemoveUrl(id: FilterRemovePathParams["id"]) {
	const res = {method: "DELETE", url: `/v1/filters/${id}` as const};
	return res;
}

/**
 * @description 필터 삭제 API(soft delete)
 * @summary v1 필터 삭제
 * {@link /v1/filters/:id}
 */
export async function filterRemove(id: FilterRemovePathParams["id"], config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<FilterRemoveMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "DELETE",
		url: getFilterRemoveUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
