/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {FilterUpsertMutationRequest, FilterUpsertMutationResponse} from "../../types/filter/filter-upsert.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getFilterUpsertUrl() {
	const res = {method: "POST", url: `/v1/filters` as const};
	return res;
}

/**
 * @description 필터 등록/수정 API
 * @summary v1 필터 등록/수정
 * {@link /v1/filters}
 */
export async function filterUpsert(
	data: FilterUpsertMutationRequest,
	config: Partial<RequestConfig<FilterUpsertMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<FilterUpsertMutationResponse, ResponseErrorConfig<Error>, FilterUpsertMutationRequest>({
		method: "POST",
		url: getFilterUpsertUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
