/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	MediaLibraryUpsert200,
	MediaLibraryUpsertMutationRequest,
	MediaLibraryUpsertMutationResponse,
} from "../../types/media-library/media-library-upsert.ts";
import {createMediaLibraryInsertRequest} from "../create-media-library-insert-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createMediaLibraryUpsert200(data?: Partial<MediaLibraryUpsert200>): MediaLibraryUpsert200 {
	return createUnitResult(data);
}

export function createMediaLibraryUpsertMutationRequest(
	data?: Partial<MediaLibraryUpsertMutationRequest>,
): MediaLibraryUpsertMutationRequest {
	return createMediaLibraryInsertRequest(data);
}

export function createMediaLibraryUpsertMutationResponse(
	data?: Partial<MediaLibraryUpsertMutationResponse>,
): MediaLibraryUpsertMutationResponse {
	return data || faker.helpers.arrayElement<any>([createMediaLibraryUpsert200()]);
}
