/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	MediaLibrarySearchMediaLibraryQueryParams,
	MediaLibrarySearchMediaLibrary200,
	MediaLibrarySearchMediaLibraryQueryResponse,
} from "../../types/media-library/media-library-search-media-library.ts";
import {createApiResultOnePageMapStringObject} from "../create-api-result-one-page-map-string-object.ts";
import {faker} from "@faker-js/faker";

export function createMediaLibrarySearchMediaLibraryQueryParams(
	data?: Partial<MediaLibrarySearchMediaLibraryQueryParams>,
): MediaLibrarySearchMediaLibraryQueryParams {
	return {
		...{
			includePrivate: faker.datatype.boolean(),
			field: faker.helpers.multiple(() => faker.string.alpha()),
			operator: faker.helpers.multiple(() => faker.string.alpha()),
			value: faker.helpers.multiple(() => faker.string.alpha()),
			page: faker.number.int(),
			size: faker.number.int(),
		},
		...(data || {}),
	};
}

/**
 * @description OK
 */
export function createMediaLibrarySearchMediaLibrary200(
	data?: Partial<MediaLibrarySearchMediaLibrary200>,
): MediaLibrarySearchMediaLibrary200 {
	return createApiResultOnePageMapStringObject(data);
}

export function createMediaLibrarySearchMediaLibraryQueryResponse(
	data?: Partial<MediaLibrarySearchMediaLibraryQueryResponse>,
): MediaLibrarySearchMediaLibraryQueryResponse {
	return data || faker.helpers.arrayElement<any>([createMediaLibrarySearchMediaLibrary200()]);
}
