/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	MediaLibraryRemovePathParams,
	MediaLibraryRemove200,
	MediaLibraryRemoveMutationResponse,
} from "../../types/media-library/media-library-remove.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createMediaLibraryRemovePathParams(data?: Partial<MediaLibraryRemovePathParams>): MediaLibraryRemovePathParams {
	return {...{id: faker.number.int()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createMediaLibraryRemove200(data?: Partial<MediaLibraryRemove200>): MediaLibraryRemove200 {
	return createUnitResult(data);
}

export function createMediaLibraryRemoveMutationResponse(
	data?: Partial<MediaLibraryRemoveMutationResponse>,
): MediaLibraryRemoveMutationResponse {
	return data || faker.helpers.arrayElement<any>([createMediaLibraryRemove200()]);
}
