/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {FilterSaveRequest} from "../filter-save-request.ts";
import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type FilterUpsert200 = UnitResult;

export type FilterUpsertMutationRequest = FilterSaveRequest;

export type FilterUpsertMutationResponse = FilterUpsert200;

export type FilterUpsertMutation = {Response: FilterUpsert200; Request: FilterUpsertMutationRequest; Errors: any};
