/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOnePageFilterResponse} from "../api-result-one-page-filter-response.ts";

export type FilterSearchFiltersQueryParams = {
	/**
	 * @description 테이블명
	 * @type string | undefined
	 */
	table?: string;
	/**
	 * @description 컬럼명
	 * @type string | undefined
	 */
	field?: string;
	/**
	 * @type integer | undefined, int32
	 */
	page?: number;
	/**
	 * @type integer | undefined, int32
	 */
	size?: number;
};

/**
 * @description OK
 */
export type FilterSearchFilters200 = ApiResultOnePageFilterResponse;

export type FilterSearchFiltersQueryResponse = FilterSearchFilters200;

export type FilterSearchFiltersQuery = {Response: FilterSearchFilters200; QueryParams: FilterSearchFiltersQueryParams; Errors: any};
