/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	HomeDashboardGetUserActivities200,
	HomeDashboardGetUserActivitiesQueryResponse,
} from "../../types/home-dashboard/home-dashboard-get-user-activities.ts";
import {createApiResultOneListUserActivityResponse} from "../create-api-result-one-list-user-activity-response.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createHomeDashboardGetUserActivities200(
	data?: Partial<HomeDashboardGetUserActivities200>,
): HomeDashboardGetUserActivities200 {
	return createApiResultOneListUserActivityResponse(data);
}

export function createHomeDashboardGetUserActivitiesQueryResponse(
	data?: Partial<HomeDashboardGetUserActivitiesQueryResponse>,
): HomeDashboardGetUserActivitiesQueryResponse {
	return data || faker.helpers.arrayElement<any>([createHomeDashboardGetUserActivities200()]);
}
