/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	HomeDashboardGetBuildNotes200,
	HomeDashboardGetBuildNotesQueryResponse,
} from "../../types/home-dashboard/home-dashboard-get-build-notes.ts";
import {createApiResultOneListBoardPageResponse} from "../create-api-result-one-list-board-page-response.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createHomeDashboardGetBuildNotes200(data?: Partial<HomeDashboardGetBuildNotes200>): HomeDashboardGetBuildNotes200 {
	return createApiResultOneListBoardPageResponse(data);
}

export function createHomeDashboardGetBuildNotesQueryResponse(
	data?: Partial<HomeDashboardGetBuildNotesQueryResponse>,
): HomeDashboardGetBuildNotesQueryResponse {
	return data || faker.helpers.arrayElement<any>([createHomeDashboardGetBuildNotes200()]);
}
