/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ContentFolderSave200,
	ContentFolderSaveMutationRequest,
	ContentFolderSaveMutationResponse,
} from "../../types/content-folder/content-folder-save.ts";
import {createContentFolderSaveRequest} from "../create-content-folder-save-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createContentFolderSave200(data?: Partial<ContentFolderSave200>): ContentFolderSave200 {
	return createUnitResult(data);
}

export function createContentFolderSaveMutationRequest(data?: Partial<ContentFolderSaveMutationRequest>): ContentFolderSaveMutationRequest {
	return createContentFolderSaveRequest(data);
}

export function createContentFolderSaveMutationResponse(
	data?: Partial<ContentFolderSaveMutationResponse>,
): ContentFolderSaveMutationResponse {
	return data || faker.helpers.arrayElement<any>([createContentFolderSave200()]);
}
