/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {ContentFolderGetList200, ContentFolderGetListQueryResponse} from "../../types/content-folder/content-folder-get-list.ts";
import {createApiResultOneListContentFolderNodeResponse} from "../create-api-result-one-list-content-folder-node-response.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createContentFolderGetList200(data?: Partial<ContentFolderGetList200>): ContentFolderGetList200 {
	return createApiResultOneListContentFolderNodeResponse(data);
}

export function createContentFolderGetListQueryResponse(
	data?: Partial<ContentFolderGetListQueryResponse>,
): ContentFolderGetListQueryResponse {
	return data || faker.helpers.arrayElement<any>([createContentFolderGetList200()]);
}
