/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AuditLogSearchAuditLogsQueryResponse,
	AuditLogSearchAuditLogsQueryParams,
} from "../../types/audit-log/audit-log-search-audit-logs.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {auditLogSearchAuditLogs} from "../../clients/audit-log/audit-log-search-audit-logs.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const auditLogSearchAuditLogsQueryKey = (params: AuditLogSearchAuditLogsQueryParams = {}) =>
	[{url: "/v1/audit-logs"}, ...(params ? [params] : [])] as const;

export type AuditLogSearchAuditLogsQueryKey = ReturnType<typeof auditLogSearchAuditLogsQueryKey>;

export function auditLogSearchAuditLogsQueryOptions(
	params?: AuditLogSearchAuditLogsQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = auditLogSearchAuditLogsQueryKey(params);
	return queryOptions<
		AuditLogSearchAuditLogsQueryResponse,
		ResponseErrorConfig<Error>,
		AuditLogSearchAuditLogsQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return auditLogSearchAuditLogs(params, config);
		},
	});
}

/**
 * @description 감사 로그 목록 페이징 조회 API
 * @summary v1 감사 로그 목록 조회
 * {@link /v1/audit-logs}
 */
export function useAuditLogSearchAuditLogs<
	TData = AuditLogSearchAuditLogsQueryResponse,
	TQueryData = AuditLogSearchAuditLogsQueryResponse,
	TQueryKey extends QueryKey = AuditLogSearchAuditLogsQueryKey,
>(
	params?: AuditLogSearchAuditLogsQueryParams,
	options: {
		query?: Partial<
			QueryObserverOptions<AuditLogSearchAuditLogsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? auditLogSearchAuditLogsQueryKey(params);

	const query = useQuery(
		{...auditLogSearchAuditLogsQueryOptions(params, config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
