/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AuditLogSearchAuditLogsQueryResponse,
	AuditLogSearchAuditLogsQueryParams,
} from "../../types/audit-log/audit-log-search-audit-logs.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {auditLogSearchAuditLogs} from "../../clients/audit-log/audit-log-search-audit-logs.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const auditLogSearchAuditLogsSuspenseQueryKey = (params: AuditLogSearchAuditLogsQueryParams = {}) =>
	[{url: "/v1/audit-logs"}, ...(params ? [params] : [])] as const;

export type AuditLogSearchAuditLogsSuspenseQueryKey = ReturnType<typeof auditLogSearchAuditLogsSuspenseQueryKey>;

export function auditLogSearchAuditLogsSuspenseQueryOptions(
	params?: AuditLogSearchAuditLogsQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = auditLogSearchAuditLogsSuspenseQueryKey(params);
	return queryOptions<
		AuditLogSearchAuditLogsQueryResponse,
		ResponseErrorConfig<Error>,
		AuditLogSearchAuditLogsQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return auditLogSearchAuditLogs(params, config);
		},
	});
}

/**
 * @description 감사 로그 목록 페이징 조회 API
 * @summary v1 감사 로그 목록 조회
 * {@link /v1/audit-logs}
 */
export function useAuditLogSearchAuditLogsSuspense<
	TData = AuditLogSearchAuditLogsQueryResponse,
	TQueryKey extends QueryKey = AuditLogSearchAuditLogsSuspenseQueryKey,
>(
	params?: AuditLogSearchAuditLogsQueryParams,
	options: {
		query?: Partial<UseSuspenseQueryOptions<AuditLogSearchAuditLogsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? auditLogSearchAuditLogsSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{...auditLogSearchAuditLogsSuspenseQueryOptions(params, config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
