/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOnePageTenantResponse} from "../api-result-one-page-tenant-response.ts";

export type TenantSearchTenantsQueryParams = {
	/**
	 * @type integer | undefined, int32
	 */
	page?: number;
	/**
	 * @type integer | undefined, int32
	 */
	size?: number;
};

/**
 * @description OK
 */
export type TenantSearchTenants200 = ApiResultOnePageTenantResponse;

export type TenantSearchTenantsQueryResponse = TenantSearchTenants200;

export type TenantSearchTenantsQuery = {Response: TenantSearchTenants200; QueryParams: TenantSearchTenantsQueryParams; Errors: any};
