/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UnitResult} from "../unit-result.ts";

export type TenantRemovePathParams = {
	/**
	 * @description 테넌트 아이디
	 * @type integer, int64
	 */
	id: number;
};

/**
 * @description OK
 */
export type TenantRemove200 = UnitResult;

export type TenantRemoveMutationResponse = TenantRemove200;

export type TenantRemoveMutation = {Response: TenantRemove200; PathParams: TenantRemovePathParams; Errors: any};
