/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {TenantSaveRequest} from "../tenant-save-request.ts";
import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type TenantUpsert200 = UnitResult;

export type TenantUpsertMutationRequest = TenantSaveRequest;

export type TenantUpsertMutationResponse = TenantUpsert200;

export type TenantUpsertMutation = {Response: TenantUpsert200; Request: TenantUpsertMutationRequest; Errors: any};
