/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

/**
 * @description OK
 */
export type IndexRoot200 = {[key: string]: string};

export type IndexRootQueryResponse = IndexRoot200;

export type IndexRootQuery = {Response: IndexRoot200; Errors: any};
