/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {adminGetItem} from "./admin-get-item.ts";
import {adminIsLoginIdDuplicate} from "./admin-is-login-id-duplicate.ts";
import {adminRemoveAdmins} from "./admin-remove-admins.ts";
import {adminSearchAdmins} from "./admin-search-admins.ts";
import {adminUnlockAdmins} from "./admin-unlock-admins.ts";
import {adminUpdates} from "./admin-updates.ts";
import {adminUpsert} from "./admin-upsert.ts";

export function admin() {
	return {adminSearchAdmins, adminUpsert, adminRemoveAdmins, adminUnlockAdmins, adminUpdates, adminGetItem, adminIsLoginIdDuplicate};
}
