/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {AdminRemoveAdminsMutationResponse, AdminRemoveAdminsQueryParams} from "../../types/admin/admin-remove-admins.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAdminRemoveAdminsUrl() {
	const res = {method: "DELETE", url: `/v1/admins` as const};
	return res;
}

/**
 * @description 관리자 삭제 API
 * @summary v1 관리자 삭제
 * {@link /v1/admins}
 */
export async function adminRemoveAdmins(params: AdminRemoveAdminsQueryParams, config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<AdminRemoveAdminsMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "DELETE",
		url: getAdminRemoveAdminsUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
