/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	AdminIsLoginIdDuplicateQueryResponse,
	AdminIsLoginIdDuplicateQueryParams,
} from "../../types/admin/admin-is-login-id-duplicate.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAdminIsLoginIdDuplicateUrl() {
	const res = {method: "GET", url: `/v1/admins/is-duplicate-login-id` as const};
	return res;
}

/**
 * @description 관리자 로그인 아이디 중복 확인 API
 * @summary v1 관리자 로그인 아이디 중복 확인
 * {@link /v1/admins/is-duplicate-login-id}
 */
export async function adminIsLoginIdDuplicate(
	params: AdminIsLoginIdDuplicateQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<AdminIsLoginIdDuplicateQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getAdminIsLoginIdDuplicateUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
