/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {AdminSearchAdminsQueryResponse, AdminSearchAdminsQueryParams} from "../../types/admin/admin-search-admins.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAdminSearchAdminsUrl() {
	const res = {method: "GET", url: `/v1/admins` as const};
	return res;
}

/**
 * @description 관리자 목록 조회 API
 * @summary v1 관리자 목록 조회
 * {@link /v1/admins}
 */
export async function adminSearchAdmins(params?: AdminSearchAdminsQueryParams, config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<AdminSearchAdminsQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getAdminSearchAdminsUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
