/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {AdminGetItemQueryResponse, AdminGetItemPathParams} from "../../types/admin/admin-get-item.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAdminGetItemUrl(id: AdminGetItemPathParams["id"]) {
	const res = {method: "GET", url: `/v1/admins/${id}` as const};
	return res;
}

/**
 * @description 관리자 상세 조회 API
 * @summary v1 관리자 상세 조회
 * {@link /v1/admins/:id}
 */
export async function adminGetItem(id: AdminGetItemPathParams["id"], config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<AdminGetItemQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getAdminGetItemUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
