/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {AdminUpsertMutationRequest, AdminUpsertMutationResponse} from "../../types/admin/admin-upsert.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAdminUpsertUrl() {
	const res = {method: "POST", url: `/v1/admins` as const};
	return res;
}

/**
 * @description 관리자 등록/수정 API
 * @summary v1 관리자 등록/수정
 * {@link /v1/admins}
 */
export async function adminUpsert(
	data: AdminUpsertMutationRequest,
	config: Partial<RequestConfig<AdminUpsertMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<AdminUpsertMutationResponse, ResponseErrorConfig<Error>, AdminUpsertMutationRequest>({
		method: "POST",
		url: getAdminUpsertUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
