/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {AdminUpdatesMutationRequest, AdminUpdatesMutationResponse} from "../../types/admin/admin-updates.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAdminUpdatesUrl() {
	const res = {method: "POST", url: `/v1/admins/modify/permission-groups` as const};
	return res;
}

/**
 * @description 관리자 권한 그룹 일괄 수정 API
 * @summary v1 관리자 권한 그룹 일괄 수정
 * {@link /v1/admins/modify/permission-groups}
 */
export async function adminUpdates(
	data: AdminUpdatesMutationRequest,
	config: Partial<RequestConfig<AdminUpdatesMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<AdminUpdatesMutationResponse, ResponseErrorConfig<Error>, AdminUpdatesMutationRequest>({
		method: "POST",
		url: getAdminUpdatesUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
