/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {AdminUnlockAdminsMutationRequest, AdminUnlockAdminsMutationResponse} from "../../types/admin/admin-unlock-admins.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAdminUnlockAdminsUrl() {
	const res = {method: "POST", url: `/v1/admins/unlock` as const};
	return res;
}

/**
 * @description 관리자 잠금 해제 API
 * @summary v1 관리자 잠금 해제
 * {@link /v1/admins/unlock}
 */
export async function adminUnlockAdmins(
	data: AdminUnlockAdminsMutationRequest,
	config: Partial<RequestConfig<AdminUnlockAdminsMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<AdminUnlockAdminsMutationResponse, ResponseErrorConfig<Error>, AdminUnlockAdminsMutationRequest>({
		method: "POST",
		url: getAdminUnlockAdminsUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
