/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UnitResult} from "../unit-result.ts";

export type PermissionGroupRemovePathParams = {
	/**
	 * @description 권한 그룹 아이디
	 * @type integer, int64
	 */
	permissionGroupId: number;
};

/**
 * @description OK
 */
export type PermissionGroupRemove200 = UnitResult;

export type PermissionGroupRemoveMutationResponse = PermissionGroupRemove200;

export type PermissionGroupRemoveMutation = {Response: PermissionGroupRemove200; PathParams: PermissionGroupRemovePathParams; Errors: any};
