/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultPermissionGroupApiEndPointResponse} from "../api-result-permission-group-api-end-point-response.ts";

export type PermissionGroupGetItemPathParams = {
	/**
	 * @description 권한 그룹 아이디
	 * @type integer, int64
	 */
	permissionGroupId: number;
};

/**
 * @description OK
 */
export type PermissionGroupGetItem200 = ApiResultPermissionGroupApiEndPointResponse;

export type PermissionGroupGetItemQueryResponse = PermissionGroupGetItem200;

export type PermissionGroupGetItemQuery = {Response: PermissionGroupGetItem200; PathParams: PermissionGroupGetItemPathParams; Errors: any};
