/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOneListApiEndpointResponse} from "../api-result-one-list-api-endpoint-response.ts";

/**
 * @description OK
 */
export type PermissionGroupGetApiEndpointList200 = ApiResultOneListApiEndpointResponse;

export type PermissionGroupGetApiEndpointListQueryResponse = PermissionGroupGetApiEndpointList200;

export type PermissionGroupGetApiEndpointListQuery = {Response: PermissionGroupGetApiEndpointList200; Errors: any};
