/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOneListPermissionGroupResponse} from "../api-result-one-list-permission-group-response.ts";

/**
 * @description OK
 */
export type PermissionGroupGetList200 = ApiResultOneListPermissionGroupResponse;

export type PermissionGroupGetListQueryResponse = PermissionGroupGetList200;

export type PermissionGroupGetListQuery = {Response: PermissionGroupGetList200; Errors: any};
