/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {PermissionGroupApiEndpointSaveRequest} from "../permission-group-api-endpoint-save-request.ts";
import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type PermissionGroupUpsert200 = UnitResult;

export type PermissionGroupUpsertMutationRequest = PermissionGroupApiEndpointSaveRequest;

export type PermissionGroupUpsertMutationResponse = PermissionGroupUpsert200;

export type PermissionGroupUpsertMutation = {
	Response: PermissionGroupUpsert200;
	Request: PermissionGroupUpsertMutationRequest;
	Errors: any;
};
