/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {CacheFlushAllRedisCacheMutationResponse} from "../../types/cache/cache-flush-all-redis-cache.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {cacheFlushAllRedisCache} from "../../clients/cache/cache-flush-all-redis-cache.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const cacheFlushAllRedisCacheMutationKey = () => [{url: "/v1/cache/flush-all"}] as const;

export type CacheFlushAllRedisCacheMutationKey = ReturnType<typeof cacheFlushAllRedisCacheMutationKey>;

export function cacheFlushAllRedisCacheMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = cacheFlushAllRedisCacheMutationKey();
	return mutationOptions<CacheFlushAllRedisCacheMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
		mutationKey,
		mutationFn: async () => {
			return cacheFlushAllRedisCache(config);
		},
	});
}

/**
 * @description Redis 캐시 전체 삭제 API
 * @summary v1 Redis 캐시 전체 삭제
 * {@link /v1/cache/flush-all}
 */
export function useCacheFlushAllRedisCache<TContext>(
	options: {
		mutation?: UseMutationOptions<CacheFlushAllRedisCacheMutationResponse, ResponseErrorConfig<Error>, void, TContext> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? cacheFlushAllRedisCacheMutationKey();

	const baseOptions = cacheFlushAllRedisCacheMutationOptions(config) as UseMutationOptions<
		CacheFlushAllRedisCacheMutationResponse,
		ResponseErrorConfig<Error>,
		void,
		TContext
	>;

	return useMutation<CacheFlushAllRedisCacheMutationResponse, ResponseErrorConfig<Error>, void, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<CacheFlushAllRedisCacheMutationResponse, ResponseErrorConfig<Error>, void, TContext>;
}
