/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	ContentTypeGetTableListQueryResponse,
	ContentTypeGetTableListQueryParams,
} from "../../types/content-type/content-type-get-table-list.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getContentTypeGetTableListUrl() {
	const res = {method: "GET", url: `/v1/content-type/tables` as const};
	return res;
}

/**
 * @description 권한이 있는 테이블 목록 조회 API
 * @summary v1 테이블 목록 조회
 * {@link /v1/content-type/tables}
 */
export async function contentTypeGetTableList(
	params?: ContentTypeGetTableListQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<ContentTypeGetTableListQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getContentTypeGetTableListUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
