/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {AuthorizationInfoQueryResponse} from "../../types/authorization/authorization-info.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAuthorizationInfoUrl() {
	const res = {method: "GET", url: `/v1/cms/auth/info` as const};
	return res;
}

/**
 * @description 로그인 정보 조회 API
 * @summary v1 로그인 정보 조회
 * {@link /v1/cms/auth/info}
 */
export async function authorizationInfo(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<AuthorizationInfoQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getAuthorizationInfoUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
