/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {AuthorizationLoginMutationRequest, AuthorizationLoginMutationResponse} from "../../types/authorization/authorization-login.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAuthorizationLoginUrl() {
	const res = {method: "POST", url: `/v1/cms/auth/login` as const};
	return res;
}

/**
 * @description 로그인 API
 * @summary v1 로그인
 * {@link /v1/cms/auth/login}
 */
export async function authorizationLogin(
	data: AuthorizationLoginMutationRequest,
	config: Partial<RequestConfig<AuthorizationLoginMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<AuthorizationLoginMutationResponse, ResponseErrorConfig<Error>, AuthorizationLoginMutationRequest>({
		method: "POST",
		url: getAuthorizationLoginUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
