/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	AuthorizationRefreshTokenMutationRequest,
	AuthorizationRefreshTokenMutationResponse,
} from "../../types/authorization/authorization-refresh-token.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAuthorizationRefreshTokenUrl() {
	const res = {method: "POST", url: `/v1/cms/auth/refresh` as const};
	return res;
}

/**
 * @description accessToken 갱신 API
 * @summary v1 accessToken 갱신
 * {@link /v1/cms/auth/refresh}
 */
export async function authorizationRefreshToken(
	data: AuthorizationRefreshTokenMutationRequest,
	config: Partial<RequestConfig<AuthorizationRefreshTokenMutationRequest>> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const requestData = data;

	const res = await request<
		AuthorizationRefreshTokenMutationResponse,
		ResponseErrorConfig<Error>,
		AuthorizationRefreshTokenMutationRequest
	>({method: "POST", url: getAuthorizationRefreshTokenUrl().url.toString(), data: requestData, ...requestConfig});
	return res.data;
}
