/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import {authorizationInfo} from "./authorization-info.ts";
import {authorizationLoginGoogle} from "./authorization-login-google.ts";
import {authorizationLogin} from "./authorization-login.ts";
import {authorizationLogout} from "./authorization-logout.ts";
import {authorizationRefreshToken} from "./authorization-refresh-token.ts";
import {authorizationVerifyOtp} from "./authorization-verify-otp.ts";

export function authorization() {
	return {
		authorizationVerifyOtp,
		authorizationLoginGoogle,
		authorizationRefreshToken,
		authorizationLogout,
		authorizationLogin,
		authorizationInfo,
	};
}
