/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	AuthorizationVerifyOtpMutationResponse,
	AuthorizationVerifyOtpQueryParams,
} from "../../types/authorization/authorization-verify-otp.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAuthorizationVerifyOtpUrl() {
	const res = {method: "POST", url: `/v1/cms/auth/verify-otp` as const};
	return res;
}

/**
 * @description OTP 검증 API
 * @summary v1 OTP 검증
 * {@link /v1/cms/auth/verify-otp}
 */
export async function authorizationVerifyOtp(
	params: AuthorizationVerifyOtpQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<AuthorizationVerifyOtpMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "POST",
		url: getAuthorizationVerifyOtpUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
