/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {AuthorizationLogoutMutationResponse, AuthorizationLogoutQueryParams} from "../../types/authorization/authorization-logout.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAuthorizationLogoutUrl() {
	const res = {method: "POST", url: `/v1/cms/auth/logout` as const};
	return res;
}

/**
 * @description 로그아웃 API
 * @summary v1 로그아웃
 * {@link /v1/cms/auth/logout}
 */
export async function authorizationLogout(params: AuthorizationLogoutQueryParams, config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<AuthorizationLogoutMutationResponse, ResponseErrorConfig<Error>, unknown>({
		method: "POST",
		url: getAuthorizationLogoutUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
