/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AuthorizationVerifyOtpQueryParams,
	AuthorizationVerifyOtp200,
	AuthorizationVerifyOtpMutationResponse,
} from "../../types/authorization/authorization-verify-otp.ts";
import {createApiResultTokenInfoResponse} from "../create-api-result-token-info-response.ts";
import {faker} from "@faker-js/faker";

export function createAuthorizationVerifyOtpQueryParams(
	data?: Partial<AuthorizationVerifyOtpQueryParams>,
): AuthorizationVerifyOtpQueryParams {
	return {...{otp: faker.number.int()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createAuthorizationVerifyOtp200(data?: Partial<AuthorizationVerifyOtp200>): AuthorizationVerifyOtp200 {
	return createApiResultTokenInfoResponse(data);
}

export function createAuthorizationVerifyOtpMutationResponse(
	data?: Partial<AuthorizationVerifyOtpMutationResponse>,
): AuthorizationVerifyOtpMutationResponse {
	return data || faker.helpers.arrayElement<any>([createAuthorizationVerifyOtp200()]);
}
