/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AuthorizationLogoutQueryParams,
	AuthorizationLogout200,
	AuthorizationLogoutMutationResponse,
} from "../../types/authorization/authorization-logout.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createAuthorizationLogoutQueryParams(data?: Partial<AuthorizationLogoutQueryParams>): AuthorizationLogoutQueryParams {
	return {...{refreshToken: faker.string.alpha()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createAuthorizationLogout200(data?: Partial<AuthorizationLogout200>): AuthorizationLogout200 {
	return createUnitResult(data);
}

export function createAuthorizationLogoutMutationResponse(
	data?: Partial<AuthorizationLogoutMutationResponse>,
): AuthorizationLogoutMutationResponse {
	return data || faker.helpers.arrayElement<any>([createAuthorizationLogout200()]);
}
