/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {AuthorizationInfo200, AuthorizationInfoQueryResponse} from "../../types/authorization/authorization-info.ts";
import {createApiResultAdminDetailResponse} from "../create-api-result-admin-detail-response.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createAuthorizationInfo200(data?: Partial<AuthorizationInfo200>): AuthorizationInfo200 {
	return createApiResultAdminDetailResponse(data);
}

export function createAuthorizationInfoQueryResponse(data?: Partial<AuthorizationInfoQueryResponse>): AuthorizationInfoQueryResponse {
	return data || faker.helpers.arrayElement<any>([createAuthorizationInfo200()]);
}
