/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AuthorizationLoginGoogle200,
	AuthorizationLoginGoogleMutationRequest,
	AuthorizationLoginGoogleMutationResponse,
} from "../../types/authorization/authorization-login-google.ts";
import {createApiResultLoginResponse} from "../create-api-result-login-response.ts";
import {createLoginRequest} from "../create-login-request.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createAuthorizationLoginGoogle200(data?: Partial<AuthorizationLoginGoogle200>): AuthorizationLoginGoogle200 {
	return createApiResultLoginResponse(data);
}

export function createAuthorizationLoginGoogleMutationRequest(
	data?: Partial<AuthorizationLoginGoogleMutationRequest>,
): AuthorizationLoginGoogleMutationRequest {
	return createLoginRequest(data);
}

export function createAuthorizationLoginGoogleMutationResponse(
	data?: Partial<AuthorizationLoginGoogleMutationResponse>,
): AuthorizationLoginGoogleMutationResponse {
	return data || faker.helpers.arrayElement<any>([createAuthorizationLoginGoogle200()]);
}
