/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AuthorizationLogin200,
	AuthorizationLoginMutationRequest,
	AuthorizationLoginMutationResponse,
} from "../../types/authorization/authorization-login.ts";
import {createApiResultLoginResponse} from "../create-api-result-login-response.ts";
import {createPlatformLoginRequest} from "../create-platform-login-request.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createAuthorizationLogin200(data?: Partial<AuthorizationLogin200>): AuthorizationLogin200 {
	return createApiResultLoginResponse(data);
}

export function createAuthorizationLoginMutationRequest(
	data?: Partial<AuthorizationLoginMutationRequest>,
): AuthorizationLoginMutationRequest {
	return createPlatformLoginRequest(data);
}

export function createAuthorizationLoginMutationResponse(
	data?: Partial<AuthorizationLoginMutationResponse>,
): AuthorizationLoginMutationResponse {
	return data || faker.helpers.arrayElement<any>([createAuthorizationLogin200()]);
}
