/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	AuthorizationRefreshToken200,
	AuthorizationRefreshTokenMutationRequest,
	AuthorizationRefreshTokenMutationResponse,
} from "../../types/authorization/authorization-refresh-token.ts";
import {createApiResultTokenInfoResponse} from "../create-api-result-token-info-response.ts";
import {createRefreshTokenRequest} from "../create-refresh-token-request.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createAuthorizationRefreshToken200(data?: Partial<AuthorizationRefreshToken200>): AuthorizationRefreshToken200 {
	return createApiResultTokenInfoResponse(data);
}

export function createAuthorizationRefreshTokenMutationRequest(
	data?: Partial<AuthorizationRefreshTokenMutationRequest>,
): AuthorizationRefreshTokenMutationRequest {
	return createRefreshTokenRequest(data);
}

export function createAuthorizationRefreshTokenMutationResponse(
	data?: Partial<AuthorizationRefreshTokenMutationResponse>,
): AuthorizationRefreshTokenMutationResponse {
	return data || faker.helpers.arrayElement<any>([createAuthorizationRefreshToken200()]);
}
