/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {IndexRoot200, IndexRootQueryResponse} from "../../types/index-controller/index-root.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createIndexRoot200(data?: Partial<IndexRoot200>): IndexRoot200 {
	return {...{}, ...(data || {})};
}

export function createIndexRootQueryResponse(data?: Partial<IndexRootQueryResponse>): IndexRootQueryResponse {
	return data || faker.helpers.arrayElement<any>([createIndexRoot200()]);
}
