/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOneListContentTypeTableResponse} from "../api-result-one-list-content-type-table-response.ts";

export type ContentTypeGetTableListQueryParams = {
	/**
	 * @description 시스템 컬럼 포함 여부
	 * @default false
	 * @type boolean | undefined
	 */
	includeSystemColumns?: boolean;
	/**
	 * @description private 필드 포함 여부
	 * @default false
	 * @type boolean | undefined
	 */
	includePrivateFields?: boolean;
};

/**
 * @description OK
 */
export type ContentTypeGetTableList200 = ApiResultOneListContentTypeTableResponse;

export type ContentTypeGetTableListQueryResponse = ContentTypeGetTableList200;

export type ContentTypeGetTableListQuery = {
	Response: ContentTypeGetTableList200;
	QueryParams: ContentTypeGetTableListQueryParams;
	Errors: any;
};
