/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOneListContentTypeColumnResponse} from "../api-result-one-list-content-type-column-response.ts";

export type ContentManagerGetTableInfoQueryParams = {
	/**
	 * @type string
	 */
	tableName: string;
	/**
	 * @default false
	 * @type boolean | undefined
	 */
	includeSystemColumns?: boolean;
	/**
	 * @default false
	 * @type boolean | undefined
	 */
	includePrivate?: boolean;
};

/**
 * @description OK
 */
export type ContentManagerGetTableInfo200 = ApiResultOneListContentTypeColumnResponse;

export type ContentManagerGetTableInfoQueryResponse = ContentManagerGetTableInfo200;

export type ContentManagerGetTableInfoQuery = {
	Response: ContentManagerGetTableInfo200;
	QueryParams: ContentManagerGetTableInfoQueryParams;
	Errors: any;
};
