/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ContentUpsertRequest} from "../content-upsert-request.ts";
import type {UnitResult} from "../unit-result.ts";

export type ContentManagerUpsertQueryParams = {
	/**
	 * @type string
	 */
	tableName: string;
	/**
	 * @default false
	 * @type boolean | undefined
	 */
	includePrivate?: boolean;
};

/**
 * @description OK
 */
export type ContentManagerUpsert200 = UnitResult;

export type ContentManagerUpsertMutationRequest = ContentUpsertRequest;

export type ContentManagerUpsertMutationResponse = ContentManagerUpsert200;

export type ContentManagerUpsertMutation = {
	Response: ContentManagerUpsert200;
	Request: ContentManagerUpsertMutationRequest;
	QueryParams: ContentManagerUpsertQueryParams;
	Errors: any;
};
