/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UnitResult} from "../unit-result.ts";

export type ContentManagerRemovesQueryParams = {
	/**
	 * @type string
	 */
	tableName: string;
	/**
	 * @description 컨텐츠 아이디 목록
	 * @type array
	 */
	ids: number[];
};

/**
 * @description OK
 */
export type ContentManagerRemoves200 = UnitResult;

export type ContentManagerRemovesMutationResponse = ContentManagerRemoves200;

export type ContentManagerRemovesMutation = {
	Response: ContentManagerRemoves200;
	QueryParams: ContentManagerRemovesQueryParams;
	Errors: any;
};
