/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOnePageMapStringObject} from "../api-result-one-page-map-string-object.ts";

export type ContentManagerSearchContentsQueryParams = {
	/**
	 * @description 테이블 명
	 * @type string
	 */
	tableName: string;
	/**
	 * @description private 필드 포함 여부
	 * @default false
	 * @type boolean | undefined
	 */
	includePrivate?: boolean;
	/**
	 * @type integer | undefined, int32
	 */
	page?: number;
	/**
	 * @type integer | undefined, int32
	 */
	size?: number;
};

/**
 * @description OK
 */
export type ContentManagerSearchContents200 = ApiResultOnePageMapStringObject;

export type ContentManagerSearchContentsQueryResponse = ContentManagerSearchContents200;

export type ContentManagerSearchContentsQuery = {
	Response: ContentManagerSearchContents200;
	QueryParams: ContentManagerSearchContentsQueryParams;
	Errors: any;
};
