/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultOneListMapStringObject} from "../api-result-one-list-map-string-object.ts";

export type ContentManagerGetItemPathParams = {
	/**
	 * @type integer, int64
	 */
	id: number;
};

export type ContentManagerGetItemQueryParams = {
	/**
	 * @type string
	 */
	tableName: string;
	/**
	 * @default false
	 * @type boolean | undefined
	 */
	includePrivate?: boolean;
};

/**
 * @description OK
 */
export type ContentManagerGetItem200 = ApiResultOneListMapStringObject;

export type ContentManagerGetItemQueryResponse = ContentManagerGetItem200;

export type ContentManagerGetItemQuery = {
	Response: ContentManagerGetItem200;
	PathParams: ContentManagerGetItemPathParams;
	QueryParams: ContentManagerGetItemQueryParams;
	Errors: any;
};
