/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AuthorizationVerifyOtpMutationResponse,
	AuthorizationVerifyOtpQueryParams,
} from "../../types/authorization/authorization-verify-otp.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {authorizationVerifyOtp} from "../../clients/authorization/authorization-verify-otp.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const authorizationVerifyOtpMutationKey = () => [{url: "/v1/cms/auth/verify-otp"}] as const;

export type AuthorizationVerifyOtpMutationKey = ReturnType<typeof authorizationVerifyOtpMutationKey>;

export function authorizationVerifyOtpMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = authorizationVerifyOtpMutationKey();
	return mutationOptions<
		AuthorizationVerifyOtpMutationResponse,
		ResponseErrorConfig<Error>,
		{params: AuthorizationVerifyOtpQueryParams},
		TContext
	>({
		mutationKey,
		mutationFn: async ({params}) => {
			return authorizationVerifyOtp(params, config);
		},
	});
}

/**
 * @description OTP 검증 API
 * @summary v1 OTP 검증
 * {@link /v1/cms/auth/verify-otp}
 */
export function useAuthorizationVerifyOtp<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthorizationVerifyOtpMutationResponse,
			ResponseErrorConfig<Error>,
			{params: AuthorizationVerifyOtpQueryParams},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? authorizationVerifyOtpMutationKey();

	const baseOptions = authorizationVerifyOtpMutationOptions(config) as UseMutationOptions<
		AuthorizationVerifyOtpMutationResponse,
		ResponseErrorConfig<Error>,
		{params: AuthorizationVerifyOtpQueryParams},
		TContext
	>;

	return useMutation<
		AuthorizationVerifyOtpMutationResponse,
		ResponseErrorConfig<Error>,
		{params: AuthorizationVerifyOtpQueryParams},
		TContext
	>({...baseOptions, mutationKey, ...mutationOptions}, queryClient) as UseMutationResult<
		AuthorizationVerifyOtpMutationResponse,
		ResponseErrorConfig<Error>,
		{params: AuthorizationVerifyOtpQueryParams},
		TContext
	>;
}
