/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AuthorizationRefreshTokenMutationRequest,
	AuthorizationRefreshTokenMutationResponse,
} from "../../types/authorization/authorization-refresh-token.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {authorizationRefreshToken} from "../../clients/authorization/authorization-refresh-token.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const authorizationRefreshTokenMutationKey = () => [{url: "/v1/cms/auth/refresh"}] as const;

export type AuthorizationRefreshTokenMutationKey = ReturnType<typeof authorizationRefreshTokenMutationKey>;

export function authorizationRefreshTokenMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<AuthorizationRefreshTokenMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = authorizationRefreshTokenMutationKey();
	return mutationOptions<
		AuthorizationRefreshTokenMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationRefreshTokenMutationRequest},
		TContext
	>({
		mutationKey,
		mutationFn: async ({data}) => {
			return authorizationRefreshToken(data, config);
		},
	});
}

/**
 * @description accessToken 갱신 API
 * @summary v1 accessToken 갱신
 * {@link /v1/cms/auth/refresh}
 */
export function useAuthorizationRefreshToken<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthorizationRefreshTokenMutationResponse,
			ResponseErrorConfig<Error>,
			{data: AuthorizationRefreshTokenMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<AuthorizationRefreshTokenMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? authorizationRefreshTokenMutationKey();

	const baseOptions = authorizationRefreshTokenMutationOptions(config) as UseMutationOptions<
		AuthorizationRefreshTokenMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationRefreshTokenMutationRequest},
		TContext
	>;

	return useMutation<
		AuthorizationRefreshTokenMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationRefreshTokenMutationRequest},
		TContext
	>({...baseOptions, mutationKey, ...mutationOptions}, queryClient) as UseMutationResult<
		AuthorizationRefreshTokenMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationRefreshTokenMutationRequest},
		TContext
	>;
}
