/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {AuthorizationLogoutMutationResponse, AuthorizationLogoutQueryParams} from "../../types/authorization/authorization-logout.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {authorizationLogout} from "../../clients/authorization/authorization-logout.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const authorizationLogoutMutationKey = () => [{url: "/v1/cms/auth/logout"}] as const;

export type AuthorizationLogoutMutationKey = ReturnType<typeof authorizationLogoutMutationKey>;

export function authorizationLogoutMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = authorizationLogoutMutationKey();
	return mutationOptions<
		AuthorizationLogoutMutationResponse,
		ResponseErrorConfig<Error>,
		{params: AuthorizationLogoutQueryParams},
		TContext
	>({
		mutationKey,
		mutationFn: async ({params}) => {
			return authorizationLogout(params, config);
		},
	});
}

/**
 * @description 로그아웃 API
 * @summary v1 로그아웃
 * {@link /v1/cms/auth/logout}
 */
export function useAuthorizationLogout<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthorizationLogoutMutationResponse,
			ResponseErrorConfig<Error>,
			{params: AuthorizationLogoutQueryParams},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? authorizationLogoutMutationKey();

	const baseOptions = authorizationLogoutMutationOptions(config) as UseMutationOptions<
		AuthorizationLogoutMutationResponse,
		ResponseErrorConfig<Error>,
		{params: AuthorizationLogoutQueryParams},
		TContext
	>;

	return useMutation<AuthorizationLogoutMutationResponse, ResponseErrorConfig<Error>, {params: AuthorizationLogoutQueryParams}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<
		AuthorizationLogoutMutationResponse,
		ResponseErrorConfig<Error>,
		{params: AuthorizationLogoutQueryParams},
		TContext
	>;
}
