/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AuthorizationLoginGoogleMutationRequest,
	AuthorizationLoginGoogleMutationResponse,
} from "../../types/authorization/authorization-login-google.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {authorizationLoginGoogle} from "../../clients/authorization/authorization-login-google.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const authorizationLoginGoogleMutationKey = () => [{url: "/v1/cms/auth/social-login"}] as const;

export type AuthorizationLoginGoogleMutationKey = ReturnType<typeof authorizationLoginGoogleMutationKey>;

export function authorizationLoginGoogleMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<AuthorizationLoginGoogleMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = authorizationLoginGoogleMutationKey();
	return mutationOptions<
		AuthorizationLoginGoogleMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationLoginGoogleMutationRequest},
		TContext
	>({
		mutationKey,
		mutationFn: async ({data}) => {
			return authorizationLoginGoogle(data, config);
		},
	});
}

/**
 * @description Google 로그인 API
 * @summary v1 Google 로그인
 * {@link /v1/cms/auth/social-login}
 */
export function useAuthorizationLoginGoogle<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthorizationLoginGoogleMutationResponse,
			ResponseErrorConfig<Error>,
			{data: AuthorizationLoginGoogleMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<AuthorizationLoginGoogleMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? authorizationLoginGoogleMutationKey();

	const baseOptions = authorizationLoginGoogleMutationOptions(config) as UseMutationOptions<
		AuthorizationLoginGoogleMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationLoginGoogleMutationRequest},
		TContext
	>;

	return useMutation<
		AuthorizationLoginGoogleMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationLoginGoogleMutationRequest},
		TContext
	>({...baseOptions, mutationKey, ...mutationOptions}, queryClient) as UseMutationResult<
		AuthorizationLoginGoogleMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationLoginGoogleMutationRequest},
		TContext
	>;
}
