/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {AuthorizationLoginMutationRequest, AuthorizationLoginMutationResponse} from "../../types/authorization/authorization-login.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {authorizationLogin} from "../../clients/authorization/authorization-login.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const authorizationLoginMutationKey = () => [{url: "/v1/cms/auth/login"}] as const;

export type AuthorizationLoginMutationKey = ReturnType<typeof authorizationLoginMutationKey>;

export function authorizationLoginMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<AuthorizationLoginMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = authorizationLoginMutationKey();
	return mutationOptions<
		AuthorizationLoginMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationLoginMutationRequest},
		TContext
	>({
		mutationKey,
		mutationFn: async ({data}) => {
			return authorizationLogin(data, config);
		},
	});
}

/**
 * @description 로그인 API
 * @summary v1 로그인
 * {@link /v1/cms/auth/login}
 */
export function useAuthorizationLogin<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthorizationLoginMutationResponse,
			ResponseErrorConfig<Error>,
			{data: AuthorizationLoginMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<AuthorizationLoginMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? authorizationLoginMutationKey();

	const baseOptions = authorizationLoginMutationOptions(config) as UseMutationOptions<
		AuthorizationLoginMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationLoginMutationRequest},
		TContext
	>;

	return useMutation<AuthorizationLoginMutationResponse, ResponseErrorConfig<Error>, {data: AuthorizationLoginMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<
		AuthorizationLoginMutationResponse,
		ResponseErrorConfig<Error>,
		{data: AuthorizationLoginMutationRequest},
		TContext
	>;
}
