/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {AuthorizationInfoQueryResponse} from "../../types/authorization/authorization-info.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {authorizationInfo} from "../../clients/authorization/authorization-info.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const authorizationInfoQueryKey = () => [{url: "/v1/cms/auth/info"}] as const;

export type AuthorizationInfoQueryKey = ReturnType<typeof authorizationInfoQueryKey>;

export function authorizationInfoQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = authorizationInfoQueryKey();
	return queryOptions<AuthorizationInfoQueryResponse, ResponseErrorConfig<Error>, AuthorizationInfoQueryResponse, typeof queryKey>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return authorizationInfo(config);
		},
	});
}

/**
 * @description 로그인 정보 조회 API
 * @summary v1 로그인 정보 조회
 * {@link /v1/cms/auth/info}
 */
export function useAuthorizationInfo<
	TData = AuthorizationInfoQueryResponse,
	TQueryData = AuthorizationInfoQueryResponse,
	TQueryKey extends QueryKey = AuthorizationInfoQueryKey,
>(
	options: {
		query?: Partial<QueryObserverOptions<AuthorizationInfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? authorizationInfoQueryKey();

	const query = useQuery(
		{...authorizationInfoQueryOptions(config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
