/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {EnvironmentGetAuthPlatformQueryResponse} from "../../types/environment/environment-get-auth-platform.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getEnvironmentGetAuthPlatformUrl() {
	const res = {method: "GET", url: `/v1/environments/auth-platform` as const};
	return res;
}

/**
 * @description 플랫폼/GCP 로그인 사용 유무 조회 API
 * @summary v1 로그인 플랫폼 사용 유무 조회
 * {@link /v1/environments/auth-platform}
 */
export async function environmentGetAuthPlatform(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<EnvironmentGetAuthPlatformQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getEnvironmentGetAuthPlatformUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
