/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {EnvironmentGetAuthPlatformQueryResponse} from "../../types/environment/environment-get-auth-platform.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {environmentGetAuthPlatform} from "../../clients/environment/environment-get-auth-platform.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const environmentGetAuthPlatformSuspenseQueryKey = () => [{url: "/v1/environments/auth-platform"}] as const;

export type EnvironmentGetAuthPlatformSuspenseQueryKey = ReturnType<typeof environmentGetAuthPlatformSuspenseQueryKey>;

export function environmentGetAuthPlatformSuspenseQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = environmentGetAuthPlatformSuspenseQueryKey();
	return queryOptions<
		EnvironmentGetAuthPlatformQueryResponse,
		ResponseErrorConfig<Error>,
		EnvironmentGetAuthPlatformQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return environmentGetAuthPlatform(config);
		},
	});
}

/**
 * @description 플랫폼/GCP 로그인 사용 유무 조회 API
 * @summary v1 로그인 플랫폼 사용 유무 조회
 * {@link /v1/environments/auth-platform}
 */
export function useEnvironmentGetAuthPlatformSuspense<
	TData = EnvironmentGetAuthPlatformQueryResponse,
	TQueryKey extends QueryKey = EnvironmentGetAuthPlatformSuspenseQueryKey,
>(
	options: {
		query?: Partial<UseSuspenseQueryOptions<EnvironmentGetAuthPlatformQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? environmentGetAuthPlatformSuspenseQueryKey();

	const query = useSuspenseQuery(
		{...environmentGetAuthPlatformSuspenseQueryOptions(config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
