/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {EnvironmentGetAuthPlatformQueryResponse} from "../../types/environment/environment-get-auth-platform.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {environmentGetAuthPlatform} from "../../clients/environment/environment-get-auth-platform.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const environmentGetAuthPlatformQueryKey = () => [{url: "/v1/environments/auth-platform"}] as const;

export type EnvironmentGetAuthPlatformQueryKey = ReturnType<typeof environmentGetAuthPlatformQueryKey>;

export function environmentGetAuthPlatformQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = environmentGetAuthPlatformQueryKey();
	return queryOptions<
		EnvironmentGetAuthPlatformQueryResponse,
		ResponseErrorConfig<Error>,
		EnvironmentGetAuthPlatformQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return environmentGetAuthPlatform(config);
		},
	});
}

/**
 * @description 플랫폼/GCP 로그인 사용 유무 조회 API
 * @summary v1 로그인 플랫폼 사용 유무 조회
 * {@link /v1/environments/auth-platform}
 */
export function useEnvironmentGetAuthPlatform<
	TData = EnvironmentGetAuthPlatformQueryResponse,
	TQueryData = EnvironmentGetAuthPlatformQueryResponse,
	TQueryKey extends QueryKey = EnvironmentGetAuthPlatformQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<EnvironmentGetAuthPlatformQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? environmentGetAuthPlatformQueryKey();

	const query = useQuery(
		{...environmentGetAuthPlatformQueryOptions(config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
