/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultLoginResponse} from "../api-result-login-response.ts";
import type {LoginRequest} from "../login-request.ts";

/**
 * @description OK
 */
export type AuthorizationLoginGoogle200 = ApiResultLoginResponse;

export type AuthorizationLoginGoogleMutationRequest = LoginRequest;

export type AuthorizationLoginGoogleMutationResponse = AuthorizationLoginGoogle200;

export type AuthorizationLoginGoogleMutation = {
	Response: AuthorizationLoginGoogle200;
	Request: AuthorizationLoginGoogleMutationRequest;
	Errors: any;
};
