/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultTokenInfoResponse} from "../api-result-token-info-response.ts";

export type AuthorizationVerifyOtpQueryParams = {
	/**
	 * @description otp
	 * @type integer, int32
	 */
	otp: number;
};

/**
 * @description OK
 */
export type AuthorizationVerifyOtp200 = ApiResultTokenInfoResponse;

export type AuthorizationVerifyOtpMutationResponse = AuthorizationVerifyOtp200;

export type AuthorizationVerifyOtpMutation = {
	Response: AuthorizationVerifyOtp200;
	QueryParams: AuthorizationVerifyOtpQueryParams;
	Errors: any;
};
