/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultAdminDetailResponse} from "../api-result-admin-detail-response.ts";

/**
 * @description OK
 */
export type AuthorizationInfo200 = ApiResultAdminDetailResponse;

export type AuthorizationInfoQueryResponse = AuthorizationInfo200;

export type AuthorizationInfoQuery = {Response: AuthorizationInfo200; Errors: any};
