/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultTokenInfoResponse} from "../api-result-token-info-response.ts";
import type {RefreshTokenRequest} from "../refresh-token-request.ts";

/**
 * @description OK
 */
export type AuthorizationRefreshToken200 = ApiResultTokenInfoResponse;

export type AuthorizationRefreshTokenMutationRequest = RefreshTokenRequest;

export type AuthorizationRefreshTokenMutationResponse = AuthorizationRefreshToken200;

export type AuthorizationRefreshTokenMutation = {
	Response: AuthorizationRefreshToken200;
	Request: AuthorizationRefreshTokenMutationRequest;
	Errors: any;
};
