/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UnitResult} from "../unit-result.ts";

export type AuthorizationLogoutQueryParams = {
	/**
	 * @description 리프레쉬 토큰
	 * @type string
	 */
	refreshToken: string;
};

/**
 * @description OK
 */
export type AuthorizationLogout200 = UnitResult;

export type AuthorizationLogoutMutationResponse = AuthorizationLogout200;

export type AuthorizationLogoutMutation = {Response: AuthorizationLogout200; QueryParams: AuthorizationLogoutQueryParams; Errors: any};
