/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultLoginResponse} from "../api-result-login-response.ts";
import type {PlatformLoginRequest} from "../platform-login-request.ts";

/**
 * @description OK
 */
export type AuthorizationLogin200 = ApiResultLoginResponse;

export type AuthorizationLoginMutationRequest = PlatformLoginRequest;

export type AuthorizationLoginMutationResponse = AuthorizationLogin200;

export type AuthorizationLoginMutation = {Response: AuthorizationLogin200; Request: AuthorizationLoginMutationRequest; Errors: any};
