/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ContentTypeGetTableListQueryParams,
	ContentTypeGetTableList200,
	ContentTypeGetTableListQueryResponse,
} from "../../types/content-type/content-type-get-table-list.ts";
import {createApiResultOneListContentTypeTableResponse} from "../create-api-result-one-list-content-type-table-response.ts";
import {faker} from "@faker-js/faker";

export function createContentTypeGetTableListQueryParams(
	data?: Partial<ContentTypeGetTableListQueryParams>,
): ContentTypeGetTableListQueryParams {
	return {...{includeSystemColumns: faker.datatype.boolean(), includePrivateFields: faker.datatype.boolean()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createContentTypeGetTableList200(data?: Partial<ContentTypeGetTableList200>): ContentTypeGetTableList200 {
	return createApiResultOneListContentTypeTableResponse(data);
}

export function createContentTypeGetTableListQueryResponse(
	data?: Partial<ContentTypeGetTableListQueryResponse>,
): ContentTypeGetTableListQueryResponse {
	return data || faker.helpers.arrayElement<any>([createContentTypeGetTableList200()]);
}
