/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	FilterSearchFiltersQueryParams,
	FilterSearchFilters200,
	FilterSearchFiltersQueryResponse,
} from "../../types/filter/filter-search-filters.ts";
import {createApiResultOnePageFilterResponse} from "../create-api-result-one-page-filter-response.ts";
import {faker} from "@faker-js/faker";

export function createFilterSearchFiltersQueryParams(data?: Partial<FilterSearchFiltersQueryParams>): FilterSearchFiltersQueryParams {
	return {
		...{table: faker.string.alpha(), field: faker.string.alpha(), page: faker.number.int(), size: faker.number.int()},
		...(data || {}),
	};
}

/**
 * @description OK
 */
export function createFilterSearchFilters200(data?: Partial<FilterSearchFilters200>): FilterSearchFilters200 {
	return createApiResultOnePageFilterResponse(data);
}

export function createFilterSearchFiltersQueryResponse(data?: Partial<FilterSearchFiltersQueryResponse>): FilterSearchFiltersQueryResponse {
	return data || faker.helpers.arrayElement<any>([createFilterSearchFilters200()]);
}
