/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {FilterRemovePathParams, FilterRemove200, FilterRemoveMutationResponse} from "../../types/filter/filter-remove.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createFilterRemovePathParams(data?: Partial<FilterRemovePathParams>): FilterRemovePathParams {
	return {...{id: faker.number.int()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createFilterRemove200(data?: Partial<FilterRemove200>): FilterRemove200 {
	return createUnitResult(data);
}

export function createFilterRemoveMutationResponse(data?: Partial<FilterRemoveMutationResponse>): FilterRemoveMutationResponse {
	return data || faker.helpers.arrayElement<any>([createFilterRemove200()]);
}
