/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {FilterUpsert200, FilterUpsertMutationRequest, FilterUpsertMutationResponse} from "../../types/filter/filter-upsert.ts";
import {createFilterSaveRequest} from "../create-filter-save-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createFilterUpsert200(data?: Partial<FilterUpsert200>): FilterUpsert200 {
	return createUnitResult(data);
}

export function createFilterUpsertMutationRequest(data?: Partial<FilterUpsertMutationRequest>): FilterUpsertMutationRequest {
	return createFilterSaveRequest(data);
}

export function createFilterUpsertMutationResponse(data?: Partial<FilterUpsertMutationResponse>): FilterUpsertMutationResponse {
	return data || faker.helpers.arrayElement<any>([createFilterUpsert200()]);
}
