/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	BoardSearchBoardsQueryParams,
	BoardSearchBoards200,
	BoardSearchBoardsQueryResponse,
} from "../../types/board/board-search-boards.ts";
import {createApiResultOnePageBoardPageResponse} from "../create-api-result-one-page-board-page-response.ts";
import {faker} from "@faker-js/faker";

export function createBoardSearchBoardsQueryParams(data?: Partial<BoardSearchBoardsQueryParams>): BoardSearchBoardsQueryParams {
	return {
		...{
			type: faker.helpers.arrayElement<NonNullable<BoardSearchBoardsQueryParams>["type"]>(["NOTICE", "BUILD_NOTE"]),
			field: faker.helpers.multiple(() => faker.string.alpha()),
			operator: faker.helpers.multiple(() => faker.string.alpha()),
			value: faker.helpers.multiple(() => faker.string.alpha()),
			page: faker.number.int(),
			size: faker.number.int(),
		},
		...(data || {}),
	};
}

/**
 * @description OK
 */
export function createBoardSearchBoards200(data?: Partial<BoardSearchBoards200>): BoardSearchBoards200 {
	return createApiResultOnePageBoardPageResponse(data);
}

export function createBoardSearchBoardsQueryResponse(data?: Partial<BoardSearchBoardsQueryResponse>): BoardSearchBoardsQueryResponse {
	return data || faker.helpers.arrayElement<any>([createBoardSearchBoards200()]);
}
