/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {BoardUpsert200, BoardUpsertMutationRequest, BoardUpsertMutationResponse} from "../../types/board/board-upsert.ts";
import {createBoardSaveRequest} from "../create-board-save-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createBoardUpsert200(data?: Partial<BoardUpsert200>): BoardUpsert200 {
	return createUnitResult(data);
}

export function createBoardUpsertMutationRequest(data?: Partial<BoardUpsertMutationRequest>): BoardUpsertMutationRequest {
	return createBoardSaveRequest(data);
}

export function createBoardUpsertMutationResponse(data?: Partial<BoardUpsertMutationResponse>): BoardUpsertMutationResponse {
	return data || faker.helpers.arrayElement<any>([createBoardUpsert200()]);
}
