/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {BoardRemovePathParams, BoardRemove200, BoardRemoveMutationResponse} from "../../types/board/board-remove.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createBoardRemovePathParams(data?: Partial<BoardRemovePathParams>): BoardRemovePathParams {
	return {...{id: faker.number.int()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createBoardRemove200(data?: Partial<BoardRemove200>): BoardRemove200 {
	return createUnitResult(data);
}

export function createBoardRemoveMutationResponse(data?: Partial<BoardRemoveMutationResponse>): BoardRemoveMutationResponse {
	return data || faker.helpers.arrayElement<any>([createBoardRemove200()]);
}
