/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultAdminDetailResponse} from "../api-result-admin-detail-response.ts";

export type AdminGetItemPathParams = {
	/**
	 * @description 관리자 아이디
	 * @type integer, int64
	 */
	id: number;
};

/**
 * @description OK
 */
export type AdminGetItem200 = ApiResultAdminDetailResponse;

export type AdminGetItemQueryResponse = AdminGetItem200;

export type AdminGetItemQuery = {Response: AdminGetItem200; PathParams: AdminGetItemPathParams; Errors: any};
