/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UnitResult} from "../unit-result.ts";

export type AdminIsLoginIdDuplicateQueryParams = {
	/**
	 * @description 로그인 아이디
	 * @type string
	 */
	loginId: string;
};

/**
 * @description OK
 */
export type AdminIsLoginIdDuplicate200 = UnitResult;

export type AdminIsLoginIdDuplicateQueryResponse = AdminIsLoginIdDuplicate200;

export type AdminIsLoginIdDuplicateQuery = {
	Response: AdminIsLoginIdDuplicate200;
	QueryParams: AdminIsLoginIdDuplicateQueryParams;
	Errors: any;
};
