/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {AdminSaveRequest} from "../admin-save-request.ts";
import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type AdminUpsert200 = UnitResult;

export type AdminUpsertMutationRequest = AdminSaveRequest;

export type AdminUpsertMutationResponse = AdminUpsert200;

export type AdminUpsertMutation = {Response: AdminUpsert200; Request: AdminUpsertMutationRequest; Errors: any};
