/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {AdminUnlockRequest} from "../admin-unlock-request.ts";
import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type AdminUnlockAdmins200 = UnitResult;

export type AdminUnlockAdminsMutationRequest = AdminUnlockRequest;

export type AdminUnlockAdminsMutationResponse = AdminUnlockAdmins200;

export type AdminUnlockAdminsMutation = {Response: AdminUnlockAdmins200; Request: AdminUnlockAdminsMutationRequest; Errors: any};
