/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {AdminPermissionGroupBulkUpdateRequest} from "../admin-permission-group-bulk-update-request.ts";
import type {UnitResult} from "../unit-result.ts";

/**
 * @description OK
 */
export type AdminUpdates200 = UnitResult;

export type AdminUpdatesMutationRequest = AdminPermissionGroupBulkUpdateRequest;

export type AdminUpdatesMutationResponse = AdminUpdates200;

export type AdminUpdatesMutation = {Response: AdminUpdates200; Request: AdminUpdatesMutationRequest; Errors: any};
