/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UnitResult} from "../unit-result.ts";

export type AdminRemoveAdminsQueryParams = {
	/**
	 * @description 관리자 아이디 목록
	 * @type array
	 */
	ids: number[];
};

/**
 * @description OK
 */
export type AdminRemoveAdmins200 = UnitResult;

export type AdminRemoveAdminsMutationResponse = AdminRemoveAdmins200;

export type AdminRemoveAdminsMutation = {Response: AdminRemoveAdmins200; QueryParams: AdminRemoveAdminsQueryParams; Errors: any};
