/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ContentMediaCreatePresignedUrlsQueryParams,
	ContentMediaCreatePresignedUrls200,
	ContentMediaCreatePresignedUrlsMutationRequest,
	ContentMediaCreatePresignedUrlsMutationResponse,
} from "../../types/content-media/content-media-create-presigned-urls.ts";
import {createApiResultListCreateMediaPresignedUrlResponse} from "../create-api-result-list-create-media-presigned-url-response.ts";
import {createCreateMediaPresignedUrlItemRequest} from "../create-create-media-presigned-url-item-request.ts";
import {faker} from "@faker-js/faker";

export function createContentMediaCreatePresignedUrlsQueryParams(
	data?: Partial<ContentMediaCreatePresignedUrlsQueryParams>,
): ContentMediaCreatePresignedUrlsQueryParams {
	return {...{tableName: faker.string.alpha()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createContentMediaCreatePresignedUrls200(
	data?: Partial<ContentMediaCreatePresignedUrls200>,
): ContentMediaCreatePresignedUrls200 {
	return createApiResultListCreateMediaPresignedUrlResponse(data);
}

export function createContentMediaCreatePresignedUrlsMutationRequest(
	data?: ContentMediaCreatePresignedUrlsMutationRequest,
): ContentMediaCreatePresignedUrlsMutationRequest {
	return [...faker.helpers.multiple(() => createCreateMediaPresignedUrlItemRequest()), ...(data || [])];
}

export function createContentMediaCreatePresignedUrlsMutationResponse(
	data?: Partial<ContentMediaCreatePresignedUrlsMutationResponse>,
): ContentMediaCreatePresignedUrlsMutationResponse {
	return data || faker.helpers.arrayElement<any>([createContentMediaCreatePresignedUrls200()]);
}
