/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiResultAuthPlatformResponse} from "../api-result-auth-platform-response.ts";

/**
 * @description OK
 */
export type EnvironmentGetAuthPlatform200 = ApiResultAuthPlatformResponse;

export type EnvironmentGetAuthPlatformQueryResponse = EnvironmentGetAuthPlatform200;

export type EnvironmentGetAuthPlatformQuery = {Response: EnvironmentGetAuthPlatform200; Errors: any};
