/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {HomeDashboardGetUserActivitiesQueryResponse} from "../../types/home-dashboard/home-dashboard-get-user-activities.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {homeDashboardGetUserActivities} from "../../clients/home-dashboard/home-dashboard-get-user-activities.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const homeDashboardGetUserActivitiesSuspenseQueryKey = () => [{url: "/v1/home-dashboard/user-activity"}] as const;

export type HomeDashboardGetUserActivitiesSuspenseQueryKey = ReturnType<typeof homeDashboardGetUserActivitiesSuspenseQueryKey>;

export function homeDashboardGetUserActivitiesSuspenseQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = homeDashboardGetUserActivitiesSuspenseQueryKey();
	return queryOptions<
		HomeDashboardGetUserActivitiesQueryResponse,
		ResponseErrorConfig<Error>,
		HomeDashboardGetUserActivitiesQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return homeDashboardGetUserActivities(config);
		},
	});
}

/**
 * @description 관리자별 최근 사용자 활동 목록 조회 API
 * @summary v1 사용자 활동 조회
 * {@link /v1/home-dashboard/user-activity}
 */
export function useHomeDashboardGetUserActivitiesSuspense<
	TData = HomeDashboardGetUserActivitiesQueryResponse,
	TQueryKey extends QueryKey = HomeDashboardGetUserActivitiesSuspenseQueryKey,
>(
	options: {
		query?: Partial<UseSuspenseQueryOptions<HomeDashboardGetUserActivitiesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? homeDashboardGetUserActivitiesSuspenseQueryKey();

	const query = useSuspenseQuery(
		{...homeDashboardGetUserActivitiesSuspenseQueryOptions(config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
