/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {HomeDashboardGetUserActivitiesQueryResponse} from "../../types/home-dashboard/home-dashboard-get-user-activities.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {homeDashboardGetUserActivities} from "../../clients/home-dashboard/home-dashboard-get-user-activities.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const homeDashboardGetUserActivitiesQueryKey = () => [{url: "/v1/home-dashboard/user-activity"}] as const;

export type HomeDashboardGetUserActivitiesQueryKey = ReturnType<typeof homeDashboardGetUserActivitiesQueryKey>;

export function homeDashboardGetUserActivitiesQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = homeDashboardGetUserActivitiesQueryKey();
	return queryOptions<
		HomeDashboardGetUserActivitiesQueryResponse,
		ResponseErrorConfig<Error>,
		HomeDashboardGetUserActivitiesQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return homeDashboardGetUserActivities(config);
		},
	});
}

/**
 * @description 관리자별 최근 사용자 활동 목록 조회 API
 * @summary v1 사용자 활동 조회
 * {@link /v1/home-dashboard/user-activity}
 */
export function useHomeDashboardGetUserActivities<
	TData = HomeDashboardGetUserActivitiesQueryResponse,
	TQueryData = HomeDashboardGetUserActivitiesQueryResponse,
	TQueryKey extends QueryKey = HomeDashboardGetUserActivitiesQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<HomeDashboardGetUserActivitiesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? homeDashboardGetUserActivitiesQueryKey();

	const query = useQuery(
		{...homeDashboardGetUserActivitiesQueryOptions(config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
