/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {HomeDashboardGetBuildNotesQueryResponse} from "../../types/home-dashboard/home-dashboard-get-build-notes.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {homeDashboardGetBuildNotes} from "../../clients/home-dashboard/home-dashboard-get-build-notes.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const homeDashboardGetBuildNotesQueryKey = () => [{url: "/v1/home-dashboard/build-notes"}] as const;

export type HomeDashboardGetBuildNotesQueryKey = ReturnType<typeof homeDashboardGetBuildNotesQueryKey>;

export function homeDashboardGetBuildNotesQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = homeDashboardGetBuildNotesQueryKey();
	return queryOptions<
		HomeDashboardGetBuildNotesQueryResponse,
		ResponseErrorConfig<Error>,
		HomeDashboardGetBuildNotesQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return homeDashboardGetBuildNotes(config);
		},
	});
}

/**
 * @description 빌드노트 최근 5건 조회 API
 * @summary v1 빌드노트 조회
 * {@link /v1/home-dashboard/build-notes}
 */
export function useHomeDashboardGetBuildNotes<
	TData = HomeDashboardGetBuildNotesQueryResponse,
	TQueryData = HomeDashboardGetBuildNotesQueryResponse,
	TQueryKey extends QueryKey = HomeDashboardGetBuildNotesQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<HomeDashboardGetBuildNotesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? homeDashboardGetBuildNotesQueryKey();

	const query = useQuery(
		{...homeDashboardGetBuildNotesQueryOptions(config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
