/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {HomeDashboardGetNoticesQueryResponse} from "../../types/home-dashboard/home-dashboard-get-notices.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {homeDashboardGetNotices} from "../../clients/home-dashboard/home-dashboard-get-notices.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const homeDashboardGetNoticesSuspenseQueryKey = () => [{url: "/v1/home-dashboard/notices"}] as const;

export type HomeDashboardGetNoticesSuspenseQueryKey = ReturnType<typeof homeDashboardGetNoticesSuspenseQueryKey>;

export function homeDashboardGetNoticesSuspenseQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = homeDashboardGetNoticesSuspenseQueryKey();
	return queryOptions<
		HomeDashboardGetNoticesQueryResponse,
		ResponseErrorConfig<Error>,
		HomeDashboardGetNoticesQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return homeDashboardGetNotices(config);
		},
	});
}

/**
 * @description 공지사항 최근 5건 조회 API
 * @summary v1 공지사항 조회
 * {@link /v1/home-dashboard/notices}
 */
export function useHomeDashboardGetNoticesSuspense<
	TData = HomeDashboardGetNoticesQueryResponse,
	TQueryKey extends QueryKey = HomeDashboardGetNoticesSuspenseQueryKey,
>(
	options: {
		query?: Partial<UseSuspenseQueryOptions<HomeDashboardGetNoticesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? homeDashboardGetNoticesSuspenseQueryKey();

	const query = useSuspenseQuery(
		{...homeDashboardGetNoticesSuspenseQueryOptions(config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
