/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {PermissionGroupResponse} from "./permission-group-response.ts";

export const adminDetailResponseProviderEnum = {GOOGLE: "GOOGLE", APPLE: "APPLE"} as const;

export type AdminDetailResponseProviderEnumKey = (typeof adminDetailResponseProviderEnum)[keyof typeof adminDetailResponseProviderEnum];

export type AdminDetailResponse = {
	/**
	 * @description 어드민 아이디
	 * @type integer, int64
	 */
	id: number;
	/**
	 * @description 권한 그룹
	 * @type object
	 */
	permissionGroup: PermissionGroupResponse;
	/**
	 * @description 소셜 유형
	 * @type string | undefined
	 */
	provider?: AdminDetailResponseProviderEnumKey;
	/**
	 * @description 로그인 아이디
	 * @type string
	 */
	loginId: string;
	/**
	 * @description 이름
	 * @type string
	 */
	name: string;
	/**
	 * @description OTP Secret Key
	 * @type string | undefined
	 */
	otpSecretKey?: string;
	/**
	 * @description 삭제 여부
	 * @type boolean
	 */
	removed: boolean;
	/**
	 * @description 비밀번호 오류횟수
	 * @type integer | undefined, int32
	 */
	lockCount?: number;
	/**
	 * @description 잠금 일시
	 * @type string | undefined, date-time
	 */
	lockedAt?: string;
	/**
	 * @description 계정 생성 일시
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @description 삭제 일시
	 * @type string | undefined, date-time
	 */
	disabledAt?: string;
	/**
	 * @description 마지막 로그인 일시
	 * @type string | undefined, date-time
	 */
	lastLoginAt?: string;
	/**
	 * @description 비밀번호 변경일시
	 * @type string | undefined, date-time
	 */
	resetPasswordAt?: string;
	/**
	 * @description 테넌시 ID
	 * @type integer | undefined, int64
	 */
	tenantId?: number;
};
