/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

export const adminSaveRequestProviderEnum = {GOOGLE: "GOOGLE", APPLE: "APPLE"} as const;

export type AdminSaveRequestProviderEnumKey = (typeof adminSaveRequestProviderEnum)[keyof typeof adminSaveRequestProviderEnum];

export type AdminSaveRequest = {
	/**
	 * @description 어드민 아이디
	 * @type integer | undefined, int64
	 */
	id?: number;
	/**
	 * @description 권한 그룹 아이디
	 * @type integer, int64
	 */
	permissionGroupId: number;
	/**
	 * @description 소셜 유형
	 * @type string | undefined
	 */
	provider?: AdminSaveRequestProviderEnumKey;
	/**
	 * @description 로그인 아이디
	 * @minLength 1
	 * @type string
	 */
	loginId: string;
	/**
	 * @description 비밀번호 (비밀번호 변경 하려는 경우만 입력)
	 * @type string | undefined
	 */
	password?: string;
	/**
	 * @description 이름
	 * @minLength 1
	 * @type string
	 */
	name: string;
	/**
	 * @description 멀티테넌트 아이디
	 * @type integer | undefined, int64
	 */
	tenantId?: number;
};
