/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

export type AuthPlatformResponse = {
	/**
	 * @description 플랫폼 로그인 사용 여부
	 * @type boolean
	 */
	usePlatformLogin: boolean;
	/**
	 * @description GCP 로그인 사용 여부
	 * @type boolean
	 */
	useGcpLogin: boolean;
};
