/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

export type ConfigValueResponse = {
	/**
	 * @description 설정 키
	 * @type string
	 */
	config: string;
	/**
	 * @description 설정 값
	 * @type string
	 */
	value: string;
};
