/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

/**
 * @description 시스템 설정 DTO
 */
export type ConfigValueRequest = {
	/**
	 * @description 설정 키
	 * @type string
	 */
	config: string;
	/**
	 * @description 설정 값
	 * @type string
	 */
	value: string;
	/**
	 * @description 설명
	 * @type string | undefined
	 */
	description?: string;
	/**
	 * @description 개인화된 값 여부 (true: 사용자별 설정, false: 공통 설정)
	 * @default false
	 * @type boolean | undefined
	 */
	personalized?: boolean;
};
