/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UpsertMediaColumnRequest} from "./upsert-media-column-request.ts";

export type ContentUpsertRequest = {
	/**
	 * @description 일반 컬럼 데이터
	 * @type object | undefined
	 */
	body?: {[key: string]: unknown};
	/**
	 * @description MEDIA 컬럼 파일 메타 요청
	 * @type array | undefined
	 */
	fileRequests?: UpsertMediaColumnRequest[];
};
