/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ContentFolderSaveNodeRequest} from "./content-folder-save-node-request.ts";

export type ContentFolderSaveRequest = {
	/**
	 * @description 루트 노드 목록(FOLDER/TABLE 혼합)
	 * @type array
	 */
	nodes: ContentFolderSaveNodeRequest[];
};
