/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ContentTypeColumnResponse} from "./content-type-column-response.ts";

export type ContentTypeTableResponse = {
	/**
	 * @description 테이블 명
	 * @type string
	 */
	tableName: string;
	/**
	 * @description 테이블 표시 명
	 * @type string | undefined
	 */
	displayName?: string;
	/**
	 * @description 컬럼 목록
	 * @type array
	 */
	columns: ContentTypeColumnResponse[];
};
