/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

export type CreateMediaPresignedUrlItemRequest = {
	/**
	 * @description MEDIA 필드 논리 컬럼 이름
	 * @minLength 1
	 * @pattern ^[a-z_][a-z0-9_]{0,63}$
	 * @type string
	 */
	columnName: string;
	/**
	 * @description 원본 파일명
	 * @minLength 1
	 * @type string
	 */
	name: string;
	/**
	 * @description MIME 타입
	 * @minLength 1
	 * @type string
	 */
	mimeType: string;
	/**
	 * @description 파일 크기(byte)
	 * @minLength 1
	 * @type integer, int64
	 */
	size: number;
};
