/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

export type FilterSaveRequest = {
	/**
	 * @description 필터 아이디 - null이면 등록, 아니면 수정
	 * @type integer | undefined, int64
	 */
	id?: number;
	/**
	 * @description 테이블명
	 * @minLength 1
	 * @type string
	 */
	table: string;
	/**
	 * @description 컬럼명
	 * @minLength 1
	 * @type string
	 */
	field: string;
	/**
	 * @description 컬럼 레이블
	 * @minLength 1
	 * @type string
	 */
	label: string;
	/**
	 * @description 컬럼 타입
	 * @minLength 1
	 * @type string
	 */
	dataType: string;
	/**
	 * @description 연산자
	 * @minLength 1
	 * @type string
	 */
	operator: string;
	/**
	 * @description 입력 컴포넌트
	 * @minLength 1
	 * @type string
	 */
	component: string;
	/**
	 * @description 컴포넌트 요소
	 * @type string | undefined
	 */
	items?: string;
};
