/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {TokenInfoResponse} from "./token-info-response.ts";

export type LoginResponse = {
	/**
	 * @description Otp 검증 필요 여부
	 * @type boolean
	 */
	otpRequired: boolean;
	/**
	 * @description Otp Token
	 * @type string | undefined
	 */
	otpToken?: string;
	/**
	 * @description 토큰 만료일시
	 * @type string | undefined, date-time
	 */
	otpExpiredAt?: string;
	/**
	 * @description access, refresh token
	 * @type object | undefined
	 */
	tokenInfo?: TokenInfoResponse;
};
