/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {BoardPageResponse} from "./board-page-response.ts";

export type OnePageBoardPageResponse = {
	/**
	 * @type integer, int32
	 */
	page: number;
	/**
	 * @type integer, int32
	 */
	totalCount: number;
	/**
	 * @type array
	 */
	list: BoardPageResponse[];
};
