/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiEndpointSaveRequest} from "./api-endpoint-save-request.ts";
import type {PermissionGroupSaveRequest} from "./permission-group-save-request.ts";

export type PermissionGroupApiEndpointSaveRequest = {
	/**
	 * @description 권한 그룹 정보
	 * @type object
	 */
	permissionGroupRequest: PermissionGroupSaveRequest;
	/**
	 * @description 할당 API 엔드포인트 권한 목록
	 * @type array | undefined
	 */
	apiEndpoints?: ApiEndpointSaveRequest[];
};
