/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

export type PermissionGroupAdminResponse = {
	/**
	 * @description 어드민 아이디
	 * @type integer, int64
	 */
	id: number;
	/**
	 * @description 로그인 아이디
	 * @type string
	 */
	loginId: string;
	/**
	 * @description 이름
	 * @type string
	 */
	name: string;
	/**
	 * @description 삭제 여부
	 * @type boolean
	 */
	removed: boolean;
};
