/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {ApiEndpointSummaryResponse} from "./api-endpoint-summary-response.ts";
import type {PermissionGroupAdminResponse} from "./permission-group-admin-response.ts";
import type {PermissionGroupResponse} from "./permission-group-response.ts";

export type PermissionGroupApiEndPointResponse = {
	/**
	 * @description 권한 그룹 상세 정보
	 * @type object
	 */
	permissionGroup: PermissionGroupResponse;
	/**
	 * @description 할당 API 엔드포인트 권한 목록
	 * @type array | undefined
	 */
	permissions?: ApiEndpointSummaryResponse[];
	/**
	 * @type array | undefined
	 */
	permissionGroupAdmin?: PermissionGroupAdminResponse[];
};
