/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

export type PlatformLoginRequest = {
	/**
	 * @description 로그인 아이디
	 * @minLength 1
	 * @type string
	 */
	loginId: string;
	/**
	 * @description 로그인 비밀번호
	 * @minLength 1
	 * @type string
	 */
	password: string;
};
