/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

export type TokenInfoResponse = {
	/**
	 * @description access token
	 * @type string
	 */
	accessToken: string;
	/**
	 * @description refresh token
	 * @type string
	 */
	refreshToken: string;
};
