/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {UpsertMediaFileRequest} from "./upsert-media-file-request.ts";

export type UpsertMediaColumnRequest = {
	/**
	 * @description MEDIA 논리 컬럼명
	 * @minLength 1
	 * @pattern ^[a-z_][a-z0-9_]{0,63}$
	 * @type string
	 */
	columnName: string;
	/**
	 * @description 업로드된 파일 메타 목록
	 * @type array
	 */
	files: UpsertMediaFileRequest[];
};
