/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ContentManagerGetTableInfoQueryParams,
	ContentManagerGetTableInfo200,
	ContentManagerGetTableInfoQueryResponse,
} from "../../types/content-manager/content-manager-get-table-info.ts";
import {createApiResultOneListContentTypeColumnResponse} from "../create-api-result-one-list-content-type-column-response.ts";
import {faker} from "@faker-js/faker";

export function createContentManagerGetTableInfoQueryParams(
	data?: Partial<ContentManagerGetTableInfoQueryParams>,
): ContentManagerGetTableInfoQueryParams {
	return {
		...{tableName: faker.string.alpha(), includeSystemColumns: faker.datatype.boolean(), includePrivate: faker.datatype.boolean()},
		...(data || {}),
	};
}

/**
 * @description OK
 */
export function createContentManagerGetTableInfo200(data?: Partial<ContentManagerGetTableInfo200>): ContentManagerGetTableInfo200 {
	return createApiResultOneListContentTypeColumnResponse(data);
}

export function createContentManagerGetTableInfoQueryResponse(
	data?: Partial<ContentManagerGetTableInfoQueryResponse>,
): ContentManagerGetTableInfoQueryResponse {
	return data || faker.helpers.arrayElement<any>([createContentManagerGetTableInfo200()]);
}
