/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ContentManagerSearchContentsQueryParams,
	ContentManagerSearchContents200,
	ContentManagerSearchContentsQueryResponse,
} from "../../types/content-manager/content-manager-search-contents.ts";
import {createApiResultOnePageMapStringObject} from "../create-api-result-one-page-map-string-object.ts";
import {faker} from "@faker-js/faker";

export function createContentManagerSearchContentsQueryParams(
	data?: Partial<ContentManagerSearchContentsQueryParams>,
): ContentManagerSearchContentsQueryParams {
	return {
		...{tableName: faker.string.alpha(), includePrivate: faker.datatype.boolean(), page: faker.number.int(), size: faker.number.int()},
		...(data || {}),
	};
}

/**
 * @description OK
 */
export function createContentManagerSearchContents200(data?: Partial<ContentManagerSearchContents200>): ContentManagerSearchContents200 {
	return createApiResultOnePageMapStringObject(data);
}

export function createContentManagerSearchContentsQueryResponse(
	data?: Partial<ContentManagerSearchContentsQueryResponse>,
): ContentManagerSearchContentsQueryResponse {
	return data || faker.helpers.arrayElement<any>([createContentManagerSearchContents200()]);
}
