/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ContentManagerUpsertQueryParams,
	ContentManagerUpsert200,
	ContentManagerUpsertMutationRequest,
	ContentManagerUpsertMutationResponse,
} from "../../types/content-manager/content-manager-upsert.ts";
import {createContentUpsertRequest} from "../create-content-upsert-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createContentManagerUpsertQueryParams(data?: Partial<ContentManagerUpsertQueryParams>): ContentManagerUpsertQueryParams {
	return {...{tableName: faker.string.alpha(), includePrivate: faker.datatype.boolean()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createContentManagerUpsert200(data?: Partial<ContentManagerUpsert200>): ContentManagerUpsert200 {
	return createUnitResult(data);
}

export function createContentManagerUpsertMutationRequest(
	data?: Partial<ContentManagerUpsertMutationRequest>,
): ContentManagerUpsertMutationRequest {
	return createContentUpsertRequest(data);
}

export function createContentManagerUpsertMutationResponse(
	data?: Partial<ContentManagerUpsertMutationResponse>,
): ContentManagerUpsertMutationResponse {
	return data || faker.helpers.arrayElement<any>([createContentManagerUpsert200()]);
}
