/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ContentManagerGetItemPathParams,
	ContentManagerGetItemQueryParams,
	ContentManagerGetItem200,
	ContentManagerGetItemQueryResponse,
} from "../../types/content-manager/content-manager-get-item.ts";
import {createApiResultOneListMapStringObject} from "../create-api-result-one-list-map-string-object.ts";
import {faker} from "@faker-js/faker";

export function createContentManagerGetItemPathParams(data?: Partial<ContentManagerGetItemPathParams>): ContentManagerGetItemPathParams {
	return {...{id: faker.number.int()}, ...(data || {})};
}

export function createContentManagerGetItemQueryParams(data?: Partial<ContentManagerGetItemQueryParams>): ContentManagerGetItemQueryParams {
	return {...{tableName: faker.string.alpha(), includePrivate: faker.datatype.boolean()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createContentManagerGetItem200(data?: Partial<ContentManagerGetItem200>): ContentManagerGetItem200 {
	return createApiResultOneListMapStringObject(data);
}

export function createContentManagerGetItemQueryResponse(
	data?: Partial<ContentManagerGetItemQueryResponse>,
): ContentManagerGetItemQueryResponse {
	return data || faker.helpers.arrayElement<any>([createContentManagerGetItem200()]);
}
