/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	ContentManagerRemovesQueryParams,
	ContentManagerRemoves200,
	ContentManagerRemovesMutationResponse,
} from "../../types/content-manager/content-manager-removes.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createContentManagerRemovesQueryParams(data?: Partial<ContentManagerRemovesQueryParams>): ContentManagerRemovesQueryParams {
	return {...{tableName: faker.string.alpha(), ids: faker.helpers.multiple(() => faker.number.int())}, ...(data || {})};
}

/**
 * @description OK
 */
export function createContentManagerRemoves200(data?: Partial<ContentManagerRemoves200>): ContentManagerRemoves200 {
	return createUnitResult(data);
}

export function createContentManagerRemovesMutationResponse(
	data?: Partial<ContentManagerRemovesMutationResponse>,
): ContentManagerRemovesMutationResponse {
	return data || faker.helpers.arrayElement<any>([createContentManagerRemoves200()]);
}
