/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {TenantUpsertMutationRequest, TenantUpsertMutationResponse} from "../../types/tenant/tenant-upsert.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {tenantUpsert} from "../../clients/tenant/tenant-upsert.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const tenantUpsertMutationKey = () => [{url: "/v1/tenants"}] as const;

export type TenantUpsertMutationKey = ReturnType<typeof tenantUpsertMutationKey>;

export function tenantUpsertMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<TenantUpsertMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = tenantUpsertMutationKey();
	return mutationOptions<TenantUpsertMutationResponse, ResponseErrorConfig<Error>, {data: TenantUpsertMutationRequest}, TContext>({
		mutationKey,
		mutationFn: async ({data}) => {
			return tenantUpsert(data, config);
		},
	});
}

/**
 * @description 테넌트 등록/수정 API
 * @summary v1 테넌트 등록/수정
 * {@link /v1/tenants}
 */
export function useTenantUpsert<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TenantUpsertMutationResponse,
			ResponseErrorConfig<Error>,
			{data: TenantUpsertMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<TenantUpsertMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? tenantUpsertMutationKey();

	const baseOptions = tenantUpsertMutationOptions(config) as UseMutationOptions<
		TenantUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: TenantUpsertMutationRequest},
		TContext
	>;

	return useMutation<TenantUpsertMutationResponse, ResponseErrorConfig<Error>, {data: TenantUpsertMutationRequest}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<TenantUpsertMutationResponse, ResponseErrorConfig<Error>, {data: TenantUpsertMutationRequest}, TContext>;
}
