/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {TenantRemoveMutationResponse, TenantRemovePathParams} from "../../types/tenant/tenant-remove.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {tenantRemove} from "../../clients/tenant/tenant-remove.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const tenantRemoveMutationKey = () => [{url: "/v1/tenants/:id"}] as const;

export type TenantRemoveMutationKey = ReturnType<typeof tenantRemoveMutationKey>;

export function tenantRemoveMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = tenantRemoveMutationKey();
	return mutationOptions<TenantRemoveMutationResponse, ResponseErrorConfig<Error>, {id: TenantRemovePathParams["id"]}, TContext>({
		mutationKey,
		mutationFn: async ({id}) => {
			return tenantRemove(id, config);
		},
	});
}

/**
 * @description 테넌트 삭제 API(soft delete)
 * @summary v1 테넌트 삭제
 * {@link /v1/tenants/:id}
 */
export function useTenantRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TenantRemoveMutationResponse,
			ResponseErrorConfig<Error>,
			{id: TenantRemovePathParams["id"]},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? tenantRemoveMutationKey();

	const baseOptions = tenantRemoveMutationOptions(config) as UseMutationOptions<
		TenantRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{id: TenantRemovePathParams["id"]},
		TContext
	>;

	return useMutation<TenantRemoveMutationResponse, ResponseErrorConfig<Error>, {id: TenantRemovePathParams["id"]}, TContext>(
		{...baseOptions, mutationKey, ...mutationOptions},
		queryClient,
	) as UseMutationResult<TenantRemoveMutationResponse, ResponseErrorConfig<Error>, {id: TenantRemovePathParams["id"]}, TContext>;
}
