/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {TenantSearchTenantsQueryResponse, TenantSearchTenantsQueryParams} from "../../types/tenant/tenant-search-tenants.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {tenantSearchTenants} from "../../clients/tenant/tenant-search-tenants.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const tenantSearchTenantsQueryKey = (params: TenantSearchTenantsQueryParams = {}) =>
	[{url: "/v1/tenants"}, ...(params ? [params] : [])] as const;

export type TenantSearchTenantsQueryKey = ReturnType<typeof tenantSearchTenantsQueryKey>;

export function tenantSearchTenantsQueryOptions(
	params?: TenantSearchTenantsQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = tenantSearchTenantsQueryKey(params);
	return queryOptions<TenantSearchTenantsQueryResponse, ResponseErrorConfig<Error>, TenantSearchTenantsQueryResponse, typeof queryKey>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return tenantSearchTenants(params, config);
		},
	});
}

/**
 * @description removed=false 테넌트 목록을 id desc 정렬로 페이징 조회 API
 * @summary v1 테넌트 목록 조회
 * {@link /v1/tenants}
 */
export function useTenantSearchTenants<
	TData = TenantSearchTenantsQueryResponse,
	TQueryData = TenantSearchTenantsQueryResponse,
	TQueryKey extends QueryKey = TenantSearchTenantsQueryKey,
>(
	params?: TenantSearchTenantsQueryParams,
	options: {
		query?: Partial<QueryObserverOptions<TenantSearchTenantsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? tenantSearchTenantsQueryKey(params);

	const query = useQuery(
		{...tenantSearchTenantsQueryOptions(params, config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
