/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {TenantRemovePathParams, TenantRemove200, TenantRemoveMutationResponse} from "../../types/tenant/tenant-remove.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

export function createTenantRemovePathParams(data?: Partial<TenantRemovePathParams>): TenantRemovePathParams {
	return {...{id: faker.number.int()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createTenantRemove200(data?: Partial<TenantRemove200>): TenantRemove200 {
	return createUnitResult(data);
}

export function createTenantRemoveMutationResponse(data?: Partial<TenantRemoveMutationResponse>): TenantRemoveMutationResponse {
	return data || faker.helpers.arrayElement<any>([createTenantRemove200()]);
}
