/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {
	TenantSearchTenantsQueryParams,
	TenantSearchTenants200,
	TenantSearchTenantsQueryResponse,
} from "../../types/tenant/tenant-search-tenants.ts";
import {createApiResultOnePageTenantResponse} from "../create-api-result-one-page-tenant-response.ts";
import {faker} from "@faker-js/faker";

export function createTenantSearchTenantsQueryParams(data?: Partial<TenantSearchTenantsQueryParams>): TenantSearchTenantsQueryParams {
	return {...{page: faker.number.int(), size: faker.number.int()}, ...(data || {})};
}

/**
 * @description OK
 */
export function createTenantSearchTenants200(data?: Partial<TenantSearchTenants200>): TenantSearchTenants200 {
	return createApiResultOnePageTenantResponse(data);
}

export function createTenantSearchTenantsQueryResponse(data?: Partial<TenantSearchTenantsQueryResponse>): TenantSearchTenantsQueryResponse {
	return data || faker.helpers.arrayElement<any>([createTenantSearchTenants200()]);
}
