/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import RandExp from "randexp";
import type {TenantUpsert200, TenantUpsertMutationRequest, TenantUpsertMutationResponse} from "../../types/tenant/tenant-upsert.ts";
import {createTenantSaveRequest} from "../create-tenant-save-request.ts";
import {createUnitResult} from "../create-unit-result.ts";
import {faker} from "@faker-js/faker";

/**
 * @description OK
 */
export function createTenantUpsert200(data?: Partial<TenantUpsert200>): TenantUpsert200 {
	return createUnitResult(data);
}

export function createTenantUpsertMutationRequest(data?: Partial<TenantUpsertMutationRequest>): TenantUpsertMutationRequest {
	return createTenantSaveRequest(data);
}

export function createTenantUpsertMutationResponse(data?: Partial<TenantUpsertMutationResponse>): TenantUpsertMutationResponse {
	return data || faker.helpers.arrayElement<any>([createTenantUpsert200()]);
}
