/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import type {Client, RequestConfig, ResponseErrorConfig} from "../../.kubb/fetch.ts";
import type {
	AuditLogSearchAuditLogsQueryResponse,
	AuditLogSearchAuditLogsQueryParams,
} from "../../types/audit-log/audit-log-search-audit-logs.ts";
import {fetch} from "../../.kubb/fetch.ts";

function getAuditLogSearchAuditLogsUrl() {
	const res = {method: "GET", url: `/v1/audit-logs` as const};
	return res;
}

/**
 * @description 감사 로그 목록 페이징 조회 API
 * @summary v1 감사 로그 목록 조회
 * {@link /v1/audit-logs}
 */
export async function auditLogSearchAuditLogs(
	params?: AuditLogSearchAuditLogsQueryParams,
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const {client: request = fetch, ...requestConfig} = config;

	const res = await request<AuditLogSearchAuditLogsQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: "GET",
		url: getAuditLogSearchAuditLogsUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
