/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {PermissionGroupGetApiEndpointListQueryResponse} from "../../types/permission-group/permission-group-get-api-endpoint-list.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult} from "@tanstack/react-query";
import {permissionGroupGetApiEndpointList} from "../../clients/permission-group/permission-group-get-api-endpoint-list.ts";
import {queryOptions, useSuspenseQuery} from "@tanstack/react-query";

export const permissionGroupGetApiEndpointListSuspenseQueryKey = () => [{url: "/v1/admins/permission-groups/api-endpoints"}] as const;

export type PermissionGroupGetApiEndpointListSuspenseQueryKey = ReturnType<typeof permissionGroupGetApiEndpointListSuspenseQueryKey>;

export function permissionGroupGetApiEndpointListSuspenseQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = permissionGroupGetApiEndpointListSuspenseQueryKey();
	return queryOptions<
		PermissionGroupGetApiEndpointListQueryResponse,
		ResponseErrorConfig<Error>,
		PermissionGroupGetApiEndpointListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return permissionGroupGetApiEndpointList(config);
		},
	});
}

/**
 * @description  API 엔드포인트(Tag name 기준으로 그룹핑된 HTTP 메서드) 목록 조회 API
 * @summary v1 API 엔드포인트 목록 조회
 * {@link /v1/admins/permission-groups/api-endpoints}
 */
export function usePermissionGroupGetApiEndpointListSuspense<
	TData = PermissionGroupGetApiEndpointListQueryResponse,
	TQueryKey extends QueryKey = PermissionGroupGetApiEndpointListSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<PermissionGroupGetApiEndpointListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? permissionGroupGetApiEndpointListSuspenseQueryKey();

	const query = useSuspenseQuery(
		{...permissionGroupGetApiEndpointListSuspenseQueryOptions(config), queryKey, ...queryOptions} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
