/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {PermissionGroupGetListQueryResponse} from "../../types/permission-group/permission-group-get-list.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {permissionGroupGetList} from "../../clients/permission-group/permission-group-get-list.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const permissionGroupGetListQueryKey = () => [{url: "/v1/admins/permission-groups"}] as const;

export type PermissionGroupGetListQueryKey = ReturnType<typeof permissionGroupGetListQueryKey>;

export function permissionGroupGetListQueryOptions(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const queryKey = permissionGroupGetListQueryKey();
	return queryOptions<
		PermissionGroupGetListQueryResponse,
		ResponseErrorConfig<Error>,
		PermissionGroupGetListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return permissionGroupGetList(config);
		},
	});
}

/**
 * @description 권한 그룹 목록 조회 API
 * @summary v1 권한 그룹 목록 조회
 * {@link /v1/admins/permission-groups}
 */
export function usePermissionGroupGetList<
	TData = PermissionGroupGetListQueryResponse,
	TQueryData = PermissionGroupGetListQueryResponse,
	TQueryKey extends QueryKey = PermissionGroupGetListQueryKey,
>(
	options: {
		query?: Partial<QueryObserverOptions<PermissionGroupGetListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? permissionGroupGetListQueryKey();

	const query = useQuery(
		{...permissionGroupGetListQueryOptions(config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
