/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	PermissionGroupUpsertMutationRequest,
	PermissionGroupUpsertMutationResponse,
} from "../../types/permission-group/permission-group-upsert.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {permissionGroupUpsert} from "../../clients/permission-group/permission-group-upsert.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const permissionGroupUpsertMutationKey = () => [{url: "/v1/admins/permission-groups"}] as const;

export type PermissionGroupUpsertMutationKey = ReturnType<typeof permissionGroupUpsertMutationKey>;

export function permissionGroupUpsertMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<PermissionGroupUpsertMutationRequest>> & {client?: Client} = {},
) {
	const mutationKey = permissionGroupUpsertMutationKey();
	return mutationOptions<
		PermissionGroupUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: PermissionGroupUpsertMutationRequest},
		TContext
	>({
		mutationKey,
		mutationFn: async ({data}) => {
			return permissionGroupUpsert(data, config);
		},
	});
}

/**
 * @description 관리자 권한 등록/수정 API
 * @summary v1 권한 그룹 등록/수정
 * {@link /v1/admins/permission-groups}
 */
export function usePermissionGroupUpsert<TContext>(
	options: {
		mutation?: UseMutationOptions<
			PermissionGroupUpsertMutationResponse,
			ResponseErrorConfig<Error>,
			{data: PermissionGroupUpsertMutationRequest},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig<PermissionGroupUpsertMutationRequest>> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? permissionGroupUpsertMutationKey();

	const baseOptions = permissionGroupUpsertMutationOptions(config) as UseMutationOptions<
		PermissionGroupUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: PermissionGroupUpsertMutationRequest},
		TContext
	>;

	return useMutation<
		PermissionGroupUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: PermissionGroupUpsertMutationRequest},
		TContext
	>({...baseOptions, mutationKey, ...mutationOptions}, queryClient) as UseMutationResult<
		PermissionGroupUpsertMutationResponse,
		ResponseErrorConfig<Error>,
		{data: PermissionGroupUpsertMutationRequest},
		TContext
	>;
}
