/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	PermissionGroupRemoveMutationResponse,
	PermissionGroupRemovePathParams,
} from "../../types/permission-group/permission-group-remove.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {UseMutationOptions, UseMutationResult, QueryClient} from "@tanstack/react-query";
import {permissionGroupRemove} from "../../clients/permission-group/permission-group-remove.ts";
import {mutationOptions, useMutation} from "@tanstack/react-query";

export const permissionGroupRemoveMutationKey = () => [{url: "/v1/admins/permission-groups/:permissionGroupId"}] as const;

export type PermissionGroupRemoveMutationKey = ReturnType<typeof permissionGroupRemoveMutationKey>;

export function permissionGroupRemoveMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & {client?: Client} = {}) {
	const mutationKey = permissionGroupRemoveMutationKey();
	return mutationOptions<
		PermissionGroupRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{permissionGroupId: PermissionGroupRemovePathParams["permissionGroupId"]},
		TContext
	>({
		mutationKey,
		mutationFn: async ({permissionGroupId}) => {
			return permissionGroupRemove(permissionGroupId, config);
		},
	});
}

/**
 * @description 관리자 권한 삭제 API
 * @summary v1 권한 그룹 삭제
 * {@link /v1/admins/permission-groups/:permissionGroupId}
 */
export function usePermissionGroupRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			PermissionGroupRemoveMutationResponse,
			ResponseErrorConfig<Error>,
			{permissionGroupId: PermissionGroupRemovePathParams["permissionGroupId"]},
			TContext
		> & {client?: QueryClient};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {mutation = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...mutationOptions} = mutation;
	const mutationKey = mutationOptions.mutationKey ?? permissionGroupRemoveMutationKey();

	const baseOptions = permissionGroupRemoveMutationOptions(config) as UseMutationOptions<
		PermissionGroupRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{permissionGroupId: PermissionGroupRemovePathParams["permissionGroupId"]},
		TContext
	>;

	return useMutation<
		PermissionGroupRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{permissionGroupId: PermissionGroupRemovePathParams["permissionGroupId"]},
		TContext
	>({...baseOptions, mutationKey, ...mutationOptions}, queryClient) as UseMutationResult<
		PermissionGroupRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{permissionGroupId: PermissionGroupRemovePathParams["permissionGroupId"]},
		TContext
	>;
}
