/** biome-ignore-all lint/correctness/noUnusedImports: IDONCARE */
/** biome-ignore-all lint/suspicious/noExplicitAny: IDONCARE */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: api-docs
 * Title: CMS API
 * Description: CMS API
 * OpenAPI spec version: v1.0.0
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	PermissionGroupGetItemQueryResponse,
	PermissionGroupGetItemPathParams,
} from "../../types/permission-group/permission-group-get-item.ts";
import type {Client, RequestConfig, ResponseErrorConfig} from "@kubb/plugin-client/clients/axios";
import type {QueryKey, QueryClient, QueryObserverOptions, UseQueryResult} from "@tanstack/react-query";
import {permissionGroupGetItem} from "../../clients/permission-group/permission-group-get-item.ts";
import {queryOptions, useQuery} from "@tanstack/react-query";

export const permissionGroupGetItemQueryKey = (permissionGroupId: PermissionGroupGetItemPathParams["permissionGroupId"]) =>
	[{url: "/v1/admins/permission-groups/:permissionGroupId", params: {permissionGroupId: permissionGroupId}}] as const;

export type PermissionGroupGetItemQueryKey = ReturnType<typeof permissionGroupGetItemQueryKey>;

export function permissionGroupGetItemQueryOptions(
	permissionGroupId: PermissionGroupGetItemPathParams["permissionGroupId"],
	config: Partial<RequestConfig> & {client?: Client} = {},
) {
	const queryKey = permissionGroupGetItemQueryKey(permissionGroupId);
	return queryOptions<
		PermissionGroupGetItemQueryResponse,
		ResponseErrorConfig<Error>,
		PermissionGroupGetItemQueryResponse,
		typeof queryKey
	>({
		enabled: !!permissionGroupId,
		queryKey,
		queryFn: async ({signal}) => {
			config.signal = signal;
			return permissionGroupGetItem(permissionGroupId, config);
		},
	});
}

/**
 * @description 권한 상세 조회 API
 * @summary v1 권한 그룹 상세 조회
 * {@link /v1/admins/permission-groups/:permissionGroupId}
 */
export function usePermissionGroupGetItem<
	TData = PermissionGroupGetItemQueryResponse,
	TQueryData = PermissionGroupGetItemQueryResponse,
	TQueryKey extends QueryKey = PermissionGroupGetItemQueryKey,
>(
	permissionGroupId: PermissionGroupGetItemPathParams["permissionGroupId"],
	options: {
		query?: Partial<QueryObserverOptions<PermissionGroupGetItemQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
			client?: QueryClient;
		};
		client?: Partial<RequestConfig> & {client?: Client};
	} = {},
) {
	const {query: queryConfig = {}, client: config = {}} = options ?? {};
	const {client: queryClient, ...queryOptions} = queryConfig;
	const queryKey = queryOptions?.queryKey ?? permissionGroupGetItemQueryKey(permissionGroupId);

	const query = useQuery(
		{...permissionGroupGetItemQueryOptions(permissionGroupId, config), queryKey, ...queryOptions} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {queryKey: TQueryKey};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
